### ISSUE TITLE
stats.js file issue turn as error

### ISSUE THREAD

**Issue by ChisdealHDYT** [Sank6/Discord-Bot-List#100]
![image](https://user-images.githubusercontent.com/18028479/86798188-6ca36200-c068-11ea-9c3f-8cead228545f.png)
![image](https://user-images.githubusercontent.com/18028479/86798277-8349b900-c068-11ea-8171-ef5b02add49b.png)

not been touched, API errored connect BOT to API

rate limited broken and no data. as defined to file.

PATH File: https://github.com/Sank6/Discord-Bot-List/blob/master/src/routes/api/auth/stats.js

**Comment by ChisdealHDYT** [comment]
i checked file too when i hashed top 1 and changed data.id to botid and works but its pulling servers default 0 when BOT reads 11 for example code.

![image](https://user-images.githubusercontent.com/18028479/86806437-c445cb80-c070-11ea-8cf0-2dcb835c427e.png)

![image](https://user-images.githubusercontent.com/18028479/86806476-cf98f700-c070-11ea-90bf-b2c7d6e90d53.png)

**Comment by Sank6** [comment]
Changed it to `botid`: 1c1bc89. The database stores every single entry that you post and the date that it was stored. It should retrieve the latest one.

**Comment by ChisdealHDYT** [comment]
i check it out later on see that fixes it, i keep you input if fixed self.

**Comment by ChisdealHDYT** [comment]
that fixed most issues just now still response servers to 0 when custom set to 11
![image](https://user-images.githubusercontent.com/18028479/87016820-1b5db480-c1c7-11ea-90ce-ebf1a209ae7b.png)

**Comment by Sank6** [comment]
Fixed now
