### ISSUE TITLE
Error: Unknown Error While adding bot

### ISSUE THREAD

**Issue by Castmary** [Sank6/Discord-Bot-List#102]
![image](https://user-images.githubusercontent.com/61130335/87607070-1cf51400-c6c2-11ea-9d54-2d42a4b038f1.png)

**Comment by Albala-ux** [comment]
I have this error too

**Comment by rubiksking124** [comment]
i also get this error

**Comment by CrypticKingJoe** [comment]
just refresh, everything else works fine

**Comment by GenryMg** [comment]
I got this error too.

**Comment by GenryMg** [comment]
> just refresh, everything else works fine

Yep, this fixed it

**Comment by Sank6** [comment]
What?

**Comment by GenryMg** [comment]
> What?

This error occurs when you add a bot.

**Comment by Sank6** [comment]
Can you send me the url that this error happens on. Also, did you enter anything invalid in the text boxes?

**Comment by idk-pixel** [comment]
> Can you send me the url that this error happens on. Also, did you enter anything invalid in the text boxes?

 i am getting the same error, and im typing anything correctly. Sadly im running this on local, but i can show what im typing.

![image](https://user-images.githubusercontent.com/63606830/89798690-16f02880-daf2-11ea-8257-1caa52aff05a.png)

**Comment by Sank6** [comment]
Have you set `GUILD_ID`, `BOT_VERIFIERS_ROLE_ID` and `MOD_LOG_ID` correctly in your .env. Also make sure the bot has enough perms to edit to edit that role. If that's all fine, then maybe the client ID isn't from a valid bot user.

**Comment by Duui3111** [comment]
i have the same thing also

**Comment by Duui3111** [comment]
This is how to fix this Error make the bot have a role with admin perms then make the role the highest and give it to the bot if the bot is not the highest it will give you this error

**Comment by idk-pixel** [comment]
> Have you set `GUILD_ID`, `BOT_VERIFIERS_ROLE_ID` and `MOD_LOG_ID` correctly in your .env. Also make sure the bot has enough perms to edit to edit that role. If that's all fine, then maybe the client ID isn't from a valid bot user.

So, I gave my bot the highest role and admin and everything is working now! Thank you for your wonderful code!

**Comment by idk-pixel** [comment]
`const discord // lol`

**Comment by Sank6** [comment]
np!
