### ISSUE TITLE
This is a gif of what happens when i press login in the discord bot list, it says authorize and when i press on it, it brings me there again and when i press authorize again it does that same thing in a loop any help

### ISSUE THREAD

**Issue by ForSomeReasonsYT** [Sank6/Discord-Bot-List#111]
https://gfycat.com/comfortablerecklessiriomotecat
This is a gif of what happens when i press login in the discord bot list, it says authorize and when i press on it, it brings me there again and when i press authorize again it does that same thing in a loop any help

**Comment by ForSomeReasonsYT** [comment]
Btw @Sank6 I changed to heroku!

**Comment by coolman4** [comment]
Same thing with mine

**Comment by coolman4** [comment]
and I'm on heroku

**Comment by Sank6** [comment]
Works fine for me on my pc. Heroku issue?? Not sure.

**Comment by Sank6** [comment]
Did you set the redirect URLs properly?
