### ISSUE TITLE
login loop

### ISSUE THREAD

**Issue by coolman4** [Sank6/Discord-Bot-List#112]
When I click my login button it puts me in a loop over and over and I can't get back to the website even when I press authorize, I looked at my heroku console log and it shows I'm coming back to the website but then it sends me back to /login all over again.

**Comment by Misly16** [comment]
What did you set your redirect url as In the dev portal?

**Comment by coolman4** [comment]
https://essentialbots.herokuapp.com/api/callback is my redirect url

**Comment by coolman4** [comment]
If you go to test it I'm trying to find a soultion, So it may go on and off.

**Comment by coolman4** [comment]
I'm pretty sure it has something to do with this part of code.
`    if (!result) return res.redirect('/login');`

**Comment by sayantan300** [comment]
I know the error, pls show what domain did u wrote in env file? @coolman4

**Comment by sayantan300** [comment]
I even had same error, my error was the I wrote domain as `https://rovelbotlist.glitch.me/` and it was looping... I changed the domain from that to `https://rovelbotlist.glitch.me` (removed `/`) and it works now!

**Comment by Zaid-maker** [comment]
Yes that's the solution

**Comment by sayantan300** [comment]
Lol, all glitch users have the same problem

**Comment by Zaid-maker** [comment]
Yeah I am hosting on a Linux server and my life is much easier

**Comment by sayantan300** [comment]
Can I get ur discord tag & username? Or join my server so I can talk with u
https://discord.gg/Rf3xPMm

**Comment by Zaid-maker** [comment]
Ping me I am in
