### ISSUE TITLE
https://localhost/api/callback Does not work

### ISSUE THREAD

**Issue by ViTraX** [Sank6/Discord-Bot-List#114]
On my console everything is normal

No fine error if

[2020-08-02 01:41:04] Error: Cannot find module 'C: \ Users \ LymeYT \ Desktop \ Discord-Bot-List-master \ node_modules \ canvas-constructor \ dist \ index.js'. Please verify that the package.json has a valid "main" entry

help me

**Comment by sayantan300** [comment]
It should be `localhost:3000/api/callback` or something with ur port no... Not just localhost.

**Comment by sayantan300** [comment]
Whereas I even I had ur same error in console when I tried to host on glitch... Hopefully I solved it... Just go to package.json and change the `canvas-constructor` version to `^4.x`

**Comment by Zaid-maker** [comment]
Well how a localhost is https it cannot be https it only http also don't
update dependencies just install existing dependencies.

**Comment by Zaid-maker** [comment]
Yes you are right

**Comment by sayantan300** [comment]
So @Zaid-maker pls change it then (the name of the package version)

**Comment by Zaid-maker** [comment]
Well I don't own this code lol

**Comment by Sank6** [comment]
Fixed: 584a62d
