### ISSUE TITLE
I'm hosting on glitch and there's a login error

### ISSUE THREAD

**Issue by sayantan300** [Sank6/Discord-Bot-List#116]
My site is on https://rovelbotlist.glitch.me/
When I try to login, either it shows api request error when I use the default link given in ur codes... The ones with \` quotes \` .... But when I generate & use the link from discord dev site with 'identify scope' and edit the code and put in " " then when I press the login it just loops...

**Comment by Zaid-maker** [comment]
You have to set a proper redirect_uri in your dev portal application.

**Comment by sayantan300** [comment]
This makes login loop
https://discord.com/api/oauth2/authorize?client_id=603213294265958400&redirect_uri=https%3A%2F%2Frovelbotlist.glitch.me%2Fapi%2Fcallback&response_type=code&scope=identify

**Comment by Zaid-maker** [comment]
This is not valid redirect_uri link it must be
https://project-name.glitch.me/api/callback

**Comment by sayantan300** [comment]
![Screenshot_20200804-175827](https://user-images.githubusercontent.com/62213554/89293910-534c0080-d67c-11ea-9819-871471639f57.png)

**Comment by sayantan300** [comment]
Can u say what's wrong?

**Comment by sayantan300** [comment]
@Zaid-maker

**Comment by Zaid-maker** [comment]
Yes like that

**Comment by sayantan300** [comment]
So why isn't it working?

**Comment by sayantan300** [comment]
@Zaid-maker

**Comment by sayantan300** [comment]
It says `invalid oauth2 uri`

**Comment by sayantan300** [comment]
And btw the link in ur code has website link at the last, whereas the link generator has it in the middle and perms in the last...

**Comment by Zaid-maker** [comment]
We don't need to use scope it auto done when you start the service show me your DOMAIN variable in .env file

**Comment by sayantan300** [comment]
![Screenshot_20200804-184012~2](https://user-images.githubusercontent.com/62213554/89298627-2ea75700-d683-11ea-8262-4dd0281a1777.png)
Here

**Comment by Zaid-maker** [comment]
Change it to plaintext then show me I cannot see

**Comment by sayantan300** [comment]
Domain : `https://rovelbotlist.glitch.me/`

**Comment by sayantan300** [comment]
Port 3000

**Comment by sayantan300** [comment]
I fixed it by removing `/` from domain at last

**Comment by sayantan300** [comment]
Yay

**Comment by Zaid-maker** [comment]
Congrats dude
