### ISSUE TITLE
I can't delete own bot

### ISSUE THREAD

**Issue by sayantan300** [Sank6/Discord-Bot-List#117]
I'm sure I didn't messed with any code...
https://rovelbotlist.glitch.me/
It dosen't deletes my bot... When I click on delete, it opens a popup with same page and again when I click on delete on popup, popup disappears but my bot dosen't deletes...

**Comment by Zaid-maker** [comment]
Well this is weried because of glitch behaviour

**Comment by sayantan300** [comment]
Shouldn't it delete the data on mongodb?

**Comment by Zaid-maker** [comment]
Yes it will you have to do it from the command xd

**Comment by Zaid-maker** [comment]
The delete button I really don't trust it the one way you can remove the bot is is using the command remove @bot

**Comment by sayantan300** [comment]
Then they should remove the button...
