### ISSUE TITLE
Username button up has a problem

### ISSUE THREAD

**Issue by sayantan300** [Sank6/Discord-Bot-List#119]
Whenever I click my username up it opens the menu along with a loading to my user page... Bruh
https://rovelbotlist.glitch.me/

**Comment by Zaid-maker** [comment]
You just need to hover your mouse on your username

**Comment by sayantan300** [comment]
On mobiles?

**Comment by Zaid-maker** [comment]
For mobiles it has on the bottom of screen if I am not wrong

**Comment by sayantan300** [comment]
Yes..
