### ISSUE TITLE
Problem...

### ISSUE THREAD

**Issue by impressiveaustin** [Sank6/Discord-Bot-List#120]
Hello! Thank you so much for providing such a good template, there is a problem though.

I am hosting the website on Glitch, I have filled EVERY SINGLE THING in .env

But if you go to the website all it says is Starting...

Why is that?

https://botlistfordiscord.glitch.me/

**Comment by Sank6** [comment]
That's because you're using glitch. They stop all processes, which haven't had any visitors in a while to help keep their servers cheap, so every time you go visit the page, the script has to run again, hance "starting..."
