### ISSUE TITLE
There's an error in ur code

### ISSUE THREAD

**Issue by sayantan300** [Sank6/Discord-Bot-List#130]
Go to src/public/errors/index.html and open it, then go below and see the link of saying error with html, at last of the line, remove the comma... @Sank6

**Comment by Sank6** [comment]
Thanks for pointing it out. Fixed: 31af220f8d55829f4a069e6bec7c0933c46f3719

**Comment by Sank6** [comment]
@

**Comment by sayantan300** [comment]
Ok, np

**Comment by sayantan300** [comment]
I was sitting there thinking I never came to that page, so how did I wrote an extra comma 😅
