### ISSUE TITLE
I got hosting, and i got f*****

### ISSUE THREAD

**Issue by idk-pixel** [Sank6/Discord-Bot-List#132]
https://whoaboutyt.is-inside.me/mHuIK8hL.png

What the..
all my oauth redirects are correct.....

**Comment by idk-pixel** [comment]
First comment on issue :D

**Comment by Sank6** [comment]
Make sure you include the oauth redirect url in discord developer settings for the app.

**Comment by idk-pixel** [comment]
> Make sure you include the oauth redirect url in discord developer settings for the app.

to make sure im not doing anything wrong, what should i put there?

**Comment by idk-pixel** [comment]
Fixed.
