### ISSUE TITLE
HTML addon

### ISSUE THREAD

**Issue by idk-pixel** [Sank6/Discord-Bot-List#133]
can you make a HTML for long desc

**Comment by Sank6** [comment]
I tried. The problem is it's really hard to completely stop scripting. Anyone can easily inject malicious code into their description. Removing all HTML was the best option imo. If you can find a library that successfully cleanes all javascript, including inline, then I can try add it.

**Comment by Duui3111** [comment]
Something like this https://www.npmjs.com/package/sanitize-html

**Comment by sayantan300** [comment]
I know, there is a old bot list, u can copy it from there, @Sank6 
The bot list name was/is xeno bot list....
I tried it and it has vote feature and we can post only the <body> part of html and not that <head> part so no one can inject js code and css code in it

**Comment by Sank6** [comment]
@Duui3111 That looks cool. I'm gonna have a look. 
@sayantan300 I don't really know what you mean.

**Comment by idk-pixel** [comment]
> I tried. The problem is it's really hard to completely stop scripting. Anyone can easily inject malicious code into their description. Removing all HTML was the best option imo. If you can find a library that successfully cleanes all javascript, including inline, then I can try add it.

cant you make something in the licences where if anything malicious happens its not your responsibility? We can just ban them and remove the bot.

**Comment by idk-pixel** [comment]
> Till that time ur website will be hacked :/ @idk-pixel

Oh, did not know. Thanks!

**Comment by Sank6** [comment]
It's already in the license. No liability or warranty. Also, **you** won't get hacked, but your innocent users can, if there's some dodgy JS script that downloads malicious software onto their own devices.

**Comment by idk-pixel** [comment]
> It's already in the license. No liability or warranty. Also, **you** won't get hacked, but your innocent users can, if there's some dodgy JS script that downloads malicious software onto their own devices.

Oh, but can you use that package so nothing malicious happensm

**Comment by Duui3111** [comment]
i thing this is how to do it with https://www.npmjs.com/package/sanitize-html
```js
$(document).ready(function () {
    const longD = $("#long");
    const allowedTags = sanitizeHtml.defaults.allowedTags.concat(["img", "center"]);
    const sanitizedRender = sanitizeHtml({ allowedTags });
    longD.html(sanitizedRender);
});
```

**Comment by Sank6** [comment]
Yes, I think it's better to do it in the backend though so it stores already sanitised HTML instead of sanitising it each time.

**Comment by ririko5834** [comment]
Please add html support for description but without scripts

**Comment by Duui3111** [comment]
there is const cheerio = require('cheerio'); 
i thing this how to do it 
```js
const clean = (html) => {
  const $ = cheerio.load(html);
  $('*').each((i, element) => {
      Object.keys(element.attribs)
          .filter(attribute => attribute.startsWith('on'))
          .forEach((attribute) => {
              $(element).removeAttr(attribute);
          });
  });
  $('script').remove();
  $('object').remove();
  return $.html();
};
```

**Comment by Sank6** [comment]
That would still leave the js in the `href`s open and possibly other stuff. I think `sanitizeHtml` is a better choice.

**Comment by idk-pixel** [comment]
@Sank6 does that mean html addon is here soon>

**Comment by Sank6** [comment]
Yes, I'm working on a new long description editor and html support.

**Comment by Sank6** [comment]
Added: 38b9acb935fada292164ece901dedcde09f5c044
