### ISSUE TITLE
Adding a upvote and a online and offline status 

### ISSUE THREAD

**Issue by Duui3111** [Sank6/Discord-Bot-List#137]
So there is the old discord bot list at has the upvote and status code https://github.com/zyrouge/xeno-bot-list

**Comment by sayantan300** [comment]
That's what I was saying @Sank6 #133 this xeno bot list has html and live preview too

**Comment by sayantan300** [comment]
That's what I was saying @Sank6 #133 this xeno bot list has html and live preview too

**Comment by Sank6** [comment]
There already was an online-offline status thing. It was just buggy and didn't work, but it does now. When you go to the bot page, there's a border around the bot's avatar the same colour as its status.

**Comment by ririko5834** [comment]
Please add upvote system
