### ISSUE TITLE
Deleting bots without ownership check

### ISSUE THREAD

**Issue by vladciphersky** [Sank6/Discord-Bot-List#140]
`/api/bots/delete/:botID` able to delete any bot, even if you are not its owner

**Comment by Sank6** [comment]
I had a look at the issue. The endpoint isn't open. Only the **bot developer** and the **admins** can delete a bot. I think you must have tried it signed in as the admin.

**Comment by vladciphersky** [comment]
@mrlivixx tried to delete all bots in bot list (your source), he's not signed as the admin
![image](https://media.discordapp.net/attachments/663398140736569355/746013780848410694/unknown.png)

**Comment by Sank6** [comment]
Oo. My bad. I forgot an `!` in if statement. Should be fixed I think: 670ad0a

**Comment by Sank6** [comment]
Re-open this if it still happens
