### ISSUE TITLE
still no admin badge?

### ISSUE THREAD

**Issue by idk-pixel** [Sank6/Discord-Bot-List#149]
still no admin badge

**Comment by idk-pixel** [comment]
@Sank6

**Comment by Sank6** [comment]
Yeah. It's there. For all the admins in the config.json

**Comment by idk-pixel** [comment]
i made admins for config.json
@Sank6

**Comment by idk-pixel** [comment]
https://discordbotlist.cleverapps.io/user/435899379275137025 im an admin

**Comment by Sank6** [comment]
There was an issue with the badge on the `/me` page, but the rest works fine for me.

**Comment by idk-pixel** [comment]
@Sank6 Does my site work for you?

**Comment by Sank6** [comment]
No, not on your site but I can't seem to reproduce that.

**Comment by idk-pixel** [comment]
@Sank6 i downloaded the code

**Comment by HideakiAtsuyo** [comment]
> 
> 
> https://discordbotlist.cleverapps.io/user/435899379275137025 im an admin

I just did the complete setup of the site by putting me admin and all the other required tasks and it works very well for me...

With /user/:id https://i.imgur.com/64lmGFg.png
With /me https://i.imgur.com/9R7j2FY.png

**Comment by idk-pixel** [comment]
> > https://discordbotlist.cleverapps.io/user/435899379275137025 im an admin
> 
> I just did the complete setup of the site by putting me admin and all the other required tasks and it works very well for me...
> 
> With /user/:id https://i.imgur.com/64lmGFg.png
> With /me https://i.imgur.com/9R7j2FY.png
> 
> In your config.json:
> 
> "admin_user_ids": ["YOUR ID"],
i know my admin is set because im able to do bot commands like .verify

**Comment by idk-pixel** [comment]
WAIT IM SORRY I DIDNT PUT "" BETWEET EACH ID SORRY IM STUPID!!!
