### ISSUE TITLE
how to connect website

### ISSUE THREAD

**Issue by PixelSized** [Sank6/Discord-Bot-List#151]
Ive registered a domain and all that and filled it out in the .env

how does the bot actaully connect to the domain?

**Comment by PixelSized** [comment]
> Take a vps, attach the domaine to it, launch the server! :)

how can i launch this on glitch with a custom domain from freenom

**Comment by Sank6** [comment]
This isn't exactly designed to be hosted on glitch, but I guess you can just import the repository. It should work I think. Ideally though, just put it on a VPS and point an A Name record to it.

**Comment by HideakiAtsuyo** [comment]
Don't use glitch this is just a bad idea but you can buy a vps.

- Point A record to your vps ip
- use certbot if you want https encryption(and use htaccess to force https traffic if certbot doesn't do it)
- Launch your server(discord bot list)
- Go to https://yourdomain:theport
