### ISSUE TITLE
OAuth never goes back to website

### ISSUE THREAD

**Issue by PixelSized** [Sank6/Discord-Bot-List#152]
When no Oauth it gets stuck on wanting to authorise

**Comment by TheRealPikachu** [comment]
Head to your applications, and setup an oAuth link. Permissions: identify and replace it in login.js.

**Comment by Sank6** [comment]
Look at [Step 4](https://github.com/Sank6/Discord-Bot-List/wiki/Setup-Information#setting-up).

**Comment by HideakiAtsuyo** [comment]
Invalid OAuth2 redirect url: https://i.imgur.com/qkbfaAm.png & https://i.imgur.com/wn4wOFl.png (you can choose the port) & https://i.imgur.com/7D9kFIT.png
