### ISSUE TITLE
Bots Command

### ISSUE THREAD

**Issue by TheRealToxicDev** [Sank6/Discord-Bot-List#155]
Bots Command doesn't work as expected, keep getting this error ![image](https://user-images.githubusercontent.com/59587139/91294607-0a590a80-e757-11ea-92f6-089944377b07.jpeg)

On line:

`let bots = await Bots.findOne({ botid: user.id }, { _id: false })`

How can I fix this?? If I ping someone instead of letting it default to me (message.author) it says cannot read property filter of null

**Comment by ririko5834** [comment]
Yes i am getting this error too. Please fix it.
If i mentioned someone: Cannot read property 'filter' of null

**Comment by idk-pixel** [comment]
Happens to me 2.

**Comment by Sank6** [comment]
Which command is this on? What file?

**Comment by Duui3111** [comment]
This one https://github.com/Sank6/Discord-Bot-List/blob/master/src/bot/commands/Bots/bots.js

**Comment by TheRealToxicDev** [comment]
> Which command is this on? What file?

Bots.js

**Comment by Sank6** [comment]
Thanks, fixed: f46af05

**Comment by TheRealToxicDev** [comment]
Awesome thanks for the quick support
