### ISSUE TITLE
Error: Dark theme is not working

### ISSUE THREAD

**Issue by ririko5834** [Sank6/Discord-Bot-List#157]
Hi i switched Dark theme but it is not working :(
![image](https://user-images.githubusercontent.com/64729293/91302942-867b3e80-e7a7-11ea-8c8c-71e051abd3d2.png)
Option is saved in cookies
![image](https://user-images.githubusercontent.com/64729293/91303054-baeefa80-e7a7-11ea-8961-c9d178deb653.png)

**Comment by idk-pixel** [comment]
yes, for me its saved in cookies to. Idk why its happening.

**Comment by idk-pixel** [comment]
it happens for me 2.

**Comment by idk-pixel** [comment]
@Sank6

**Comment by Sank6** [comment]
That could be because of your cache. Try doing a hard refresh on the page: `[ctrl] [shift] [r]`.

**Comment by idk-pixel** [comment]
@Sank6 Ah, yes it is because of cache. But how do i make it so it auto cache's?

**Comment by Sank6** [comment]
Disabled cache on the theme endpoint: 298a6e8
