### ISSUE TITLE
there is a problem posting server stats

### ISSUE THREAD

**Issue by Duui3111** [Sank6/Discord-Bot-List#162]
i get this error `{"success":"false","error":"Count not found in body."}`
when i do it like this ` body: JSON.stringify({"server_count": client.guilds.cache.size}) `

**Comment by Sank6** [comment]
Are you sure you're making a post request? Have a look at [this wiki page](https://github.com/Sank6/Discord-Bot-List/wiki/Server-Count-API).

**Comment by Duui3111** [comment]
yes i am doing it like this 
```js
const fetch = require("node-fetch")

var requestOptions = {
  method: 'POST',
  headers: {
    'authorization': ' this is in the edit page', 
    'Content-Type': 'application/json'
  },
  body: JSON.stringify({"server_count": client.guilds.cache.size}) 
};

fetch("http://localhost:8080/api/auth/stats/710861768653799484/", requestOptions) 
  .then(response => response.text())
  .then(console.log)
  .catch(console.error);
```

**Comment by Sank6** [comment]
Uh idk man. I just tested that code and it works fine for me. Are you sure you're using the latest version?

**Comment by Duui3111** [comment]
let me try to downloaded it again and see

**Comment by Duui3111** [comment]
still the something

**Comment by Sank6** [comment]
I think the issue was with posting stats to a bot that hadn't had any stats posted to it before. Try now: d608428. If it still happens, reopen this.

**Comment by Duui3111** [comment]
still the same thing with the latest update
