### ISSUE TITLE
Suggestion: Auto join user to support server

### ISSUE THREAD

**Issue by ririko5834** [Sank6/Discord-Bot-List#165]
Hi can you please add that botlist will automatilly join user to support server when trying to add bot (something like [this](https://github.com/zyrouge/xeno-bot-list/blob/master/src/server/routers/AddBot.js) ). 
Also add voting system and certified bots soon + more buttons please.
You can inspire by: https://github.com/zyrouge/xeno-bot-list

**Comment by Sank6** [comment]
Please stop staying the same thing across multiple issues. I don't really have time to work on a load of features. If you want, you can try it yourself and PR, or wait till I get around to it.
Also, auto joining the server, without the user's input seems a bit suspicious and you'd need the `guilds.join` scope which is also unnecesarry.
