### ISSUE TITLE
is there a way you can fix the description to go to the second line 

### ISSUE THREAD

**Issue by Duui3111** [Sank6/Discord-Bot-List#169]
like can you make the line go to the second line when it gets to serton point i cant figure it out 
i think it will be like `if(bot.description < 62 then go to the second line but i don't know on how to do it )`

![textline2](https://user-images.githubusercontent.com/67356442/91506073-38e1fd00-e89f-11ea-90f2-c4ffcc17e992.PNG)

**Comment by Sank6** [comment]
Yeah I think canvas constructor has a multiple line text option.

**Comment by Sank6** [comment]
Fixed: 8ba14a8
