### ISSUE TITLE
Posting Stats NodeJS

### ISSUE THREAD

**Issue by bobby365** [Sank6/Discord-Bot-List#170]
what npm package is being used for it?

**Comment by ririko5834** [comment]
You can use this
```js
const fetch = require("node-fetch")

var requestOptions = {
  method: 'POST',
  headers: {
    'authorization': 'your auth token', 
    'Content-Type': 'application/json'
  },
  body: JSON.stringify({"server_count": client.guilds.cache.size}) 
};

fetch("http://yourdomain.com/api/auth/stats/your bot id/", requestOptions) 
  .then(response => response.text())
  .then(console.log)
  .catch(console.error);
```

**Comment by bobby365** [comment]
useing that gives this
Aug 28 00:40:39 discord-bot-list app/web.1 [2020-08-28 07:40:38] [EVENT] /app/node_modules/klasa/src/events/unhandledRejection.js
Aug 28 00:40:39 discord-bot-list app/web.1 [2020-08-28 07:40:38] Error [ERR_UNHANDLED_ERROR]: Unhandled error. ('Uncaught Promise Error: \n' +
Aug 28 00:40:39 discord-bot-list app/web.1 [2020-08-28 07:40:38]   "TypeError: Cannot read property 'time' of undefined\n" +
Aug 28 00:40:39 discord-bot-list app/web.1 [2020-08-28 07:40:38]   '    at /app/src/routes/api/auth/stats.js:23:43\n' +
Aug 28 00:40:39 discord-bot-list app/web.1 [2020-08-28 07:40:38]   '    at runMicrotasks (<anonymous>)\n' +
Aug 28 00:40:39 discord-bot-list app/web.1 [2020-08-28 07:40:38]   '    at processTicksAndRejections (internal/process/task_queues.js:97:5)')
Aug 28 00:40:39 discord-bot-list app/web.1 [2020-08-28 07:40:38]     at KlasaClient.emit (events.js:304:17)
Aug 28 00:40:39 discord-bot-list app/web.1 [2020-08-28 07:40:38]     at module.exports.run (/app/node_modules/klasa/src/events/unhandledRejection.js:12:15)
Aug 28 00:40:39 discord-bot-list app/web.1 [2020-08-28 07:40:38]     at module.exports._run (/app/node_modules/klasa/src/lib/structures/Event.js:101:15)
Aug 28 00:40:39 discord-bot-list app/web.1 [2020-08-28 07:40:38]     at process.emit (events.js:315:20)
Aug 28 00:40:39 discord-bot-list app/web.1 [2020-08-28 07:40:38]     at processPromiseRejections (internal/process/promises.js:209:33)
Aug 28 00:40:39 discord-bot-list app/web.1 [2020-08-28 07:40:38]     at processTicksAndRejections (internal/process/task_queues.js:98:32)

**Comment by ririko5834** [comment]
@bobby365 Add this script to your bot that you want to count servers for.

```js
const fetch = require("node-fetch")

var requestOptions = {
  method: 'POST',
  headers: {
    'authorization': 'your auth token', 
    'Content-Type': 'application/json'
  },
  body: JSON.stringify({"server_count": client.guilds.cache.size}) 
};

fetch("http://yourdomain.com/api/auth/stats/your bot id/", requestOptions) 
  .then(response => response.text())
  .then(console.log)
  .catch(console.error);
```
and replace      'authorization': '**your auth token**', with your auth token and fetch("http://yourdomain.com/api/auth/stats/**your bot id**/", requestOptions)  with your bot id

**Comment by bobby365** [comment]
still does not work

**Comment by Sank6** [comment]
I think the issue was with posting stats to a bot that hadn't had any stats posted to it before. Try now: d608428. If it still happens, reopen this.
