### ISSUE TITLE
 spamming submit button does this

### ISSUE THREAD

**Issue by bobby365** [Sank6/Discord-Bot-List#171]
fix this
![Screenshot (539)](https://user-images.githubusercontent.com/58282117/91524154-5d47d480-e8b3-11ea-9835-110205e0dfef.png)

**Comment by HideakiAtsuyo** [comment]
It's interesting, I suppose you should add a deactivation of the button at the first click.

**Comment by bobby365** [comment]
yeah

**Comment by Sank6** [comment]
Yeah and maybe a check to see if the bot has already been resubmitted

**Comment by bobby365** [comment]
its not

**Comment by HideakiAtsuyo** [comment]
> o see if the bot has already been resubmitted
Yes, so there would be no possibility for spam

**Comment by Sank6** [comment]
Fixed
