### ISSUE TITLE
Bot tags / categories

### ISSUE THREAD

**Issue by bobby365** [Sank6/Discord-Bot-List#174]
add the ability for a website moderator to add a bot with no owner so it can be listed but can be claimed by the owner

add the ability to have tags for bots like moderation, utility, etc

fix the theme toggle

**Comment by Sank6** [comment]
Yeah, toggle theme works fine, but bot tags is a good idea. Idk about listing bots that don't belong to you though. That doesn't make sense because the bot owner didn't give you permission to link their bot on your page.

**Comment by idk-pixel** [comment]
> add the ability for a website moderator to add a bot with no owner so it can be listed but can be claimed by the owner
> 
> add the ability to have tags for bots like moderation, utility, etc
> 
> fix the theme toggle

Did you put in the latest update of theme toggle cache?

**Comment by bobby365** [comment]
what do you mean by that

**Comment by Sank6** [comment]
Added
