### ISSUE TITLE
Multiple bot owners problem

### ISSUE THREAD

**Issue by ririko5834** [Sank6/Discord-Bot-List#175]
Hi i want report bug that multiple bot owners are not showed down in bot description. There is showed only main bot owner. (I mean here: https://github.com/Sank6/Discord-Bot-List/blob/9031f89aacde2e3015caf84dd2a4147dee80b188/src/dynamic/bots.ejs#L80)
![image](https://user-images.githubusercontent.com/64729293/91544241-be0cf680-e91f-11ea-940b-737356e0fa54.png)
Please fix it.

**Comment by Sank6** [comment]
Yes, I am aware of this issue. There's also a few other bugs with multiple owners.

**Comment by ririko5834** [comment]
Ok, please fix them as soon as you can.
