### ISSUE TITLE
still with the new version of status posting does not work 

### ISSUE THREAD

**Issue by Duui3111** [Sank6/Discord-Bot-List#181]
https://github.com/Sank6/Discord-Bot-List/commit/d608428a470226976804da47cd5740a6b17751f8 it gives this error `{"success":"false","error":"Count not found in body."}`
```js
const fetch = require("node-fetch")

var requestOptions = {
  method: 'POST',
  headers: {
    'authorization': ' ', 
    'Content-Type': 'application/json'
  },
  body: JSON.stringify({"server_count": client.guilds.cache.size}) 
};

fetch("http://localhost:8080/api/auth/stats/735698663021900470/", requestOptions) 
  .then(response => response.text())
  .then(console.log)
  .catch(console.error);

```

**Comment by ririko5834** [comment]
Status works for me

**Comment by Duui3111** [comment]
it returns as undefined when  do it like ` body: JSON.stringify({"server_count": client.guilds.cache.size})` but `body: JSON.stringify({"server_count": 100}) ` returns as 100

**Comment by Sank6** [comment]
That means your `client.guilds.cache.size` isn't returning an integer.

**Comment by Duui3111** [comment]
Can you fix that so client.guild.cachezzise will work

**Comment by Sank6** [comment]
That's on your side. Try logging `client.guilds.cache.size` and `typeof client.guilds.cache.size`. See if you get what you wanted to get.

**Comment by Duui3111** [comment]
returns as the server count

**Comment by Duui3111** [comment]
i fixed it it was that i had to put it in the ready event

**Comment by Sank6** [comment]
Ah ok yeah
