### ISSUE TITLE
after applying your fix it stopped working 

### ISSUE THREAD

**Issue by bobby365** [Sank6/Discord-Bot-List#182]
I literally had to roll back my host
![Screenshot (564)_LI](https://user-images.githubusercontent.com/58282117/91633202-441a5300-e99b-11ea-81f2-a22402c9bd94.jpg)

**Comment by Sank6** [comment]
Which fix was this after?

**Comment by bobby365** [comment]
the one where you fix the server count and the theme toggle

**Comment by bobby365** [comment]
I use heroku for my host

**Comment by Sank6** [comment]
Try reinstalling everything. I'm not sure why that's happening

**Comment by bobby365** [comment]
that worked
