### ISSUE TITLE
Request: Remove old server count data after new data received

### ISSUE THREAD

**Issue by ririko5834** [Sank6/Discord-Bot-List#186]
Hi also can you please add that old server count data that were added to database using api will be removed after new data received. Because some bots have more than 100 server count data saved in database (it takes up space in database).

**Comment by Sank6** [comment]
It really shouldn't take up that much. All it stores is a timestamp and a number. I was hoping to add a graph to show server growth over time.

**Comment by ririko5834** [comment]
OK i like graph feature. But can you add that if server count has more than 250x arrays remove them and start from 0 
or add command that admin can reset server count for specific bot

**Comment by Sank6** [comment]
Each additional server count takes up about 50~ bytes, so to take up 1 megabyte, you would need 20,000 server counts posted. That means, if you set your ratelimit to 1 hour. It would take over 2 years for a bot to take up 1 Mb. Even on free tier on MongoDB Atlas, you'd need 500 bots for 2 years posting server count for you to reach the limit. I don't think that's going to matter. 

Correct my maths if I'm wrong

**Comment by ririko5834** [comment]
Ok, Thanks for explanation. And graphs will be good 👍
