### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by RITIKDHAYAL-PHOENIX** [Sank6/Discord-Bot-List#187]
u should make a tutorial vedio on it ... if u can please ...

**Comment by Zaid-maker** [comment]
not even hard to configure the json file if you know web development not hard to start the website.

**Comment by RITIKDHAYAL-PHOENIX** [comment]
Can u just tell me processs start to end once in easy way please....

**Comment by Zaid-maker** [comment]
Well you cantact me on discord DevMirza#6447

**Comment by Sank6** [comment]
Have a look at this: https://github.com/Sank6/Discord-Bot-List/wiki/Setup-Information
