### ISSUE TITLE
new update broke editing bots 

### ISSUE THREAD

**Issue by bobby365** [Sank6/Discord-Bot-List#189]
I replaced every file with the new update it also doesn't even work with HTML

**Comment by Sank6** [comment]
It does work with HTML, it just sanitises the code so there's nothing dangerous in there. The editor has a `source` button to edit the html directly

**Comment by bobby365** [comment]
I see but I entered in some HTML code and it broke the HTML code also now
when you go to edit a bot it just gives an error

**Comment by bobby365** [comment]
it works now
