### ISSUE TITLE
Pug and passport-discord

### ISSUE THREAD

**Issue by idk-pixel** [Sank6/Discord-Bot-List#190]
Is there anything different? I don't wanna re-download and restart everything. I dont know PUG either, So can we revert?

**Comment by Duui3111** [comment]
ya can you try to go back to last one with ejs

**Comment by idk-pixel** [comment]
@Sank6

**Comment by Sank6** [comment]
The code is much neater, especially passport for auth. Also pug is simple. Have a look at the code in `dynamic`. Reinstalling won't be hard though because you just need to keep the config file.

**Comment by idk-pixel** [comment]
k
