### ISSUE TITLE
Search issue

### ISSUE THREAD

**Issue by idk-pixel** [Sank6/Discord-Bot-List#191]
When i go to [mydomain]/bots/search this happens:
{"message":"/home/bas/app_4a657ebb-df74-4a88-ab50-372595c21e85/src/dynamic/includes/nav.pug:15\n    13|                     span.navtext Embed\n    14|             if (cards)\n  > 15|                 a(href=`/user/${user.id}`)\n    16|                     span.navtext #{user.username}\n    17|     a#searcher.navtag.search(href='/bots/search/')\n    18|         img#searchimg(src='/assets/img/search.png' width='26px' height='26px')\n\nCannot read property 'id' o

**Comment by idk-pixel** [comment]
Also  make it so markdown is also supported, now all the bots on the list look kinda ugly

**Comment by ririko5834** [comment]
I am getting this error in in new version with discord passport and pug. Please fix it and add that markdown is also supported.

**Comment by Sank6** [comment]
Fixed
