### ISSUE TITLE
i have a probable install pug 

### ISSUE THREAD

**Issue by Duui3111** [Sank6/Discord-Bot-List#192]
so i do `npm i pug` i get this `npm WARN tar EINVAL: invalid argument, futime` and does not install

**Comment by Sank6** [comment]
Try removing your `package-lock.json` and deleting `node_modules` and reinstalling everything from an admin CMD. If it doesn't work, I don't know what else you could do. Google / StackOverflow.

**Comment by Duui3111** [comment]
still the some thing is it because i have node v12.18.3

**Comment by idk-pixel** [comment]
> still the some thing is it because i have node v12.18.3

Try running npm install? Anything

**Comment by Duui3111** [comment]
I tried it nothing at all

**Comment by Sank6** [comment]
That's an issue with pug then.  Open an issue on their repo, not here.
