### ISSUE TITLE
Update command error

### ISSUE THREAD

**Issue by ririko5834** [Sank6/Discord-Bot-List#194]
I am getting err while running update command
`TypeError: Cannot read property 'displayAvatarURL' of undefined
` and also UpdateOne is not defined

**Comment by idk-pixel** [comment]
@ririko5834 try in the code displayAvatarURL({ format: `png` }) and for UpdateOne change it to updateOne

**Comment by ririko5834** [comment]
I will wait for @Sank6

**Comment by Sank6** [comment]
@idk-pixel 's suggestion should work. I can'tal do anything rn, but I'll add it to the repo when I can

**Comment by Sank6** [comment]
What version are you using. It's already a function: `.displayAvatarURL()`

**Comment by ririko5834** [comment]
I use: ` "discord.js": "^12.2.0",` i think that there it is `avatarURL()`

**Comment by Sank6** [comment]
Oh I see. I'll change it then.

**Comment by Sank6** [comment]
Just checked the docs. It should be working fine: https://discord.js.org/#/docs/main/stable/class/User?scrollTo=displayAvatarURL

**Comment by Sank6** [comment]
Also, I just fixed the updateOne error
