### ISSUE TITLE
edit bot

### ISSUE THREAD

**Issue by idk-pixel** [Sank6/Discord-Bot-List#195]
when i submit bot it don't work now, can we please now switch back to EJS

**Comment by Duui3111** [comment]
Ya i cant event install pug

**Comment by Sank6** [comment]
Switching back to ejs isn't going to fix anything.

**Comment by idk-pixel** [comment]
@Sank6 maybe we should revert? Is it possible do get html without put also markdown

**Comment by Duui3111** [comment]
Plz try if you can

**Comment by idk-pixel** [comment]
> Plz try if you can

I figured out it problem I think do node -v and npm -v and tell me the results

**Comment by idk-pixel** [comment]
@Duui3111

**Comment by Duui3111** [comment]
node v12.18.3 And for npm i think it is v6

**Comment by idk-pixel** [comment]
> node v12.18.3 And for npm i think it is v6

@Duui3111 what's the error when installing pug

**Comment by Duui3111** [comment]
npm WARN tar EINVAL: invalid argument, futime

**Comment by idk-pixel** [comment]
What operating platform are you on @Duui3111

**Comment by idk-pixel** [comment]
> npm WARN tar EINVAL: invalid argument, futime

Also it's a warn, u should have pug

**Comment by Duui3111** [comment]
Win64

**Comment by idk-pixel** [comment]
What do u so to install pug

**Comment by idk-pixel** [comment]
@Duui3111

**Comment by Duui3111** [comment]
npm i pug when i get the error it spam it then stops

**Comment by idk-pixel** [comment]
@Duui3111 try doing node ./src/index

**Comment by Duui3111** [comment]
Tried that do

**Comment by idk-pixel** [comment]
Try npm I node-pre-gyp

**Comment by idk-pixel** [comment]
@Duui3111
