### ISSUE TITLE
Bug Profile Page

### ISSUE THREAD

**Issue by Octavia0509** [Sank6/Discord-Bot-List#197]
![image](https://user-images.githubusercontent.com/66703687/92279727-382d1480-eef8-11ea-8c4f-f1d22b90187d.png)
Hello, I've got a problem when I'm connected, the button "Login" still displayed. 
And, when I create a new profile with a other Discord Acount, I am redirect at the page "Unknown User"...

I am French so my English could be very imperfect

**Comment by MaximilianGT500** [comment]
I have the same Bug

**Comment by ririko5834** [comment]
Yes, same bug

**Comment by Sank6** [comment]
Yes, I am aware of this issue. I forgot to chang the frontend after switching to passport discord. I'm worming on a fix.

**Comment by MaximilianGT500** [comment]
Thanksss

**Comment by Octavia0509** [comment]
Thanks a lot 😁

**Comment by Sank6** [comment]
Fixed
