### ISSUE TITLE
Site Bug

### ISSUE THREAD

**Issue by p9sq** [Sank6/Discord-Bot-List#198]
I try and edit/delete/resubmit a bot, but it doesn't work. I really need it fixed so then my bot list can be public

**Comment by HideakiAtsuyo** [comment]
Where is the error ?

**Comment by p9sq** [comment]
> Where is the error ?

Well, it's not really an error, it's just that nothing is happening, also, when I login, it still says "login" and it doesn't show my discord username and tag.

**Comment by HideakiAtsuyo** [comment]
I set it up a few days ago following an issue but I don't have any of these errors

**Comment by Sank6** [comment]
The login one does exist. I'm working on a fix for it.

**Comment by p9sq** [comment]
> The login one does exist. I'm working on a fix for it.

k

**Comment by Sank6** [comment]
Fixed
