### ISSUE TITLE
found a bug

### ISSUE THREAD

**Issue by bobby365** [Sank6/Discord-Bot-List#202]
![image](https://user-images.githubusercontent.com/58282117/92339852-efe33300-f06c-11ea-9da8-dc892691038e.png)

**Comment by thedev2307** [comment]
have you connected the mongo database correctly?

**Comment by bobby365** [comment]
yes I have it seems to only do it with new people that never have signed
into the website before

**Comment by Sank6** [comment]
Are you sure you aren't missing the file `src/dynamic/user/notfound.pug`?

**Comment by thedev2307** [comment]
> 
> 
> Are you sure you aren't missing the file `src/dynamic/user/notfound.pug`?
is there a way to fix that btw? cuz a member got this after he logged in but he couldnt get on his profile

**Comment by Sank6** [comment]
Yeah check if you have the file

**Comment by idk-pixel** [comment]
@Sank6 notFound.pug, notfound.pug, there's a diffrence between them

**Comment by idk-pixel** [comment]
@Sank6 also when i renamed it to notfound.pug, it worked, but there is a problem, i am in the server but it gives the error

**Comment by Sank6** [comment]
I didn't realise I saved it as `notFound`. Anyway, is this on `/me` or `/user/id`?

**Comment by idk-pixel** [comment]
@Sank6 me is working, user is broken

**Comment by idk-pixel** [comment]
@Sank6 but /user/ is not working
