### ISSUE TITLE
Error code

### ISSUE THREAD

**Issue by CipherHYT** [Sank6/Discord-Bot-List#203]
![BF79D8D1-A394-48BE-91BC-8C109C40AB46](https://user-images.githubusercontent.com/69433762/92417451-d5ba5b00-f127-11ea-896c-06c18e026aae.jpeg)

**Comment by idk-pixel** [comment]
This is not the dbl problem. Please use a correct database.

**Comment by CipherHYT** [comment]
wdym

**Comment by idk-pixel** [comment]
You need a DB to host it. The DB URL was invalid, so you got that error

**Comment by idk-pixel** [comment]
if u need help dm username.#6129 on discord

**Comment by CipherHYT** [comment]
I sent a friend request

**Comment by Sank6** [comment]
Your MongoDB url link is invalid. Have a look at the config
