### ISSUE TITLE
Server API issue

### ISSUE THREAD

**Issue by ZeroNation20** [Sank6/Discord-Bot-List#213]
When trying to start the bot with the API it'll say headers is not defined. Everything put in correctly. Any fix?

**Comment by discord-bot-purchases** [comment]
Give the code? How are we supposed to help with no code...

**Comment by ZeroNation20** [comment]
//var myHeaders = new Headers();
//myHeaders.append("authorization", "mytokenalreadyadded");
//myHeaders.append("Content-Type", "application/json");

//var requestOptions = {
 // method: 'POST',
 // headers: myHeaders,
//  body: JSON.stringify({"server_count" : 500}) // Replace this number with the server count
//};

//fetch("mydomainweb/api/auth/stats/688370250059874338", requestOptions) // Make sure you include the domain
  //.then(response => response.text())
//  .then(console.log)
 // .catch(console.error)

**Comment by Sank6** [comment]
I'll fix it in the wiki, but I think you can just use an object with those properties with node fetch.

**Comment by ZeroNation20** [comment]
Not sure. We tried other ways but didn't work at all, if you can fix it, it'll be amazing. Cuz its the first part that didn't work at all

**Comment by ZeroNation20** [comment]
this brings us to the no user found page even though the user exists and the user has bots on the list

const { Router } = require("express");
const Bots = require("@models/bots");

const { server: {admin_user_ids} } = require("@root/config.json")

const route = Router();

route.get("/:id", async (req, res, next) => {
    let user = req.app.get('client').users.fetch(req.params.id);
    if (!user) return res.render("user/notfound", {user: req.user})

    let bots = await Bots.find({}, { _id: false })
    bots = bots.filter(bot => bot.owners.includes(user.id))
    
    if (bots.length === 0) return res.render("user/notFound", {user: req.user})
    let data = {
        user: user,
        cards: bots,
        admin: admin_user_ids.includes(req.params.id),
        isProfile: true
    }
    res.render("user/index", data);
});

module.exports = route;

**Comment by Sank6** [comment]
Fixed the user issue

**Comment by ZeroNation20** [comment]
The issue is still happening to the users

**Comment by ZeroNation20** [comment]
![Screenshot_20200911-161754](https://user-images.githubusercontent.com/51929773/92959012-16391200-f463-11ea-88bf-0799e74f196a.png)

**Comment by ZeroNation20** [comment]
![unknown](https://user-images.githubusercontent.com/51929773/92959097-294be200-f463-11ea-85c8-01c183f0aef2.png)

**Comment by Sank6** [comment]
Not for me. Did you update it?

**Comment by ZeroNation20** [comment]
Yeah I updated it

**Comment by ZeroNation20** [comment]
Alright. Now it's working, thank you! If you fix the API it'll mean a lot. Thanks again!

**Comment by discord-bot-purchases** [comment]
That's on your end. Its your code. In js never heard of Headers(), is it defined? lso in nose fetch you can make options and make otpions for exa pls var lots = {
headers: 
}
}
Fetch('uri', lots)

**Comment by Sank6** [comment]
Yeah I just need to update it on the wiki.

**Comment by Sank6** [comment]
Done
