### ISSUE TITLE
Error On Submiting Bot

### ISSUE THREAD

**Issue by hello936** [Sank6/Discord-Bot-List#217]
Hello @Sank6 when I try to submit a bot, it just refreshes and doesn't submit the bot. This error is only for some users and not all users.

**Comment by hello936** [comment]
@Sank6 do you know what the issue is?

**Comment by Sank6** [comment]
Not sure. I'll have a look. Any error?

**Comment by hello936** [comment]
@Sank6 do you mind if I send in a screen recording?

**Comment by Sank6** [comment]
You can if you want, but it's not that I don't trust you. I just don't have much time to work on this. I'll have a look when I can.

**Comment by hello936** [comment]
okay @Sank6

**Comment by Sank6** [comment]
Hey, I couldn't reproduce the issue so I added some try catch statements. If it still happens, can you reopen this issue and send the console error message on both the client and server side, whichever exist.
