### ISSUE TITLE
What is mongo url?

### ISSUE THREAD

**Issue by EditeY** [Sank6/Discord-Bot-List#220]
"mongo_url": "", 

what is mongo url?, what im to write

**Comment by MaximilianGT500** [comment]
The Mongo url is the Database also go to mongo and create a Atlas and then Go Go Access and create a bot Account and Thema go to your Atlas and then to Connect

**Comment by Sank6** [comment]
Have a look at the [Setup Info](https://github.com/Sank6/Discord-Bot-List/wiki/Setup-Information)
