### ISSUE TITLE
Avatar URL Change

### ISSUE THREAD

**Issue by idk-pixel** [Sank6/Discord-Bot-List#221]
Hello, when people change the bot of their avatar.it doesn't update. Can you make it so it auto update

**Comment by Sank6** [comment]
That's what the `update` command in the bot should do, but I see what you mean. I think instead of storing the avatar in the database, it would be better to just fetch it each time. I'll add it to the readme

**Comment by Sank6** [comment]
I added some events, like viewing the bot page or using the botinfo command that'll update the avatar. Other things like the home page and search page will still use the cached version of the avatar
