### ISSUE TITLE
Invalid OAuth2 redirect_uri Problem

### ISSUE THREAD

**Issue by zarar2312** [Sank6/Discord-Bot-List#223]
Please how can it fix [https://prnt.sc/ugvndt](url)

**Comment by DynamoYT** [comment]
Same

**Comment by zarar2312** [comment]
l fixed it. @DynamoYT vote system how to used?

**Comment by DynamoYT** [comment]
I'm fixing it rn

**Comment by DynamoYT** [comment]
https://github.com/Sank6/Discord-Bot-List/wiki/FAQs

**Comment by zarar2312** [comment]
@DynamoYT UPVOTE system how it used?
