### ISSUE TITLE
Login 404

### ISSUE THREAD

**Issue by shootdot** [Sank6/Discord-Bot-List#226]
Error 404 on login page 
https://i.imgur.com/CMx88B3.png

**Comment by DyIster** [comment]
Same error

**Comment by ririko5834** [comment]
Yes, its because 404 error page

**Comment by Zaid-maker** [comment]
obv the 404 page working fine xd

**Comment by Zaid-maker** [comment]
you have to login lmao

**Comment by ForSomeCodezYT** [comment]
They cant.. with this new commit.. when someone presses on Login it takes them to 404 page...

**Comment by DyIster** [comment]
We go to localhost/login and it literally shows a 404 error. We can't login

**Comment by Naiym223** [comment]
same rror

**Comment by Naiym223** [comment]
When do you think a fix will be put in?

**Comment by Naiym223** [comment]
@Sank6 Do you think it will be fixed today?

**Comment by Sank6** [comment]
I'll try but not sure. Just go back to the previous commit for now

**Comment by Naiym223** [comment]
@Sank6 Sorry for the tag, but how do I go back? I didn't have the old version, is there a way to view previous commits?

**Comment by Sank6** [comment]
Just clone the repo and select the checkout the commit. Google it.

**Comment by ririko5834** [comment]
Old version works for me

**Comment by Sank6** [comment]
Fixed. Update :)
