### ISSUE TITLE
[SUGGESTION] - Add bot status

### ISSUE THREAD

**Issue by Naiym223** [Sank6/Discord-Bot-List#229]
You should add it so it can say "Playing a game: watching the bots" or something, instead of it just being a green dot (indicating that it's online) so add a bot playing status.

**Comment by Sank6** [comment]
Oh yeah that's a good idea. Maybe on the bot info page. I didn't realise this info was on the API, but it looks like it is.

**Comment by ririko5834** [comment]
This is great idea 👍

**Comment by Zaid-maker** [comment]
ima add that.

**Comment by Sank6** [comment]
That wasn't the suggestion but it's a good features anyway.

**Comment by Sank6** [comment]
Added
