### ISSUE TITLE
Admin User ID's

### ISSUE THREAD

**Issue by Naiym223** [Sank6/Discord-Bot-List#230]
I am trying to put 2 ID's as admins:

["504423728478683157,359471285090123800"],

Does not work, when I do that it doesn't display anyone as admin. Nor does the bot verifier role work, it still says "You don't have permission to use this command.)

The only time the Admin ID works if it is one person e.g:

["504423728478683157"],

Anyone please help.!

**Comment by Sank6** [comment]
That's not how arrays work. Admin IDs are individual strings (separated by commas).
