### ISSUE TITLE
[SUGGESTION] Add User's Profile Picture, to website profile.

### ISSUE THREAD

**Issue by Naiym223** [Sank6/Discord-Bot-List#231]
Instead of the localhost/user/504423728478683157 just showing the user's username and bots, you should add it so that it also displays their profile picture, so it makes us know who they are a bit more.

**Comment by Discord-Bot-List** [comment]
Their user id, but still a great idea!

**Comment by ririko5834** [comment]
Profile picture is a great idea.

**Comment by Zaid-maker** [comment]
Google will automatically did this when you run the bot list on a domain.

**Comment by Sank6** [comment]
Added
