### ISSUE TITLE
[SUGGESTION] Make the bot dm the bot owner, when bot is verified or removed.

### ISSUE THREAD

**Issue by Naiym223** [Sank6/Discord-Bot-List#232]
Make the bot, direct message the bot author/owner if their bot has been declined or accepted.

**Comment by TheRealPikachu** [comment]
This is possible

**Comment by hello936** [comment]
I would also like this

**Comment by TheRealPikachu** [comment]
Can I try making this

**Comment by ririko5834** [comment]
Yes, this is possible, i have it

**Comment by Zaid-maker** [comment]
Yes we need that feature

**Comment by Zaid-maker** [comment]
> Can I try making this

Yes sure dide

**Comment by hello936** [comment]
@TheRealPikachu can you pass me the code for this? other then that @Sank6 should make this

**Comment by Sank6** [comment]
?? Yes I will work on this but anyone can make a pr.

**Comment by hello936** [comment]
ok cool.

**Comment by hello936** [comment]
@Sank6 how the progress on this

**Comment by Sank6** [comment]
Added

**Comment by hello936** [comment]
@Sank6 coolio
