### ISSUE TITLE
[BUG] Bot info, doesn't include the bots prefix.

### ISSUE THREAD

**Issue by Naiym223** [Sank6/Discord-Bot-List#236]
![image](https://user-images.githubusercontent.com/40970290/93607179-fd66ba00-f996-11ea-8aca-42b448f02c2f.png)

**Comment by Sank6** [comment]
Yeah I didn't really know where to place it. The prefix is still stored in the database. Any suggestions for positioning?

**Comment by Naiym223** [comment]
> Yeah I didn't really know where to place it. The prefix is still stored in the database. Any suggestions for positioning?

--
I would say put it under the bots status, OR put it under the short description.

**Comment by Sank6** [comment]
Yeah I guess maybe if I make the bot icon larger, there'll be space for the prefix beside. I was thinking utilising the free space on the top right side, but I don't know how.

**Comment by Naiym223** [comment]
Oh! Or you can put it under the bot icon. That would look pretty good

**Comment by Sank6** [comment]
Oh yeah. Under the icon sounds good.

**Comment by ririko5834** [comment]
Yes 👍

**Comment by Sank6** [comment]
Fixed
