### ISSUE TITLE
Error 404

### ISSUE THREAD

**Issue by shootdot** [Sank6/Discord-Bot-List#240]
Hello,
I added one extra page and added a .pug file in the dynamic folder but when I try to access it I get 404 error how do I fix it ?

**Comment by Sank6** [comment]
It's dynamic. You need to add the routes.

**Comment by shootdot** [comment]
So how can I add it ?

**Comment by Sank6** [comment]
You need to add express routing for the page.: https://expressjs.com/

**Comment by shootdot** [comment]
I found it already btw thanks for helping

>
