### ISSUE TITLE
Wrong output from commands

### ISSUE THREAD

**Issue by DyIster** [Sank6/Discord-Bot-List#241]
marknsfw returns no longer marked nsfw and notnsfw returns now marked nsfw

**Comment by Zaid-maker** [comment]
Not hard just check the code in verify command maybe

**Comment by DyIster** [comment]
Yes I know it isn't hard to fix I'm just bringing it up

**Comment by Zaid-maker** [comment]
> Yes I know it isn't hard to fix I'm just bringing it up

Good

**Comment by Sank6** [comment]
Fixed
