### ISSUE TITLE
Advice, Suggestions and help

### ISSUE THREAD

**Issue by rockoj** [Sank6/Discord-Bot-List#244]
Hi I need your help urgently. The new config.js says unmuted what this, also whats the difference btw admin and bot verifier role?

**Comment by rockoj** [comment]
My tag is Tube#1996 I'm not always on GitHub and I will accept your friend request or you can talk here

**Comment by Sank6** [comment]
`unmuted` is under the roles section. Admins have more perms than bot verifiers.

**Comment by rockoj** [comment]
ok. what is the unmuted for?

**Comment by Sank6** [comment]
It's a role that unmuted bots have.
