### ISSUE TITLE
suggestions

### ISSUE THREAD

**Issue by the-cute-panda** [Sank6/Discord-Bot-List#246]
here's what I think would be nice having

ability to have ads in the website

ability to have a promoted bot either through a mod adding it in promotion or an auction

have categories like what's in top.gg instead of just having all bots just be mixed together

ability to remove bots straight from the website instead of having to use the bot constantly

ability to ban someone from the website

**Comment by Sank6** [comment]
Most of these have been suggested already. I'm not going to add ads / promoted content to this because it's free and open sourced. Everything else is being worked on. Please remember this isn't a top.gg clone or trying to be either, so features aren't going to match up.
