### ISSUE TITLE
Error: Cannot find module 'module-alias/register'

### ISSUE THREAD

**Issue by metinyalcink** [Sank6/Discord-Bot-List#247]
![image](https://user-images.githubusercontent.com/67004487/94179427-26aaad00-fea5-11ea-9501-a13f814d1359.png)
![image](https://user-images.githubusercontent.com/67004487/94179460-32966f00-fea5-11ea-9e25-f10d0d0de81d.png)
ı need help

**Comment by Sank6** [comment]
Install it: `npm i`
