### ISSUE TITLE
connect ECONNREFUSED 127.0.0.1:27017

### ISSUE THREAD

**Issue by GCRX** [Sank6/Discord-Bot-List#249]
ERROR: connect ECONNREFUSED 127.0.0.1:27017 HELP ME

**Comment by Zaid-maker** [comment]
Because your ip address is refusing to connect to the database on mongodb

**Comment by GCRX** [comment]
> Because your ip address is refusing to connect to the database on mongodb

How Can I Fix This?

**Comment by Sank6** [comment]
Make sure you whitelist your IP address or all IPs (if you're using Atlas)
