### ISSUE TITLE
How do I confirm the added bot

### ISSUE THREAD

**Issue by metinyalcink** [Sank6/Discord-Bot-List#250]
How do I confirm the added bot

**Comment by Zaid-maker** [comment]
Wym by confirming bot you have to setup your server lol for logging bot adding or declines.

**Comment by metinyalcink** [comment]
what is lol

**Comment by metinyalcink** [comment]
Please can you write properly so that I can translate

**Comment by metinyalcink** [comment]
> Wym by confirming bot you have to setup your server lol for logging bot adding or declines.

Please can you write properly so that I can translate
