### ISSUE TITLE
Site Erro

### ISSUE THREAD

**Issue by rockoj** [Sank6/Discord-Bot-List#253]
I logged in and everything and did what was needed on my protodactyl panel and got can't connect to site. What do I do to get my site working and operational. No I can't afford a VPs that why I'm using a free protodactyl panel from my Friends

**Comment by discord-bot-purchases** [comment]
Hey there, my name is WhoAboutYT!

Sadly the ptreoactdyl panel won't work unless it's a seperate node. As there is no **free** panels, I'm guessing your using danbot host. Danbot won't work just to keep you in mind.
Thanks!

**Comment by discord-bot-purchases** [comment]
Also, this is not a site error. This is your panel.
