### ISSUE TITLE
not showing full description..

### ISSUE THREAD

**Issue by RITIKDHAYAL-PHOENIX** [Sank6/Discord-Bot-List#256]
![image](https://user-images.githubusercontent.com/57560515/94496133-27c73b80-0211-11eb-9d74-23cfb5a0dbef.png)

i typed a long description and its only showing 40-50 char. its not showing letter characters.... 

how to fix this...

**Comment by RITIKDHAYAL-PHOENIX** [comment]
its showing full description but its in a single line.. how to make this in more lines instead of one line...

**Comment by Sank6** [comment]
That's because it's all one word. I'll fix it when I can on the repo, but it's just css `word-wrap`

**Comment by RITIKDHAYAL-PHOENIX** [comment]
ok , can u add one more button like this for discord support server i add a button but not able to href it to provided link by users. 
![image](https://user-images.githubusercontent.com/57560515/94628163-ebf9a800-02dc-11eb-92d4-a363e84d8bfc.png)

**Comment by Sank6** [comment]
Has already been suggested and is in the readme

**Comment by RITIKDHAYAL-PHOENIX** [comment]
any news when the update of voting system and more button like support server link and other when it will come.

**Comment by Sank6** [comment]
I'm quite busy with exams now. I'll work on it when I can.

**Comment by Sank6** [comment]
Fixed
