### ISSUE TITLE
unable to get index

### ISSUE THREAD

**Issue by the-cute-panda** [Sank6/Discord-Bot-List#258]
I went and got myself a dedicated host and then I download all new files to start fresh and this happened
![image](https://user-images.githubusercontent.com/71202582/94786053-549c5f80-0385-11eb-95e2-c7433dd84be1.png)

**Comment by Sank6** [comment]
Do you have the files in the right folder?

**Comment by the-cute-panda** [comment]
yes 
![Screenshot (824)](https://user-images.githubusercontent.com/71202582/94848694-39f3d600-03d9-11eb-8420-35e9ea39d206.png)

**Comment by the-cute-panda** [comment]
![Screenshot (825)](https://user-images.githubusercontent.com/71202582/94848907-863f1600-03d9-11eb-89a5-adc7acdd909a.png)

**Comment by the-cute-panda** [comment]
I have it on a VPS that is running Ubuntu

**Comment by Sank6** [comment]
Works fine for me. Maybe it's something to do with the folder you're running it from.

**Comment by the-cute-panda** [comment]
I know I haven't changed anything in the folders my bot works just fine on
the server and I'm able to host a simple website on it

**Comment by Sank6** [comment]
I mean the folder you're running it from. Make sure you're "cd"ing to the root folder and running `node src/index.js`

**Comment by the-cute-panda** [comment]
I'm running it like normal

**Comment by Sank6** [comment]
Works for me, so it's related to your setup.

**Comment by the-cute-panda** [comment]
I know there's nothing wrong with it because everything else works just
fine

**Comment by the-cute-panda** [comment]
im using digitalocean to have my vps

**Comment by Sank6** [comment]
Can you explain how you're running it.

**Comment by the-cute-panda** [comment]
im starting it like this 
![Screenshot (832)_LI](https://user-images.githubusercontent.com/71202582/94944123-a5977b00-048d-11eb-910d-49dee4110ff2.jpg)

**Comment by Sank6** [comment]
Yeah go up a folder and try `pm2 start src/botlist.js`

**Comment by the-cute-panda** [comment]
I did that and got it to start but its still not working

**Comment by Sank6** [comment]
Not entirely sure why then. Maybe it's something to do with pm2 and module alias?

**Comment by the-cute-panda** [comment]
I started it without pm2 and just started it with node but it did the same
thing

**Comment by Sank6** [comment]
Try checking to see uf you actually have the files in `src/dynamic`

**Comment by the-cute-panda** [comment]
I do files in src/dynamic

**Comment by Sank6** [comment]
It works fine for me. There's not enough information to reproduce this issue. I'm sorry I can't help.

**Comment by TeamColaDev** [comment]
src/index.js
