### ISSUE TITLE
fields.flat is not a function

### ISSUE THREAD

**Issue by rockoj** [Sank6/Discord-Bot-List#259]
fields.flat is not a function
 
![Screenshot_20201001-192549](https://user-images.githubusercontent.com/53316573/94843718-62052880-041d-11eb-99a1-bedf609e25ec.png)

im not sure what wrong and How to fix it. Someone help me

**Comment by Sank6** [comment]
I'm not getting this error. Do you have the right versions of the modules installed?

**Comment by ririko5834** [comment]
I know this error is caused because of using another node version. Try to remove embeds from all messages and it will work.

**Comment by XysID** [comment]
Hi, @rockoj!

I'm suggest you to upgrade your node.js to latest LTS (12)
You can upgrade it by using this on your `package.json`

```
  "engines": {
    "node": "12.x"
  },
```
