### ISSUE TITLE
Website Help

### ISSUE THREAD

**Issue by GameDevolopersGroup** [Sank6/Discord-Bot-List#261]
I want Help with website 
i have a domain named http://f20-bot.ml
but in config.js i have added it but its not working

Can anyone give me a quick Guide Of website

**Comment by discord-bot-purchases** [comment]
its config.json

**Comment by Sank6** [comment]
You need to actually run the website. Have a look at [the setup guide](https://github.com/Sank6/Discord-Bot-List/wiki/Setup-Information).
