### ISSUE TITLE
sumbting bot doesn't work

### ISSUE THREAD

**Issue by hello936** [Sank6/Discord-Bot-List#262]
I own my own botlist, but I can even add my own bot. It never works!!! Can you fix this??? @Sank6

**Comment by Sank6** [comment]
Works fine for me. Is there something wrong with your config?

**Comment by hello936** [comment]
Nope! In fact it works for majority of the people. But some people like me, it doesn't submit. It just stays at the form and reloads. It doesn't take me to the success page. @Sank6

**Comment by Sank6** [comment]
Maybe there's an issue with the config or what you're entering?

**Comment by hello936** [comment]
@Sank6 Nope! Everything is correct.

**Comment by hello936** [comment]
@Sank6 I have tried re-installing it multiple times and it still doesn't work.

**Comment by Sank6** [comment]
I can't seem to be able to reproduce this problem. I can't help you without more information.
