### ISSUE TITLE
Color Change

### ISSUE THREAD

**Issue by shootdot** [Sank6/Discord-Bot-List#264]
How do I change the color ? in CSS it's `--primary`. How can I change the color of `--primary`

**Comment by shootdot** [comment]
and I am getting this error in console i dont know if it will cause problem but yet it didn't cause
https://i.imgur.com/h9XW4H5.png

**Comment by shootdot** [comment]
![image](https://user-images.githubusercontent.com/55920587/94998175-e643e100-05c0-11eb-8f0f-98dc591d199e.png)

**Comment by Sank6** [comment]
That error shouldn't cause any problems. Change the colours in the theme files in the dynamic folder.
