### ISSUE TITLE
Hey there! Every time I try and add a bot, it says "Unknown Error"

### ISSUE THREAD

**Issue by EggyOnCrack** [Sank6/Discord-Bot-List#267]

**Comment by EggyOnCrack** [comment]
![Uploading image.png…]()

**Comment by Sank6** [comment]
Uhh, check your config file.

**Comment by EggyOnCrack** [comment]
> Uhh, check your config file.

![image](https://user-images.githubusercontent.com/69737561/95033946-6f235f80-071c-11eb-95eb-389b6ef0655f.png)

**Comment by EggyOnCrack** [comment]
![image](https://user-images.githubusercontent.com/69737561/95034180-4c457b00-071d-11eb-95d6-67dce881cac4.png)
