### ISSUE TITLE
I figured out how to know if a bots verified or not 

### ISSUE THREAD

**Issue by discord-bot-purchases** [Sank6/Discord-Bot-List#270]
I figured it out!! For the field of the if its a verified bot or not, 

This is what you do,

if(client.user.flags.has('VERIFIED_BOT') {
 idk create div class thingy
}

**Comment by discord-bot-purchases** [comment]
So basiccly you could do:

client.users.cache.get(bot_id).user.flags.has('VERIFIED_BOT')

**Comment by Sank6** [comment]
Oh cool, I'm guessing you're suggesting this to be added as a feature. I'll add it to the readme. 👍

**Comment by Sank6** [comment]
Added
