### ISSUE TITLE
Cannot read property 'bot_developer' of undefined

### ISSUE THREAD

**Issue by idk-pixel** [Sank6/Discord-Bot-List#275]
Cannot read property 'bot_developer' of undefined

The .verify command does this.

**Comment by idk-pixel** [comment]
It sends it to mod log, but it gives error

**Comment by Sank6** [comment]
Ok, I'll have a look

**Comment by Sank6** [comment]
Check your config file has `role_ids`

**Comment by Sank6** [comment]
Oh wait it happens for the `remove` command, not verify.

**Comment by Sank6** [comment]
Fixed
