### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by RITIKDHAYAL-PHOENIX** [Sank6/Discord-Bot-List#276]
I not understand how to connect a GoDaddy domain to this web please help me what exactly i have to do to connect my domain to my code...

**Comment by ayaan1005** [comment]
how can we use server count api?

**Comment by Sank6** [comment]
Please stop spamming issues. I have already answered: https://github.com/Sank6/Discord-Bot-List/issues/273#issuecomment-703791485

**Comment by Sank6** [comment]
And @ayaan1005 , look at the wiki

**Comment by RITIKDHAYAL-PHOENIX** [comment]
@Sank6  am not understanding in your wiki please help me

**Comment by Sank6** [comment]
Please google it. Use a DNS record to point the c
domain to your host. It isn't related to this repo.
