### ISSUE TITLE
Updating.

### ISSUE THREAD

**Issue by JectaEx** [Sank6/Discord-Bot-List#292]
# Hey! 
### So basicly you guys are making this project better and better but i would like to update my instance of it with new things you guys are updating on the git. Is there an easy way to do that?

**Comment by Sank6** [comment]
I guess you can just clone the github repo: `git clone https://github.com/Sank6/Discord-Bot-List`. And then for every update, just do `git pull origin master` to get the new stuff. It shouldn't overwrite your config file because it's in the `.gitignore`. 👍

**Comment by Zaid-maker** [comment]
Cloning the repo is the best way.
