### ISSUE TITLE
Just a Question

### ISSUE THREAD

**Issue by shootdot** [Sank6/Discord-Bot-List#296]
Hey there 
In Readme you have have Server Count API how can I access that ?

**Comment by Zaid-maker** [comment]
Hello 
So if you have added any bot to your bot list that is owned by you and you want to post server count right so all have to do is go to your bots edit page then scroll down to the end click on authorization token copy that and I advise u to use node-fetch to post server count.

**Comment by shootdot** [comment]
@Zaid-maker Hey there Thanks for the information would you mind if u provide a sample code please ?

**Comment by Zaid-maker** [comment]
Yeah sure I will as soon as possible I am on my PC.

**Comment by shootdot** [comment]
THanks

**Comment by Sank6** [comment]
https://github.com/Sank6/Discord-Bot-List/wiki/Server-Count-API

**Comment by Zaid-maker** [comment]
No he wants the example of node-fetch

**Comment by Sank6** [comment]
That is node fetch

**Comment by Zaid-maker** [comment]
But some people confuse at that point.
