### ISSUE TITLE
Error: Failed to lookup view "index" in views directory "src/dynamic"

### ISSUE THREAD

**Issue by iamKTD** [Sank6/Discord-Bot-List#299]
How do I fix the "**Error: Failed to lookup view "index" in views directory "src/dynamic"**" error?

**Comment by Sank6** [comment]
Make sure you're running it from `npm start` or `node src/index.js` and not `node index.js`

**Comment by iamKTD** [comment]
Okay, that worked, but I ran into another issue:

Uncaught Promise Error:
**Error: The module '/var/www/[domain name]/node_modules/canvas/build/Release/canvas.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 72. This version of Node.js requires
NODE_MODULE_VERSION 88. Please try re-compiling or re-installing**

How do I upgrade canvas from version 72 to 88?

I installed the modules once again after I changed my node version but that didn't work. Any suggestions of common fixes?
Thanks. Great work on the Bot List btw!

**Comment by Zaid-maker** [comment]
Try to properly install the dependencies because canvas take some time to install.

**Comment by Sank6** [comment]
That's probably the issue. You installed canvas on a different node version to the one you're running it with. Delete the `node_modules` folder and then retry `npm i`

**Comment by Zaid-maker** [comment]
Yup sank this is the solution.

**Comment by iamKTD** [comment]
Solved! Thanks.. worked like a charm.

**Comment by Zaid-maker** [comment]
Ok we loved to hear that.
