### ISSUE TITLE
Site not displaying properly

### ISSUE THREAD

**Issue by iamKTD** [Sank6/Discord-Bot-List#302]
Hi Sank6,

I ran into a third issue. After I managed to get it up and running fine, connected MongoDB, editing configurations, etc., the site looked like this:

![image](https://user-images.githubusercontent.com/44924113/97085925-dbe09a00-15f6-11eb-9318-4771ee13acf2.png)
![image](https://user-images.githubusercontent.com/44924113/97085936-eac74c80-15f6-11eb-895c-cc407f8ec9c2.png)
![image](https://user-images.githubusercontent.com/44924113/97085946-f31f8780-15f6-11eb-956b-a7e5c3e5c90f.png)

Fixes I've tried
- Use my phone to load the page
- Changed Internet Browser
- Cleared cache
- Restarted my server

I am using Cloudflare btw.

What can I do to fix this? Please provide suggestions and/or common fixes.

Thanks.

**Comment by Zaid-maker** [comment]
the css is not loading

**Comment by Zaid-maker** [comment]
@iamKTD  How command you use to start the application?

**Comment by Sank6** [comment]
Yeah it appears your CSS isn't loading. Make sure you're running `npm start`

**Comment by Zaid-maker** [comment]
yup
