### ISSUE TITLE
Website isn't showing

### ISSUE THREAD

**Issue by Infinityisgreat** [Sank6/Discord-Bot-List#311]
I go to the website which for me is https://Infinityisgreat.github.io
and it just shows this
Infinityisgreat.github.io
About
This is a discontinued discord bot list. I still maintain it occasionally, so feel free to use it. There’s a setup guide in the wiki if you’re interested. If you have any issues, check the FAQs first please.

Screenshots
Front Page Dark Theme Bot Page

Features
HTML descriptions
Minimalistic website (with dark theme)
Bot resubmit option
Bot widget
Search option
Easy setup (all customisation features in one file)
Discord bot for bot verification
Server count API
To Do
Vote / upvote feature
Certified / verified bots
Mark bot as NSFW when submitting
More bot fields like support server invite link, Github repo and Website
Dynamic Sitemap
Admin panel
This site is open source. Improve this page.

idk how to fix it please help me

**Comment by Sank6** [comment]
You can't just put it on GitHub pages. You have to host it. Check the setup guide in the wiki.
