### ISSUE TITLE
Error: listen EACCES: permission denied 0.0.0.0:80 when connecting to MongoDB

### ISSUE THREAD

**Issue by haydenwalker980** [Sank6/Discord-Bot-List#315]
I'm trying to host this but it keeps giving me this error. Allowing all IPs doesn't solve it.

**Comment by Zaid-maker** [comment]
Use 0:0:0:0 as a IP address in network section.

**Comment by haydenwalker980** [comment]
Tried but I still get this error.
![image](https://user-images.githubusercontent.com/37120379/98575370-fa3ccb80-226d-11eb-889b-db5fac8836ce.png)

**Comment by haydenwalker980** [comment]
I swapped VPS providers and that solved the issue. I still have another issue though.
