### ISSUE TITLE
If I run project, It ends up as an error.

### ISSUE THREAD

**Issue by CipherHYT** [Sank6/Discord-Bot-List#317]
I am using repl.it for the Discord Bot List and when I clicked run, it starts npm i everything. Can someone fix this?

**Comment by shootdot** [comment]
Please mention the error ?

**Comment by haydenwalker980** [comment]
Repl.it doesn't work with this (speaking from experience)
Try migrating to a VPS provider (like Linode).

**Comment by CipherHYT** [comment]
alright

**Comment by CipherHYT** [comment]
@shootdot Repl.it: Updating package configuration

--> npm install @utils/discordApi @utils/fileWalk @models/bots @routes/bots @utils/checkFields @structures/app.js @utils/getList.js @routes/api @routes/theme @bot/index @utils/passport.js @utils/createAuth.js @root/config.json
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@utils%2ffileWalk - Not found
npm ERR! 404 
npm ERR! 404  '@utils/fileWalk@latest' is not in the npm registry.
npm ERR! 404 Your package name is not valid, because 
npm ERR! 404  1. name can no longer contain capital letters
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2020-11-10T23_46_02_223Z-debug.log
exit status 1


Repl.it: Package operation failed.

**Comment by shootdot** [comment]
It is trying to install package which is not even there in npm and it is project files.
Make sure your package.json is correct and run ```npm install```

**Comment by Sank6** [comment]
That error means `module-alias` isn't working properly. Try installing it: `npm i module-alias`. If it still doesn't work, it's probably something to do with repl.it. You'll have to change the path in every `require` statement of every file to the relative path.
