### ISSUE TITLE
Bug: error page does not exist

### ISSUE THREAD

**Issue by ririko5834** [Sank6/Discord-Bot-List#326]
```js
    if (![bot.owners.primary].concat(bot.owners.additional).includes(req.user.id)) return res.redirect(`/error?e=owner`);
```
Error page (/error) does not exist. For example this code is in `/src/routes/bots/edit.js`

![image](https://user-images.githubusercontent.com/64729293/99180398-3ff20c00-2726-11eb-9a2c-21377d41ffb7.png)

**Comment by Sank6** [comment]
Changed to 403
