### ISSUE TITLE
Feature request: like system api

### ISSUE THREAD

**Issue by ririko5834** [Sank6/Discord-Bot-List#333]
Create api for like (vote) system. 
For example user who owns bot want to log all votes on his bot to support server.
I think that you should add atleast option to link Discord Webhook to bot in /edit page. That all votes for certain bot will be sent to webhook that provided bot owner.

**Comment by ririko5834** [comment]
Another feature request: Add that bot like count will be on /api/embed/:id widget.

**Comment by shootdot** [comment]
For the 1st request I have never made an API system before and never tried to do on it. May be Sank6 can make but I will try my best And fro 2nd Request that can be done easily I will Make a PR for it.

**Comment by ririko5834** [comment]
Also here is bug: (-200 minutes)
![image](https://user-images.githubusercontent.com/64729293/99251349-748cc300-280d-11eb-9f30-05bf96a4ce2b.png)

**Comment by shootdot** [comment]
Sank6 edited that...

**Comment by Sank6** [comment]
Yeah sorry. I don't know why it's like that. I'll have a look.

**Comment by Sank6** [comment]
Also it's quite hard to add an api right now because it doesn't store who likes the bot. It's just a tally of total likes.

**Comment by shootdot** [comment]
Yea true but we can make like if a user votes it stores it's username for temporary and sends to webhook ?

**Comment by shootdot** [comment]
Right now I'm searching how to make an API 😂😂

**Comment by Sank6** [comment]
I can make the API part, but it's the method of storing likes that's going to have to change. It's going to use up more database storage as well.

**Comment by wolfier74** [comment]
Seems to be good idea
