### ISSUE TITLE
Privacy Policy

### ISSUE THREAD

**Issue by brianseminara** [Sank6/Discord-Bot-List#334]
Is there a privacy policy. If yes where. If no, how do I make one?

**Comment by brianseminara** [comment]
also where is a good place to host this list?

**Comment by wolfier74** [comment]
> also where is a good place to host this list?

@brianseminara on VPS

**Comment by Sank6** [comment]
There is no privacy policy. There is a [license](https://github.com/Sank6/Discord-Bot-List/blob/master/LICENSE.md) for the code though. You can add a privacy policy to the website if you wish.
