### ISSUE TITLE
Bot Reviewer Role/Permissions

### ISSUE THREAD

**Issue by brianseminara** [Sank6/Discord-Bot-List#338]
There is no permission for the bot reviewer role in remove.js verify.js or marknsfw.js

So the bot reviewers can't review bots. Can you give me the piece of the code that is supposed to make it happen @Sank6

**Comment by Sank6** [comment]
Wait what? Are you sure you have the correct role ID in the config file?

**Comment by brianseminara** [comment]
> Wait what? Are you sure you have the correct role ID in the config file?

yea. 

**Role ID:** 771346671543648257
**Role ID Config:** 771346671543648257

the same! right? am I blind?

**Comment by Sank6** [comment]
Bot verifiers should have perms. Is there any error message or can they just not use the command?

**Comment by brianseminara** [comment]
They can't use the command.

**Comment by shootdot** [comment]
We are using Klasa module. In klasa module you define permissions in main file that is `src/bot/index.js`.
And in line number 6 you can see
```js
    .add(8, ({ guild, member }) => member.roles.cache.has(bot_verifier));
```
which is creating a new permission number  And then we are using that permission level in verify.js, remove.js.
In `src/bot/commands/Bots/verify.js` line number 12 you can see defining the permission for that command.

**Comment by brianseminara** [comment]
Still does not work @shootdot @Sank6

**Comment by brianseminara** [comment]
nvm. I found the bug. I got the not updated code. So I had to re-update it. Also how do I add normal commands to the main bot?

**Comment by Sank6** [comment]
@brianseminara add commands in `src/bot/commands`. Each folder is a category. Either create a new category or add to an existing one. Copy the command format from ping.js

**Comment by brianseminara** [comment]
Now whenever I verify a bot it won't give the user & the bot the Bot Dev role and the Bot role.

**Comment by Sank6** [comment]
Just checked, it seems to work fine.
