### ISSUE TITLE
/add Bug

### ISSUE THREAD

**Issue by ririko5834** [Sank6/Discord-Bot-List#339]
![image](https://user-images.githubusercontent.com/64729293/99518898-754e6200-2991-11eb-9f31-57ceae0f45b5.png)

Form fields are too big, maybe they should be smaller.

and i am getting unknown error when trying to add bot

**Comment by Sank6** [comment]
There should be a sidebar on desktop?

**Comment by ririko5834** [comment]
This is /add page not /edit.
I have sidebar on /edit

**Comment by ririko5834** [comment]
And why activity is not showing here now?
![image](https://user-images.githubusercontent.com/64729293/99521536-d1ff4c00-2994-11eb-82f9-7476656d3d51.png)

**Comment by ririko5834** [comment]
Why in activity first letters are uppercase? 
![image](https://user-images.githubusercontent.com/64729293/99527697-83a27b00-299d-11eb-9af9-d8ad4222db2f.png)
@Sank6 
and when activity is longer it is in 2 lines :/
![image](https://user-images.githubusercontent.com/64729293/99528506-aed99a00-299e-11eb-8119-043d14fcbdd5.png)

**Comment by ririko5834** [comment]
Another bug when user is not primary owner:
![image](https://user-images.githubusercontent.com/64729293/99534008-0aa82100-29a7-11eb-88f8-4818dc13572d.png)

**Comment by shootdot** [comment]
@ririko5834 1st thing the fields in add page are supposed to be like that.
2nd thing Other owner's are not supposed to edit the Links.

**Comment by ririko5834** [comment]
@shootdot 
OK
> 2nd thing Other owner's are not supposed to edit the Links.

Can you make that there will be displayed Only the primary owner can edit this.


Also
> Why in activity first letters are uppercase? I want to have it original not modified.
> ![image](https://user-images.githubusercontent.com/64729293/99527697-83a27b00-299d-11eb-9af9-d8ad4222db2f.png)

Also when i am trying to resubmit or add new bot i am getting this error and nothing is in console:
![image](https://user-images.githubusercontent.com/64729293/99537721-514c4a00-29ac-11eb-9c54-fcbc5d074e24.png)

**Comment by shootdot** [comment]
Goto submit.js file in src/routes/api/bots/submit.js and in line 42 before return put the command console.log(e) and send the error

**Comment by Sank6** [comment]
No all owners should be able to edit links. That's also a bug. I'll have a look tomorrow.

**Comment by shootdot** [comment]
Okay.

**Comment by ririko5834** [comment]
This is error in console @shootdot 
```TypeError: Cannot read property 'replace' of undefined
at module.exports (/src/utils/checkFields.js:79:29)
    at processTicksAndRejections (internal/process/task_queues.js:88:5)
at async /src/routes/api/bots/submit.js:39:17
```

**Comment by shootdot** [comment]
Send Full error this is just a part of it.

>

**Comment by ririko5834** [comment]
@shootdot  That's all i get in console.
I am getting this when i add Additional owner IDS and also when i leave this field blank when addding bot.

```

TypeError: Cannot read property 'replace' of undefined
at module.exports (/src/utils/checkFields.js:79:29)
    at processTicksAndRejections (internal/process/task_queues.js:88:5)
at async /src/routes/api/bots/submit.js:39:17
TypeError: Cannot read property 'replace' of undefined
at module.exports (/src/utils/checkFields.js:79:29)
    at processTicksAndRejections (internal/process/task_queues.js:88:5)
at async /src/routes/api/bots/submit.js:39:17
```

**Comment by shootdot** [comment]
@ririko5834 Try this code replace this code with src/utils/checkFields.js
[https://raw.githubusercontent.com/Sank6/Discord-Bot-List/5a2024c930539ec3e67eddad776f73152615832a/src/utils/checkFields.js](Here)

**Comment by Sank6** [comment]
The owners bug should be fixed in development branch. I'll push to master soon. Just checking some stuff.
