### ISSUE TITLE
Role Issues:

### ISSUE THREAD

**Issue by brianseminara** [Sank6/Discord-Bot-List#340]
Now whenever I verify a bot it won't give the user & the bot the Bot Dev role and the Bot role.

@Sank6 

I would have put this into the prev issue but it was closed.

**Comment by Sank6** [comment]
You can still comment on closed issues btw. Also, make sure the bot managing it is at the top of the roles list and it has admin perms.

**Comment by brianseminara** [comment]
It is at the tippy top of the list.

**Comment by brianseminara** [comment]
Still no. Also when I verify a bot the owners section just says <@undefined> (new line) <@undefined>

**Comment by brianseminara** [comment]
@Sank6

**Comment by shootdot** [comment]
@brianseminara Tell the users to reedit and submit there bots. It will be fine.

**Comment by Sank6** [comment]
Yeah but that still shouldn't be an issue. I'll have a look.

**Comment by brianseminara** [comment]
I think someone else fixed the issue in my code.

**Comment by brianseminara** [comment]
Also how do you make a bot always at the top.

**Comment by shootdot** [comment]
What do you mean ?

**Comment by brianseminara** [comment]
like to make a bot not move around on the page and just stay o the top of the main page?

**Comment by shootdot** [comment]
The botlist get shuffled always so that it does not show unfairness over other bots.

**Comment by brianseminara** [comment]
ok, and @Sank6 the issue with the bot owners is active, again. It says <@undefined> <@undefined>

**Comment by Sank6** [comment]
Actually it should be ordered by likes. I think.

**Comment by shootdot** [comment]
Yea it should be ordered by likes. @brianseminara Edit and resubmit your bot it fixes the issue.

**Comment by Sank6** [comment]
The owner issues should be fixed in the development branch. Test it if you want. I'll merge it with master soon.
