### ISSUE TITLE
Suggestion: Began Test System

### ISSUE THREAD

**Issue by brianseminara** [Sank6/Discord-Bot-List#343]
Someone will do a !test {@bot} and it will DM the owner of the bot saying that "{message.author.tag} began testing on your bot. Please wait for the verification action."

Do it in test.js file. Create

**Comment by ririko5834** [comment]
@brianseminara I made PR for this. You can try this code: https://github.com/Sank6/Discord-Bot-List/pull/344

**Comment by Sank6** [comment]
Why though?  It really doesn't take long to test a bot. That seems very unnecessary.

**Comment by ririko5834** [comment]
Yes, I think that it is not necessary too. But I made PR, brianseminara can copy my code if they want.

**Comment by Sank6** [comment]
Yeah sure, you can use the code but I won't add it to this repo because it's not really necessary.
