### ISSUE TITLE
Suggestion: Option to specify minimum lenght of bot description

### ISSUE THREAD

**Issue by ririko5834** [Sank6/Discord-Bot-List#345]
Add option to specify minimum lenght of bot's description in config.json. I want to limit it to minimum 300 characters, but i dont want to count html tags.

**Comment by ririko5834** [comment]
Please add this

**Comment by random-people-in-internet** [comment]
Yes please add this

**Comment by shootdot** [comment]
Long description or bot summary ?

**Comment by ririko5834** [comment]
Long description. I want to make that it must be 300 characters and longer.

**Comment by ririko5834** [comment]
@shootdot

**Comment by Sank6** [comment]
Added
