### ISSUE TITLE
Suggestions: Add Notes form field when adding bot

### ISSUE THREAD

**Issue by ririko5834** [Sank6/Discord-Bot-List#346]
Hi, can you please add Notes form field when adding bot? It will be useful when member wants to leave note to bot checkers about his bot.

And add that notes will be visible only to bot checkers and server admins

**Comment by shootdot** [comment]
Please don't open multiple Issues. Mention everything in one.

**Comment by shootdot** [comment]
If Sank6 Mentions it's good feature then I will try to add it

**Comment by Sank6** [comment]
This seems like a good idea but not right now. I think it might work if there was an admin panel, but even then, there really shouldn't need to be a note. The bot needs to be usable by everyone anyway, so wouldn't it be better to include that information in the long description? At least for now anyway, we could reopen this when there's an actual dashboard.

**Comment by ririko5834** [comment]
OK, but add that notes can be view using notes command. for example `!notes @bot_mention` will list notes for bot checkers that were added when adding bot. And add optional form field Notes when adding bots
