### ISSUE TITLE
Error: Line 1 of src/index.js

### ISSUE THREAD

**Issue by brianseminara** [Sank6/Discord-Bot-List#347]
We can't define `require("module-alias/register");` no npm package we can find. So everything is down. Do you know what's up?

**Comment by brianseminara** [comment]
@Sank6

**Comment by Sank6** [comment]
`npm i` should install it.

**Comment by brianseminara** [comment]
I use glitch! Do I just do npm i in the terminal?

**Comment by brianseminara** [comment]
@Sank6

**Comment by Sank6** [comment]
You can't host it on glitch. Have a look at the [setup guide](https://github.com/Sank6/Discord-Bot-List/wiki/FAQs#how-can-i-host-this).

**Comment by brianseminara** [comment]
I have to do it on glitch. How do I do it on glitch so it would work. It just randomly started last night.

**Comment by brianseminara** [comment]
@Sank6

**Comment by Sank6** [comment]
Read the setup guide. This isn't designed to be hosted on glitch. Any issues you have are probably related to glitch and not this. Glitch is designed for hosting mostly frontend sites with maybe some server-side, not a whole site like this.

**Comment by brianseminara** [comment]
i can't host it anywhere else! Please, any way to do it!!!!!

**Comment by brianseminara** [comment]
@Sank6

**Comment by Zaid-maker** [comment]
Man you don't have to do anything the modules will auto installs ones u import that project.

**Comment by Zaid-maker** [comment]
@Sank6 hosting is only problem on glitch now as u said it mostly for server-side thing other things are perfectly running on glitch hosting is only the problem.
