### ISSUE TITLE
Feature Request: Not logout on refresh

### ISSUE THREAD

**Issue by DyIster** [Sank6/Discord-Bot-List#350]
Whenever you refresh the page it logs you out which is annoying

**Comment by Sank6** [comment]
Shouldn't do? I just checked and it stays logged in for me. It logs you out, every time you restart the program. There's nothing you can do about that. The discord data is stored in sessions.

**Comment by DyIster** [comment]
It may be because I am running it on a local host as I am just playing around with it.

**Comment by DyIster** [comment]
Also, to bring up a bug, it appears on they remove command we are granting the developer role despite us actually denying the bot

**Comment by Sank6** [comment]
Fixed in development
