### ISSUE TITLE
auth issue 

### ISSUE THREAD

**Issue by RITIKDHAYAL-PHOENIX** [Sank6/Discord-Bot-List#351]
it showing this language how to change this language to english 
![image](https://user-images.githubusercontent.com/57560515/99868329-9f00c680-2be7-11eb-99ed-345e7ce28ed5.png)

**Comment by Sank6** [comment]
That is english lol.

**Comment by RITIKDHAYAL-PHOENIX** [comment]
2nd line...

**Comment by Sank6** [comment]
Still english. Not a bug.
