### ISSUE TITLE
im just running a trial and i wont copy this i swear but what should i fill in these

### ISSUE THREAD

**Issue by The-mortal-phoenix** [Sank6/Discord-Bot-List#352]
{
    "mongo_url": "i know this",
    "server": {
        "id": "",
        "invite": "",
        "mod_log_id": "",
        "like_log": "",
        "admin_user_ids": [],
        "role_ids": {
            "bot": "",
            "unverified": "",
            "verified": "",

            "bot_developer": "",
            "bot_verifier": ""

and for running it on local host 
    "web": {
        "domain_with_protocol": "whats this ",
        "port": 80,
        "ratelimit": 30,
        "recaptcha_v2": {
            "site_key": "know this",
            "secret_key": "this too "

can you help

**Comment by Sank6** [comment]
Read the wiki, you can use this if you want.
