### ISSUE TITLE
Bug/then why is this a thing

### ISSUE THREAD

**Issue by idk-pixel** [Sank6/Discord-Bot-List#354]
so i vote 1 bot, i should be able to vote the bot in 12 hours. which is good. but if i vote another i have to wait? dosent make any sense

**Comment by idk-pixel** [comment]
also i can still submit bots without captcha

**Comment by idk-pixel** [comment]
also only the primary owner can edit additional owners, didnt edit ?

**Comment by shootdot** [comment]
1. Yes if you vote 1 bot you won't be able to vote any bots for 12 hours that does makes sense.
2. Sank6 added captcha to prevent spam of message in discord when submitting/Editing bot.
3. Primary owner can only add additional owners. Additional owners don't have that permission to add more owners.

**Comment by idk-pixel** [comment]
@shootdot 1. no that dosent make sense
2. i dont have that prob anymore
3. i didnt edit the additional owners though

**Comment by Sank6** [comment]
It does make sense. You shouldn't be allowed to spam votes across multiple bots.
The others sound like bugs. I'll have a look.

**Comment by Sank6** [comment]
Just tested, those all work fine.
