### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by RITIKDHAYAL-PHOENIX** [Sank6/Discord-Bot-List#355]
Why we can't add support server or website link of our bot from bot add page. But we have add that from bot edit page.. should u make it so we can add links from add page

**Comment by shootdot** [comment]
Sank6 is currently doing some styling changes and he will add those fields with tags. So Please wait until he updates the repo.

**Comment by Sank6** [comment]
So I thought that on the bot submit page, only include the fields that were necessary for verification, like the description and summary. The bot edit page should have all the customisable features on it.
