### ISSUE TITLE
Add certification system

### ISSUE THREAD

**Issue by ririko5834** [Sank6/Discord-Bot-List#357]
Hi, can you please add certification system? 
And that certified bots will be showed first and will get Certified bot badge?

**Comment by shootdot** [comment]
@ririko5834 I have made it and asking permission to Sank6 if he/she thinks it is a good Idea I will open a PR
![image](https://user-images.githubusercontent.com/55920587/100049513-ee860300-2e30-11eb-82d9-a4ee12c5a6f9.png)
Preview ^^

**Comment by ririko5834** [comment]
Yes its good, please open PR.

**Comment by shootdot** [comment]
Sank6 Had been avoiding certified bots feature from before as I remember.
So if Sank6 thinks it's a good feature and accepts it I will surely open PR for it

**Comment by Sank6** [comment]
As I said, I don't think it's necessary. Obviously, you can add it yourself if you like.

**Comment by shootdot** [comment]
It's basically not that necessary to have a copy same like top.gg. If you want just try coding the certification 😀

**Comment by ririko5834** [comment]
@shootdot Please make PR and then  close it.

**Comment by ririko5834** [comment]
Also when bot tags will be added?

**Comment by Sank6** [comment]
It's on the development branch if you want to use it now, but I'll work on fixing bugs and pushing to master when I can.

**Comment by ririko5834** [comment]
OK, but please add also certified bots.

**Comment by Sank6** [comment]
> It's basically not that necessary to have a copy same like top.gg. If you want just try coding the certification 😀

**Comment by RITIKDHAYAL-PHOENIX** [comment]
@shootdot please make pr

**Comment by shootdot** [comment]
This is Sank6 repo and as sank6 told it isn't that necessary. So please stop pinging me. If Sank6 tells i will create a PR for sure.
