### ISSUE TITLE
VPN/Proxy Detection

### ISSUE THREAD

**Issue by shootdot** [Sank6/Discord-Bot-List#358]
Sank6 Please make VPN detection users are activating VPN and Voting bots continuously. 😫😪

**Comment by Sank6** [comment]
I thought they had to be signed in to a discord account to vote. And it has to be a different one each time right?

**Comment by shootdot** [comment]
Yea but I have seen one of the user continuously voting without having a break of 12 her!

**Comment by shootdot** [comment]
![image](https://user-images.githubusercontent.com/55920587/100182464-1e4b0e80-2ef6-11eb-8486-53b144eac6ee.png)

**Comment by Sank6** [comment]
I'll have a look. That isn't supposed to work.

**Comment by Sank6** [comment]
Just tested it. Doesn't seem to work. Are the votes being cast with the old bot command still?
