### ISSUE TITLE
ERRORS

### ISSUE THREAD

**Issue by alikemalkara61** [Sank6/Discord-Bot-List#359]
I am getting errors in this project. Can you specify a discord address so I can present the errors to you?

**Comment by shootdot** [comment]
@alikemalkara61 Please mention the errors.

**Comment by Sank6** [comment]
Yeah, put the error here.

**Comment by alikemalkara61** [comment]
![README md – iodized-nebula-puffin - Google Chrome 25 11 2020 10_27_41 (2)](https://user-images.githubusercontent.com/70637209/100195849-0466f700-2f09-11eb-96ab-47eb60314042.png)

**Comment by shootdot** [comment]
This project is not made for using in Glitch.

**Comment by shootdot** [comment]
Read wikis

**Comment by alikemalkara61** [comment]
So can you recommend another editor

**Comment by shootdot** [comment]
Get A VPS

**Comment by alikemalkara61** [comment]
ok thanks

**Comment by alikemalkara61** [comment]
Can you specify a discord address?

**Comment by shootdot** [comment]
wdym by discord address ?

>

**Comment by Sank6** [comment]
[Setup guide](https://github.com/Sank6/Discord-Bot-List/wiki/Setup-Information)
