### ISSUE TITLE
question

### ISSUE THREAD

**Issue by wqtalha** [Sank6/Discord-Bot-List#360]
What is the server count api and where to use it.
It's on the bot edit page, but I don't know what it does. Can you explain?

**Comment by shootdot** [comment]
@wqtalha Read this [https://github.com/Sank6/Discord-Bot-List/wiki/Server-Count-API](Server Count API)

**Comment by Sank6** [comment]
I plan to add these instructions to the server tab in the bot edit page, along with statistics, like a graph, but I haven't got round to it yet. For now, use the [wiki page](https://github.com/Sank6/Discord-Bot-List/wiki/Server-Count-API) like @shootdot said.
