### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by RITIKDHAYAL-PHOENIX** [Sank6/Discord-Bot-List#361]
Please add certified bots and some more categories pleaseeeeee.

**Comment by shootdot** [comment]
As Sank6 already told we are not copying exact of top.gg and it is not much required for a bot list it won't be added. If you want please code yourself.

**Comment by Sank6** [comment]
Also categories are entirely customisable.

**Comment by shootdot** [comment]
Lol
