### ISSUE TITLE
error

### ISSUE THREAD

**Issue by mongo001** [Sank6/Discord-Bot-List#365]
getting this error when starting it. 
![image](https://user-images.githubusercontent.com/75176904/100521393-681f4780-31c9-11eb-9d8b-458febb96d47.png)

**Comment by shootdot** [comment]
Looks like you didn't fill your config.json file well.

**Comment by mongo001** [comment]
its working before correctly today i just updates new updates than i getting this error
and my config file id well.

**Comment by shootdot** [comment]
Just delete config.json and recreate it

**Comment by mongo001** [comment]
i did it not working.

**Comment by Sank6** [comment]
What's at position 642 on your config file?

**Comment by mongo001** [comment]
how i know which is position 642.

**Comment by mongo001** [comment]
now the new error 
![image](https://user-images.githubusercontent.com/75176904/100535522-bf5fff00-323f-11eb-8b16-4de49f26117e.png)

**Comment by Sank6** [comment]
Make sure you have all the files.
