### ISSUE TITLE
Error: TokenError

### ISSUE THREAD

**Issue by xX-MoonWalker-Xx** [Sank6/Discord-Bot-List#367]
When I Authorize My Account(Login)
and i redirect to /api/callback
i get this error:

TokenError
    at Strategy.OAuth2Strategy.parseErrorResponse (C:\Users\Moon Walker\Desktop\Discord-Bot-List-master\Discord-Bot-List-master\node_modules\passport-oauth2\lib\strategy.js:358:12)
    at Strategy.OAuth2Strategy._createOAuthError (C:\Users\Moon Walker\Desktop\Discord-Bot-List-master\Discord-Bot-List-master\node_modules\passport-oauth2\lib\strategy.js:405:16)
    at C:\Users\Moon Walker\Desktop\Discord-Bot-List-master\Discord-Bot-List-master\node_modules\passport-oauth2\lib\strategy.js:175:45
    at C:\Users\Moon Walker\Desktop\Discord-Bot-List-master\Discord-Bot-List-master\node_modules\oauth\lib\oauth2.js:191:18
    at passBackControl (C:\Users\Moon Walker\Desktop\Discord-Bot-List-master\Discord-Bot-List-master\node_modules\oauth\lib\oauth2.js:132:9)
    at IncomingMessage.<anonymous> (C:\Users\Moon Walker\Desktop\Discord-Bot-List-master\Discord-Bot-List-master\node_modules\oauth\lib\oauth2.js:157:7)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)

help pls
Info:
windows: 8.1
node version:  v14.15.0
i installed all dependencies
And I filled config.json

**Comment by Sank6** [comment]
Check the domain in the [config file includes the protocol](https://github.com/Sank6/Discord-Bot-List/wiki/Setup-Information#config) and doesn't end with a `/`.

**Comment by xX-MoonWalker-Xx** [comment]
It's Correct 

`domain-with-protocol: http://localhost`
and port is default

**Comment by shootdot** [comment]
Is your port 80 ?

**Comment by xX-MoonWalker-Xx** [comment]
Yes

**Comment by xX-MoonWalker-Xx** [comment]
Help please
![screenshot](https://user-images.githubusercontent.com/72574462/100568599-e0c4f780-32e0-11eb-8b8e-60e7470832e2.jpg)

**Comment by shootdot** [comment]
Looks like you are running it on port 3001.
Change the port in config.json and goto your bot OAuth redirect URL and change to `http://localhost:3001/api/callback`

**Comment by shootdot** [comment]
Okay Try now.

**Comment by xX-MoonWalker-Xx** [comment]
![Uploading 2020-11-30_08-03_Error.jpg…]()

**Comment by shootdot** [comment]
Still same ? Have u changed in config.json file ?

**Comment by xX-MoonWalker-Xx** [comment]
yes

**Comment by shootdot** [comment]
Okay Restart the bot

**Comment by xX-MoonWalker-Xx** [comment]
I Restarted Before Testing again

**Comment by shootdot** [comment]
Oh

**Comment by xX-MoonWalker-Xx** [comment]
> Oh

What i can do ? :(

**Comment by shootdot** [comment]
Have you selected the redirect URL in OAUTH after editing ?
![image](https://user-images.githubusercontent.com/55920587/100569418-651a7900-32e7-11eb-93a7-cf6fe2ddd979.png)

**Comment by xX-MoonWalker-Xx** [comment]
yes

**Comment by shootdot** [comment]
Have you filled everything in config.json including client secret etc.

**Comment by xX-MoonWalker-Xx** [comment]
wait im checking

**Comment by shootdot** [comment]
Okay

**Comment by xX-MoonWalker-Xx** [comment]
Fixed ! :D

**Comment by shootdot** [comment]
Good You can close this issue.

**Comment by xX-MoonWalker-Xx** [comment]
Thank You :D

**Comment by shootdot** [comment]
Np
