### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by Mad-Ollie** [Sank6/Discord-Bot-List#370]
![Screenshot_20](https://user-images.githubusercontent.com/73799984/100572954-5b1f5880-329c-11eb-8d1a-00674582168f.png)
![Screenshot_21](https://user-images.githubusercontent.com/73799984/100572983-6d00fb80-329c-11eb-8b6e-cb6a34b1c693.png)

I have placed everything correctly and I get that when I log in

**Comment by shootdot** [comment]
In config.json file edit the area domain woth protocol to `https://mbotlistn.glitch.me`

**Comment by shootdot** [comment]
And read

**Comment by Zaid-maker** [comment]
yup that will fixes the issue
