### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by wqtalha** [Sank6/Discord-Bot-List#374]
How can I show the bots with the most votes on the homepage

**Comment by shootdot** [comment]
It's already shown.

**Comment by wqtalha** [comment]
No I just want to show the top voted bots on the homepage

**Comment by wqtalha** [comment]
I don't want to show bots with 0 voted
I want to show the top voted 5 bots

**Comment by shootdot** [comment]
Why do you want to do that ?

**Comment by wqtalha** [comment]
Because there are already bots in the search section, it will be better to have different things on the main page.

**Comment by wqtalha** [comment]
When this is the case with all botlist sites why not here

**Comment by Sank6** [comment]
The reason it's not already in this is so that all bots can have a similar chance if growing. However, you can change it in your code if you wish. Just add an if statement in `dynamic/index.pug`.
