### ISSUE TITLE
Note to admin on bot submit

### ISSUE THREAD

**Issue by ririko5834** [Sank6/Discord-Bot-List#375]
When will be admin panel and certified bots added?

**Comment by shootdot** [comment]
Certification will never been added and as for admin panel Idk what all should be there in admin panel. if I would come to know I can surely help Sank6 in making of admin panel.

**Comment by Sank6** [comment]
This isn't actively being maintained. There's only one other contributor other than me right now. I'll start on it when I can but even if I do, it'll take a while to be completed.

**Comment by shootdot** [comment]
@Sank6 could you mention what all things must be there in admin panel ?

**Comment by Sank6** [comment]
I was hoping to start with an admin api and then creating some frontend to verify/decline bots from the admin dashboard.

**Comment by shootdot** [comment]
Admin api for what ?

**Comment by ririko5834** [comment]
Its sad that you dont want to add certified bots. I hope that admin panel will be launched soon 😉 .

**Comment by Sank6** [comment]
API to verify and remove bots

**Comment by shootdot** [comment]
I'm not getting. Whats the use of API ?

**Comment by Sank6** [comment]
To actually update the bot details in the database.

**Comment by shootdot** [comment]
Oh. I will try to work on it.

**Comment by shootdot** [comment]
Okay So todo things.

- [ ] Admin API with auth token to edit any bot details on website.

- [ ] Approve or deny a bot through website.

@Sank6 Is this correct ?

**Comment by ririko5834** [comment]
@shootdot thanks for making admin panel, can you please also make PR for this https://github.com/Sank6/Discord-Bot-List/issues/345?

**Comment by shootdot** [comment]
@Sank6 @ririko5834 
Sneak Peak. I don't know well CSS so yeah if Sank6 you don't like it please change it I have no Idea how do I do styling more.
![image](https://user-images.githubusercontent.com/55920587/101275759-ac11de00-37c1-11eb-9c4b-6626fa3fc30b.png)

**Comment by Sank6** [comment]
Yeah I can change some of it to suit the website theme a little more. Thanks for making the PR though. It looks quite nice already tbh.

**Comment by Sank6** [comment]
Also you don't need an admin auth token. I was thinking bot verifiers and admins get an additional page on the dropdown menu under their name in the navbar to go to the dashboard. 
This dashboard should just not be accessible for anyone who isn't an admin or bot verifier - return 403.

**Comment by shootdot** [comment]
Okay Sank6 if you can I have one doubt about the API. Basically why do we need an API. Is the API needed to edit only bot details or something else also ?

**Comment by shootdot** [comment]
Yeah I made dashboard to admins only yet. If other users try going to admin page it Shows 403 Forbidden. I will make it for bot verifiers also.

**Comment by shootdot** [comment]
And if there is no auth token for Admin API anyone can use it right ?

**Comment by Sank6** [comment]
Nono. I mean API so the admin panel actually works. So for example, when you click the decline button on the frontend, you need to send a request to the backend. This is the API request and you check in the backend that the user is a bot reviewer and then decline the bot.

**Comment by shootdot** [comment]
Oh Got it.

**Comment by ririko5834** [comment]
The admin panel looks great. Also when it will be added please reopen this: https://github.com/Sank6/Discord-Bot-List/issues/346

**Comment by Sank6** [comment]
Yeah, once the admin panel reaches the master branch, I'll reopen it. Ping me if I forget.

**Comment by ririko5834** [comment]
@Sank6 Please reopen it

**Comment by Sank6** [comment]
Added: 867a675e2af97f2e9f52cf8515ad5e904bfe6cc6
