### ISSUE TITLE
erorrr when i do npm i 

### ISSUE THREAD

**Issue by WildThunder4764** [Sank6/Discord-Bot-List#376]
this error has never occurred on previous node projects i kinda understand what it is but dunno how to solve it here is the error
`C:\Users\Nandu\OneDrive\Pictures\blot-list>npm i
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: silicobots.co@3.0.0
npm ERR! Found: discord.js@12.5.1
npm ERR! node_modules/discord.js
npm ERR!   discord.js@"^12.2.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer discord.js@"github:discordjs/discord.js#master" from klasa@0.5.0
npm ERR! node_modules/klasa
npm ERR!   klasa@"^0.5.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\Nandu\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Nandu\AppData\Local\npm-cache\_logs\2020-12-05T11_14_48_118Z-debug.log`

I think this has got do with some other dependency installing discord.js 12 so I searched node modules but could not find anything so can anyone help

**Comment by WildThunder4764** [comment]
if you want debug.log here it is `0 verbose cli [
0 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
0 verbose cli   'C:\\Users\\Nandu\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
0 verbose cli   'i'
0 verbose cli ]
1 info using npm@7.0.15
2 info using node@v15.3.0
3 timing config:load:defaults Completed in 2ms
4 timing config:load:file:C:\Users\Nandu\AppData\Roaming\npm\node_modules\npm\npmrc Completed in 4ms
5 timing config:load:builtin Completed in 4ms
6 timing config:load:cli Completed in 2ms
7 timing config:load:env Completed in 1ms
8 timing config:load:file:C:\Users\Nandu\OneDrive\Pictures\blot-list\.npmrc Completed in 0ms
9 timing config:load:project Completed in 3ms
10 timing config:load:file:C:\Users\Nandu\.npmrc Completed in 1ms
11 timing config:load:user Completed in 1ms
12 timing config:load:file:C:\Users\Nandu\AppData\Roaming\npm\etc\npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:cafile Completed in 0ms
15 timing config:load:validate Completed in 1ms
16 timing config:load:setUserAgent Completed in 0ms
17 timing config:load:setEnvs Completed in 3ms
18 timing config:load Completed in 18ms
19 verbose npm-session f61f0bcee577b695
20 timing npm:load Completed in 44ms
21 timing arborist:ctor Completed in 2ms
22 timing idealTree:init Completed in 103ms
23 timing idealTree:userRequests Completed in 1ms
24 silly idealTree buildDeps
25 silly fetch manifest canvas@^2.6.1
26 http fetch GET 304 https://registry.npmjs.org/canvas 117125ms attempt #2 (from cache)
27 silly fetch manifest canvas-constructor@^4.1.0
28 http fetch GET 304 https://registry.npmjs.org/canvas-constructor 429ms (from cache)
29 silly fetch manifest cookie-parser@^1.4.4
30 http fetch GET 304 https://registry.npmjs.org/cookie-parser 392ms (from cache)
31 silly fetch manifest discord.js@^12.2.0
32 http fetch GET 304 https://registry.npmjs.org/discord.js 482ms (from cache)
33 silly fetch manifest ejs@^3.1.5
34 http fetch GET 304 https://registry.npmjs.org/ejs 401ms (from cache)
35 silly fetch manifest express@^4.16.3
36 http fetch GET 304 https://registry.npmjs.org/express 495ms (from cache)
37 silly fetch manifest express-session@^1.17.1
38 http fetch GET 304 https://registry.npmjs.org/express-session 428ms (from cache)
39 silly fetch manifest is-html@^2.0.0
40 http fetch GET 304 https://registry.npmjs.org/is-html 431ms (from cache)
41 silly fetch manifest is-url@1.2.4
42 http fetch GET 304 https://registry.npmjs.org/is-url 400ms (from cache)
43 silly fetch manifest klasa@^0.5.0
44 http fetch GET 304 https://registry.npmjs.org/klasa 408ms (from cache)
45 timing idealTree Completed in 121196ms
46 timing command:install Completed in 121205ms
47 verbose stack Error: unable to resolve dependency tree
47 verbose stack     at Arborist.[failPeerConflict] (C:\Users\Nandu\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:1045:25)
47 verbose stack     at Arborist.[loadPeerSet] (C:\Users\Nandu\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:1025:36)
47 verbose stack     at async Arborist.[buildDepStep] (C:\Users\Nandu\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:781:11)
47 verbose stack     at async Arborist.buildIdealTree (C:\Users\Nandu\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:209:7)
47 verbose stack     at async Promise.all (index 1)
47 verbose stack     at async Arborist.reify (C:\Users\Nandu\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\reify.js:122:5)
47 verbose stack     at async install (C:\Users\Nandu\AppData\Roaming\npm\node_modules\npm\lib\install.js:39:3)
48 verbose cwd C:\Users\Nandu\OneDrive\Pictures\blot-list
49 verbose Windows_NT 10.0.18363
50 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Nandu\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "i"
51 verbose node v15.3.0
52 verbose npm  v7.0.15
53 error code ERESOLVE
54 error ERESOLVE unable to resolve dependency tree
55 error
56 error While resolving: [1msilicobots.co[22m@[1m3.0.0[22m
56 error Found: [1mdiscord.js[22m@[1m12.5.1[22m[2m[22m
56 error [2mnode_modules/discord.js[22m
56 error   [1mdiscord.js[22m@"[1m^12.2.0[22m" from the root project
56 error
56 error Could not resolve dependency:
56 error [35mpeer[39m [1mdiscord.js[22m@"[1mgithub:discordjs/discord.js#master[22m" from [1mklasa[22m@[1m0.5.0[22m[2m[22m
56 error [2mnode_modules/klasa[22m
56 error   [1mklasa[22m@"[1m^0.5.0[22m" from the root project
56 error
56 error Fix the upstream dependency conflict, or retry
56 error this command with --force, or --legacy-peer-deps
56 error to accept an incorrect (and potentially broken) dependency resolution.
56 error
56 error See C:\Users\Nandu\AppData\Local\npm-cache\eresolve-report.txt for a full report.
57 verbose exit 1
`

**Comment by shootdot** [comment]
Do `npm i --force`

**Comment by shootdot** [comment]
If still it's not working check which node version u have. Node version should be 12 or above. do `node -v` to get node version

**Comment by WildThunder4764** [comment]
> If still it's not working check which node version u have. Node version should be 12 or above. do `node -v` to get node version

C:\Users\Nandu\OneDrive\Pictures\blot-list>node -v
v15.3.0

**Comment by WildThunder4764** [comment]
> Do `npm i --force`
C:\Users\Nandu\OneDrive\Pictures\blot-list>npm i --force
npm WARN using --force Recommended protections disabled.
npm WARN ERESOLVE overriding peer dependency
npm WARN Found: discord.js@12.5.1
npm WARN node_modules/discord.js
npm WARN   discord.js@"^12.5.1" from the root project
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer discord.js@"github:discordjs/discord.js#master" from klasa@0.5.0
npm WARN node_modules/klasa
npm WARN   klasa@"^0.5.0" from the root project
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! code 1
npm ERR! path C:\Users\Nandu\OneDrive\Pictures\blot-list\node_modules\canvas
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node-pre-gyp install --fallback-to-build
npm ERR! Warning: Missing input files:
npm ERR! C:\GTK\bin\libpangocairo-1.0-0.dll
npm ERR! C:\GTK\bin\libcairo-2.dll
npm ERR! C:\GTK\bin\libgmodule-2.0-0.dll
npm ERR! C:\GTK\bin\libgthread-2.0-0.dll
npm ERR! C:\GTK\bin\libintl-8.dll
npm ERR! C:\GTK\bin\libgobject-2.0-0.dll
npm ERR! C:\GTK\bin\libfontconfig-1.dll
npm ERR! C:\GTK\bin\libglib-2.0-0.dll
npm ERR! C:\GTK\bin\libexpat-1.dll
npm ERR! C:\GTK\bin\zlib1.dll
npm ERR! C:\GTK\bin\libpangoft2-1.0-0.dll
npm ERR! C:\GTK\bin\libpng14-14.dll
npm ERR! C:\GTK\bin\libpangowin32-1.0-0.dll
npm ERR! C:\GTK\bin\libpango-1.0-0.dll
npm ERR! C:\GTK\bin\libfreetype-6.dll
npm ERR! Building the projects in this solution one at a time. To enable parallel build, please add the "-m" switch.
npm ERR!   Backend.cc
npm ERR! C:\Users\Nandu\OneDrive\Pictures\blot-list\node_modules\canvas\src\backend\Backend.h(3,10): fatal error C1083: Cannot open include file: 'cairo.h': No such file or directory [C:\Users\Nandu\OneDrive\Pictures\blot-list\node_modules\canvas\build\canvas.vcxproj]
npm ERR! Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\Nandu\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\Users\Nandu\OneDrive\Pictures\blot-list\node_modules\canvas\build\Release\canvas.node --module_name=canvas --module_path=C:\Users\Nandu\OneDrive\Pictures\blot-list\node_modules\canvas\build\Release --napi_version=7 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v88' (1)
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@0.11.0
npm ERR! node-pre-gyp info using node@15.3.0 | win32 | ia32
npm ERR! node-pre-gyp WARN Using request for node-pre-gyp https download
npm ERR! node-pre-gyp info check checked for "C:\Users\Nandu\OneDrive\Pictures\blot-list\node_modules\canvas\build\Release\canvas.node" (not found)
npm ERR! node-pre-gyp http GET https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.6.1/canvas-v2.6.1-node-v88-win32-unknown-ia32.tar.gz
npm ERR! node-pre-gyp http 404 https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.6.1/canvas-v2.6.1-node-v88-win32-unknown-ia32.tar.gz
npm ERR! node-pre-gyp WARN Tried to download(404): https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.6.1/canvas-v2.6.1-node-v88-win32-unknown-ia32.tar.gz
npm ERR! node-pre-gyp WARN Pre-built binaries not found for canvas@2.6.1 and node@15.3.0 (node-v88 ABI, unknown) (falling back to source compile with node-gyp)
npm ERR! node-pre-gyp http 404 status code downloading tarball https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.6.1/canvas-v2.6.1-node-v88-win32-unknown-ia32.tar.gz
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@15.3.0 | win32 | ia32
npm ERR! gyp info ok
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@15.3.0 | win32 | ia32
npm ERR! gyp info find Python using Python version 3.9.0 found at "C:\Program Files\Python39-32\python.exe"
npm ERR! gyp info find VS using VS2019 (16.8.30717.126) found at:
npm ERR! gyp info find VS "C:\Program Files\Microsoft Visual Studio\2019\BuildTools"
npm ERR! gyp info find VS run with --verbose for detailed information
npm ERR! gyp info spawn C:\Program Files\Python39-32\python.exe
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   'C:\\Users\\Nandu\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'msvs',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\Nandu\\OneDrive\\Pictures\\blot-list\\node_modules\\canvas\\build\\config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\Nandu\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\Nandu\\AppData\\Local\\node-gyp\\Cache\\15.3.0\\include\\node\\common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=C:\\Users\\Nandu\\AppData\\Local\\node-gyp\\Cache\\15.3.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\Nandu\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\Nandu\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\15.3.0\\\\<(target_arch)\\\\node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\Nandu\\OneDrive\\Pictures\\blot-list\\node_modules\\canvas',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'C:\\Users\\Nandu\\OneDrive\\Pictures\\blot-list\\node_modules\\canvas\\build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info ok
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@15.3.0 | win32 | ia32
npm ERR! gyp info spawn C:\Program Files\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\MSBuild.exe
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   'build/binding.sln',
npm ERR! gyp info spawn args   '/clp:Verbosity=minimal',
npm ERR! gyp info spawn args   '/nologo',
npm ERR! gyp info spawn args   '/p:Configuration=Release;Platform=Win32'
npm ERR! gyp info spawn args ]
npm ERR! gyp ERR! build error
npm ERR! gyp ERR! stack Error: `C:\Program Files\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onExit (C:\Users\Nandu\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:376:20)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:277:12)
npm ERR! gyp ERR! System Windows_NT 10.0.18363
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Nandu\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=C:\\Users\\Nandu\\OneDrive\\Pictures\\blot-list\\node_modules\\canvas\\build\\Release\\canvas.node" "--module_name=canvas" "--module_path=C:\\Users\\Nandu\\OneDrive\\Pictures\\blot-list\\node_modules\\canvas\\build\\Release" "--napi_version=7" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v88"
npm ERR! gyp ERR! cwd C:\Users\Nandu\OneDrive\Pictures\blot-list\node_modules\canvas
npm ERR! gyp ERR! node -v v15.3.0
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok
npm ERR! node-pre-gyp ERR! build error
npm ERR! node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\Nandu\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\Users\Nandu\OneDrive\Pictures\blot-list\node_modules\canvas\build\Release\canvas.node --module_name=canvas --module_path=C:\Users\Nandu\OneDrive\Pictures\blot-list\node_modules\canvas\build\Release --napi_version=7 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v88' (1)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\Nandu\OneDrive\Pictures\blot-list\node_modules\canvas\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:376:20)
npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1055:16)
npm ERR! node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:288:5)
npm ERR! node-pre-gyp ERR! System Windows_NT 10.0.18363
npm ERR! node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Nandu\\OneDrive\\Pictures\\blot-list\\node_modules\\canvas\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
npm ERR! node-pre-gyp ERR! cwd C:\Users\Nandu\OneDrive\Pictures\blot-list\node_modules\canvas
npm ERR! node-pre-gyp ERR! node -v v15.3.0
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v0.11.0
npm ERR! node-pre-gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Nandu\AppData\Local\npm-cache\_logs\2020-12-05T11_42_18_201Z-debug.log

**Comment by shootdot** [comment]
Try using node version 12.

**Comment by WildThunder4764** [comment]
okay

**Comment by Sank6** [comment]
Yeah, I use Node 14 (LTS). The current version is usually less stable.

**Comment by shootdot** [comment]
@WildThunder4764 Is this issue fixed ? If fixed please close this issue.
