### ISSUE TITLE
I am getting issues with mongodb url is there anyway to fix it please tell or any vids i can watch

### ISSUE THREAD

**Issue by chitrakshbotwala** [Sank6/Discord-Bot-List#379]

**Comment by shootdot** [comment]
Please mention the error

**Comment by chitrakshbotwala** [comment]
> Please mention the error

I actually dont know how to get a mongodb url so please tell me how to get it

**Comment by shootdot** [comment]
First you need to install mongodb
Then default mongo URL is `mongodb://127.0.0.1:27017/(type whatever u want here)`
Example `mongodb://127.0.0.1:27017/DBL`

**Comment by Sank6** [comment]
Or use mongodb atlas. Check the [setup page](https://github.com/Sank6/Discord-Bot-List/wiki/Setup-Information)

**Comment by chitrakshbotwala** [comment]
Ohk thanks for the help !
