### ISSUE TITLE
Cannot read property 'logo' of null

### ISSUE THREAD

**Issue by ElemelkyaDima** [Sank6/Discord-Bot-List#381]
![image](https://user-images.githubusercontent.com/71642531/101366463-d57e4880-3859-11eb-890c-493722227ce4.png)

**Comment by Sank6** [comment]
The bot you're trying to verify hasn't actually been added to the database. Have you completed the add bot form for it?

**Comment by shootdot** [comment]
The bot you want to verify is not in database first add it to database

**Comment by ElemelkyaDima** [comment]
Sorry
