### ISSUE TITLE
additional owner error

### ISSUE THREAD

**Issue by idk-pixel** [Sank6/Discord-Bot-List#383]
if you are editing a bot as an additional owner, even if you dont edit the owners, it gives an error ( Only the primary owner can edit additional owners )

**Comment by shootdot** [comment]
Yeah.

**Comment by shootdot** [comment]
https://github.com/Sank6/Discord-Bot-List/issues/369#issuecomment-738117254

**Comment by shootdot** [comment]
@idk-pixel Is your issue fixed ? If fixed you may close this issue 😀
