### ISSUE TITLE
Glitch HELP

### ISSUE THREAD

**Issue by kjfkjdngsfkgm** [Sank6/Discord-Bot-List#384]
![image](https://user-images.githubusercontent.com/75730533/101628233-8fc7a880-3a30-11eb-9cc7-296d47cfbe16.png)
![image](https://user-images.githubusercontent.com/75730533/101628354-bb4a9300-3a30-11eb-97c2-94f8696e50c8.png)

HELP ME MY DISCORD R2BOW#8992 or reply pls

**Comment by artificialai223** [comment]
Its not supposed to be hosted on Glitch as said in the readme

**Comment by Sank6** [comment]
https://github.com/Sank6/Discord-Bot-List/wiki/FAQs#how-can-i-host-this
