### ISSUE TITLE
Offline bug

### ISSUE THREAD

**Issue by artificialai223** [Sank6/Discord-Bot-List#385]
![image](https://i.imgur.com/zIOJWJF.png)
![image](https://i.imgur.com/oZH8LDl.png)
![image](https://i.imgur.com/TSoBrUO.png)

Every bot is offline on the list
however every bot is online

https://enderlist.xyz/

**Comment by Derpy-py** [comment]
Hi! The online feature works perfectly for me. Make sure the bots added have the prescence intent enabled.

**Comment by shootdot** [comment]
Yeah. Online and offline status works perfectly. Enable Presence intent for your bot.

**Comment by Zaid-maker** [comment]
Ok

**Comment by artificialai223** [comment]
Every bot has it enabled and so does the Oauth bot

**Comment by Sank6** [comment]
Just tested. It seems to work fine for me. Is it something to do with Discord perms?
