### ISSUE TITLE
How to make login via discord?

### ISSUE THREAD

**Issue by 1sh0tgg** [Sank6/Discord-Bot-List#386]
![image](https://user-images.githubusercontent.com/70522999/101809339-3f883d80-3b39-11eb-8855-83b5c65169fe.png)

**Comment by 1sh0tgg** [comment]
Infinite authorization with discord. I click log in and I'm thrown back to log in

**Comment by 1sh0tgg** [comment]
![Uploading image.png…]()

**Comment by shootdot** [comment]
What do you mean ?

**Comment by 1sh0tgg** [comment]
I mean, when I click log in, it throws me back to authorization

**Comment by shootdot** [comment]
Yeah you are supposed to get redirect to the authorization page and you need to authorize then you will automatically get logged in to via Discord.

**Comment by 1sh0tgg** [comment]
I click on the authorize button and it sends me back to discord authorization

**Comment by 1sh0tgg** [comment]
https://discord.com/api/oauth2/authorize?client_id=786628075617517629&response_type=code&scope=identify&redirect_uri=http://localhost:666/api/callback
