### ISSUE TITLE
Loggin error

### ISSUE THREAD

**Issue by VortexDev20** [Sank6/Discord-Bot-List#393]
const { Router } = require("express");
const passport = require('passport');
const route = Router();

 route.get("/", passport.authenticate('discord', { scope: ["identify","email"], prompt: "consent" }), function(req, res) {});

module.exports = route;

It need to redirect me to : https://discord.com/api/oauth2/authorize?client_id=787725677112983552&redirect_uri=http%3A%2F%2Flocalhost%3A80&response_type=code&scope=guilds%20email

But it redirect me to : https://discord.com/oauth2/authorize?prompt=consent&response_type=code&redirect_uri=http%3A%2F%2Flocalhost%3A80%2Fapi%2Fcallback&scope=identify&client_id=787725677112983552

**Comment by shootdot** [comment]
You have edited the file.

**Comment by shootdot** [comment]
If you want to edit the scopes u need to edit in login.js in routers and in `/src/utils/passport.js` You need to edit `var scopes = ['identify', 'email'];`

**Comment by Sank6** [comment]
I'm confused. Why do you want guilds and email?
