### ISSUE TITLE
reCaptcha

### ISSUE THREAD

**Issue by VortexDev20** [Sank6/Discord-Bot-List#395]
whene i remove this line in the add file : const { web: {recaptcha_v2: {site_key}}, bot_options: {bot_tags} } = require("@root/config.json");
to remove the captcha 

its dont work :(

How to remove the captcha pls ?

**Comment by Sank6** [comment]
Why do you want to remove the recaptcha? You'll have to remove it from the backend and the frontend

**Comment by shootdot** [comment]
If you wabt to remove recaptcha u need to remove ot from utils/checkfield.js
