### ISSUE TITLE
Name

### ISSUE THREAD

**Issue by VortexDev20** [Sank6/Discord-Bot-List#396]
Hi everyone this is my third question , how to change the Name of the text 
![image](https://user-images.githubusercontent.com/72358638/102224812-b41afd80-3ee6-11eb-9fac-091d5f3c5783.png)
Because i wanna change them as another language ( french )

**Comment by Sank6** [comment]
https://github.com/Sank6/Discord-Bot-List/blob/master/src/dynamic/includes/nav.pug
