### ISSUE TITLE
Submit Boutton

### ISSUE THREAD

**Issue by VortexDev20** [Sank6/Discord-Bot-List#399]
Hi so resubmit boutton is not working , whene i click it there is not error in the console

**Comment by shootdot** [comment]
Reaubmit button works well check for any error in browser console. `CTRL + SHIFT + J` or `F12` in browser.

**Comment by AibersonDev** [comment]
Hello, I have the same problem, I checked the console and I get the following:
```
Uncaught TypeError: Cannot read property 'value' of null
    at submit (form.js:26)
    at HTMLAnchorElement.onclick ((index):1)
```
The line has the following code:
```js
if (!document.getElementById(v).value) {
```
![Sin título](https://user-images.githubusercontent.com/69764582/102674089-15eb9980-416b-11eb-8dd7-6178848ad766.png)
