### ISSUE TITLE
reCaptcha

### ISSUE THREAD

**Issue by VortexDev20** [Sank6/Discord-Bot-List#400]
![image](https://user-images.githubusercontent.com/72358638/102402325-e7dc4d00-3fe4-11eb-836d-2d18aea9359c.png)
ERROR : site_key not working

My website is : localhost:80 , so how to link my site key to my website hosted in my pc ?

**Comment by Sank6** [comment]
https://github.com/Sank6/Discord-Bot-List/wiki/Setup-Information#config
