### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by ririko5834** [Sank6/Discord-Bot-List#403]
Please add .env config support. 
Can you add support for .env and config.json at time that when value is not in config.json it will be fetched from .env using process.env.value ?

**Comment by shootdot** [comment]
But why when you have config.json ?

**Comment by ririko5834** [comment]
Because .env is better for me. Also please check https://github.com/Sank6/Discord-Bot-List/issues/345

**Comment by Sank6** [comment]
I used to use .env but its confusing because you can't have JSON-like structure. I don't think I'll be adding it back again, sorry.

**Comment by ririko5834** [comment]
@ririko5834 Can you tell me how to add it just for my botlist? What should i use.
you can use json in .env
for example in .env: `ARRAY=["test", "test2"]`
and then use `JSON.parse(process.env.ARRAY)`

**Comment by Sank6** [comment]
Yes I know, but you can just use a config file at that point. What's wrong with it?
