### ISSUE TITLE
Image Change

### ISSUE THREAD

**Issue by legofan10** [Sank6/Discord-Bot-List#404]
Hello, how do I change an image on the file. Like I want to change the logo on logo.png. How do I change it??

**Comment by Sank6** [comment]
Change the file. It'll be in `public/assets/` probably.

**Comment by legofan10** [comment]
> Change the file. It'll be in `public/assets/` probably.

What do you mean to change the file

**Comment by Sank6** [comment]
Replace it with a logo you want?

**Comment by legofan10** [comment]
> Replace it with a logo you want?

how do you change it though
