### ISSUE TITLE
Suggestion: Add option to add custom urls for bots (using command) and add Featured bots that will be showed first on the botlist 

### ISSUE THREAD

**Issue by wolfier74** [Sank6/Discord-Bot-List#408]
Read title

**Comment by zennv** [comment]
> and add Featured bots that will be showed first on the botlist

Already answered: #357

**Comment by Sank6** [comment]
As for custom URLs, I don't think I'll add it. It makes more sense to use a URL shortner.

**Comment by wolfier74** [comment]
But when i will use url shorter, it will be not same domain
I want to use https://mydomain.example/bots/ custom-vanity or botid

**Comment by Sank6** [comment]
Yeah but the only advantage to a vanity url is that it's easy to type out manually. It's easier if the URL is shorter right?

**Comment by shootdot** [comment]
@Sank6 Vanity URL are easier to make. I made for my botlist. You just need to check if the parameter is integer if no find the bot from mongodb using the vanity url.

**Comment by shootdot** [comment]
If you think it's good Idea I can surely open PR for it

**Comment by Sank6** [comment]
But that defeats the whole point of it. It should be customisable and short. For example, Microsoft use the domain `aka.ms` when they want you to go to a page on their website thats easy to type out. So they might say `aka.ms/remoteconnect` which then redirects you to a long url. Vanity URLs don't really have much use on the original domain but if people want it, then make a pr.

**Comment by shootdot** [comment]
@Sank6 But we can make like this rght ?
`https://domain.com/bots/<whateverheywanthere>`
