### ISSUE TITLE
Bug: Failing ReCaptcha causes page reload

### ISSUE THREAD

**Issue by TheCuteFoxxy** [Sank6/Discord-Bot-List#409]
If you fail the ReCaptcha, it causes the page to reload entirely. No error is provided in the console or to the user.

Unsure if this is intended or not, if there is a part of ReCaptcha code I can edit to change this to at least give the user an error please let me know.

**Comment by Sank6** [comment]
Sounds like a bug. I'll have a look.

**Comment by Sank6** [comment]
Just checked. It works fine for me. The error appears in the top right in a Noty notification
