### ISSUE TITLE
Callback

### ISSUE THREAD

**Issue by LNTheLord** [Sank6/Discord-Bot-List#413]
domain with protocol: https://ice-bots.tk/api/callback but error 
![Screenshot_20201220-210802](https://user-images.githubusercontent.com/75278120/102720791-80d1d780-4307-11eb-9308-d9199e849c2a.png)

**Comment by shootdot** [comment]
https://github.com/Sank6/Discord-Bot-List/wiki/FAQs#invalid-oauth2-redirect-uri
