### ISSUE TITLE
WebSite - Sugesstion

### ISSUE THREAD

**Issue by VortexDev20** [Sank6/Discord-Bot-List#415]
Add catégories : Top Liked , Certified , etc ..........

**Comment by shootdot** [comment]
@VortexDev20 
1. Please open 1 issue and put your requests there. Don't open multiple issues.
2. As Sank6 told earlier he/she will not be adding categories.

**Comment by Sank6** [comment]
Yeah it's already sorted by top liked which is good enough. Since many of you want bots to be separated to some degree, hoisting makes sense: #401. However certified is unnecessary imo.
