### ISSUE TITLE
Server Count Api

### ISSUE THREAD

**Issue by LNTheLord** [Sank6/Discord-Bot-List#418]
https://ice-bots.tk/api/auth/stats/790221233366499358/  but page not found

**Comment by shootdot** [comment]
It will obviously show page not found. you can only send request to that URL you can't view that page.

**Comment by LNTheLord** [comment]
How do I write the server count in the description

**Comment by Zaid-maker** [comment]
😂😂😂😂😂😂😂😂

**Comment by Sank6** [comment]
The server count is shown in the bot page but not the description. I guess the only way to include your server count in the bot description is serve a dynamic image from your server which shows the server count and then have this image in your bot description.

**Comment by LNTheLord** [comment]
> The server count is shown in the bot page but not the description. I guess the only way to include your server count in the bot description is serve a dynamic image from your server which shows the server count and then have this image in your bot description.

So how can I write to the bot page

**Comment by Sank6** [comment]
What?

**Comment by LNTheLord** [comment]
How and where can I show the server count

**Comment by Sank6** [comment]
https://github.com/Sank6/Discord-Bot-List/wiki/Bot-developer-APIs

**Comment by LNTheLord** [comment]
How will it be displayed on the bot page after sending the data to that link?

**Comment by Sank6** [comment]
Try it. It shows up next to the bot's username.

**Comment by LNTheLord** [comment]
So where do I throw the api code? Is it to the bot's main file?

**Comment by Sank6** [comment]
yep

**Comment by LNTheLord** [comment]
https://ice-bots.tk/bots/789904157892280320 dont show

**Comment by Sank6** [comment]
Any errors when you sent the stats?

**Comment by LNTheLord** [comment]
When I start the bot it sends the site codes to the logs
