### ISSUE TITLE
Add Bot Submit Button

### ISSUE THREAD

**Issue by server-git** [Sank6/Discord-Bot-List#419]
After i add all the info in the add bot and then when i press submit nothing happens
in console is no error 
*im on localhost

**Comment by server-git** [comment]
what?

**Comment by server-git** [comment]
the link dosent work

**Comment by Sank6** [comment]
Check your [config](https://github.com/Sank6/Discord-Bot-List/wiki/Setup-Information#config).

**Comment by server-git** [comment]
its all good but dont work

**Comment by server-git** [comment]
nvm fixed
