### ISSUE TITLE
Statuspage.io Embed

### ISSUE THREAD

**Issue by legofan10** [Sank6/Discord-Bot-List#423]
Where would I put my bot list's statuspage.io embed code?

**Comment by shootdot** [comment]
On which page are you trying to put ?

**Comment by legofan10** [comment]
> On which page are you trying to put ?

the main page

**Comment by Sank6** [comment]
Wherever you want. The files are in `src/dynamic`

**Comment by legofan10** [comment]
> Wherever you want. The files are in `src/dynamic`

what file will it be on?

**Comment by Sank6** [comment]
Up to you.

**Comment by legofan10** [comment]
> Up to you.

no, like what file is the main page on

**Comment by Sank6** [comment]
index.pug

**Comment by legofan10** [comment]
> index.pug

thx
