### ISSUE TITLE
SUGGESTION: What about Server List inside the bot list or sperate one?

### ISSUE THREAD

**Issue by Zaid-maker** [Sank6/Discord-Bot-List#425]
This is a nice idea because every bot list is adding that feature.

**Comment by zennv** [comment]
this is a repo for a bot list, not for a server list lol

**Comment by Zaid-maker** [comment]
@zennv not funny man hahahaha just @Sank6 if he likes that idea.

**Comment by Sank6** [comment]
Yeah, a server list is completely different. Would be too different, sorry.

**Comment by ririko5834** [comment]
Can you make also Discord-Server-List?

**Comment by Zaid-maker** [comment]
> Can you make also Discord-Server-List?

That's what I ask lmao.
