### ISSUE TITLE
Question if not, Future Request

### ISSUE THREAD

**Issue by legofan10** [Sank6/Discord-Bot-List#428]
At the end of every month or so do the bot likes/votes get reset? Or do we have to do it manually. If we do it manually, how do we do it?

**Comment by Sank6** [comment]
I don't think I'll be implementing a regular reset, but if you wanted to do it manually, the likes are stored in the MongoDB database as a property of the bots. It's just a number so setting it to zero would work. `Bots.updateMany({}, { likes: 0 })` would reset all likes

**Comment by legofan10** [comment]
> I don't think I'll be implementing a regular reset, but if you wanted to do it manually, the likes are stored in the MongoDB database as a property of the bots. It's just a number so setting it to zero would work. `Bots.updateMany({}, { likes: 0 })` would reset all likes

What would be the code?
