### ISSUE TITLE
Question if not, Future request #2

### ISSUE THREAD

**Issue by legofan10** [Sank6/Discord-Bot-List#431]
> I don't think I'll be implementing a regular reset, but if you wanted to do it manually, the likes are stored in the MongoDB database as a property of the bots. It's just a number so setting it to zero would work. `Bots.updateMany({}, { likes: 0 })` would reset all likes

What would be the code?

_Originally posted by @legofan10 in https://github.com/Sank6/Discord-Bot-List/issues/428#issuecomment-752220304_

**Comment by Sank6** [comment]
That is the code.

**Comment by legofan10** [comment]
> That is the code.

like the whole code. or the part where that all happens

**Comment by Sank6** [comment]
What?

**Comment by shootdot** [comment]
@legofan10 create a file called `reset.js` in `src/bot/commands/Bots` and paste this code :- 

```js

const { Command } = require('klasa');
const Bots = require("@models/bots");

module.exports = class extends Command {
    constructor(...args) {
        super(...args, {
            permissionLevel: 8,
        });
    }

    async run(message) {
        await Bots.updateMany({}, { likes: 0 });
        message.channel.send('Successfully Reset all Bot Likes...')
};
```

In discord run `[p]reset`

**Comment by legofan10** [comment]
thanks

**Comment by legofan10** [comment]
> @legofan10 create a file called `reset.js` in `src/bot/commands/Bots` and paste this code :-
> 
> ```js
> const { Command } = require('klasa');
> const Bots = require("@models/bots");
> 
> module.exports = class extends Command {
>     constructor(...args) {
>         super(...args, {
>             permissionLevel: 8,
>         });
>     }
> 
>     async run(message) {
>         await Bots.updateMany({}, { likes: 0 });
>         message.channel.send('Successfully Reset all Bot Likes...')
> };
> ```
> 
> In discord run `[p]reset`

error. Unexpected Token last line

**Comment by Sank6** [comment]
Add a `}`

**Comment by legofan10** [comment]
ok

**Comment by legofan10** [comment]
works, thx
