### ISSUE TITLE
Infinite loading on invalid ID

### ISSUE THREAD

**Issue by NotMarx** [Sank6/Discord-Bot-List#435]
# Issue With Searching Users In The Website

Hi, so currently that there are some issues with when searching up users. So when I search `https://localhost/user/notuserid`, the site keep loading and not redirecting users to 404. And also it do works if it's a bot id and how do I prevent that too?

---

**Comment by shootdot** [comment]
Hmm.... Yeah just tried, It's an issue I will look into it for a fix

**Comment by Sank6** [comment]
Fixed: cdb7c25da674b13d9951c2ae5d478340a5a22c44
