### ISSUE TITLE
Questions Regarding To The Bot List

### ISSUE THREAD

**Issue by NotMarx** [Sank6/Discord-Bot-List#438]
Hi, I wanna ask some question about the bot list. 

So does the bot list will list all of the bots? Like if there are 500 bots, it'll list them all or it has a limit like only 25 random bots will be in the list?

And how do I make a header 1, 2 and make it in the center in the long description of adding bots??

Any help would be appreciated!

Thanks.

**Comment by RITIKDHAYAL-PHOENIX** [comment]
it will show all bots ....

**Comment by NotMarx** [comment]
Wait what!?

**Comment by Sank6** [comment]
Yeah the list shows all bots. Use the `h1` and `h2` tags etc. on the the source tab.

**Comment by NotMarx** [comment]
Got some question again if you don't mind, how do I make the bots that showed up in the home page is limit to maybe 20-30 and randomly?

**Comment by Sank6** [comment]
It should have infinite scrolling but I'll have a look if it's not working.

**Comment by NotMarx** [comment]
Ok
