### ISSUE TITLE
offline

### ISSUE THREAD

**Issue by RITIKDHAYAL-PHOENIX** [Sank6/Discord-Bot-List#439]
it's showing me all bots offline but they are online is there anything i have to do with perms? or anything else to fix it ....

**Comment by NotMarx** [comment]
---

Check your bot at [discord.com.developers/applications](https://discord.com/developers/applications) and make sure that the Presence Intent is enabled. That should've fixed it.

---

**Comment by AtomicGaming666** [comment]
this did not work for me

**Comment by Sank6** [comment]
Make sure the bots share a server with the main bot.
