### ISSUE TITLE
follow up

### ISSUE THREAD

**Issue by Misly16** [Sank6/Discord-Bot-List#44]
right so i asked in the devs of klasa and they said i need to use an older version of discord.js for it to work so i did that and removed cache from the bot. It all started up but there are a couple of issues, one of them being that the bot doesnt get added to the server of the error unknown user

![image](https://user-images.githubusercontent.com/60405462/77858412-4cf3d680-71fb-11ea-8e42-c6208bfdc33e.png)

also the editing the bot doesnt work, which it shows errors in the log.
Thank you

**Comment by SplitXPlayZ** [comment]
I have a fix for the edit error.

**Comment by Misly16** [comment]
edit 2. I managed to get everything working except the edit. When trying to edit it will load constantly and provide these errors in the logs 
![image](https://user-images.githubusercontent.com/60405462/77926119-a4e31980-729d-11ea-986b-60a4fd00cdce.png)
It specifically points to this line ` if (!bot.owners.includes(user.id)) return res.redirect(`/error?e=owner`);`

**Comment by Sank6** [comment]
Fixed: b4e8a02

**Comment by Misly16** [comment]
> 
> 
> Fixed: [b4e8a02](https://github.com/Sank6/Discord-Bot-List/commit/b4e8a02acf45f5a780097a9e979b5f321a44555f)

You can now get into the edit page but once you edit it you get redirected to /error/?e=user which gives you the following screen 
![image](https://user-images.githubusercontent.com/60405462/77998287-c50bea80-7328-11ea-9fff-2fb4727cf604.png)
