### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by wolfier74** [Sank6/Discord-Bot-List#446]
Make example code how can you log all likes related to your bot to your bot's support server to webhook using api.

**Comment by Sank6** [comment]
https://github.com/Sank6/Discord-Bot-List/wiki/Bot-developer-APIs

**Comment by wolfier74** [comment]
But i want that when someone like it will be posted to webhook

**Comment by wolfier74** [comment]
Not to return list

**Comment by Sank6** [comment]
There is no webhook implementation. You could periodically check the API and use an in-memory cache.
