### ISSUE TITLE
Webhook for bot likes

### ISSUE THREAD

**Issue by ririko5834** [Sank6/Discord-Bot-List#449]
Add Webhook URL form field when adding and editing bot. All bot votes should be sent to the webhook url. Also send there bot approved and denied logs.
There should be that owner can setup logging webhook for every owned bot.

**Comment by shootdot** [comment]
Should it be ExpressJS Webhook like how top.gg has or just you need to enter the Webook URL It sends you whenever any one likes the bot ?

**Comment by Sank6** [comment]
Added to [dev](https://github.com/Sank6/Discord-Bot-List/tree/development). If there aren't any bugs, I can pr it into master.
