### ISSUE TITLE
New Issue

### ISSUE THREAD

**Issue by Bhcracked** [Sank6/Discord-Bot-List#45]
TypeError: Class extends value undefined is not a constructor or null

Please Help

**Comment by SplitXPlayZ** [comment]
Contact klasa developers, and use discord.js stable. Currently, klasa is unstable.

**Comment by Sank6** [comment]
Also, send the full error stack so we know where that's from

**Comment by namekinggamerboy** [comment]
class KlasaUserStore extends UserStore {

**Comment by namekinggamerboy** [comment]
```rbd/pnpm-volume/3b8871f7-4e62-4975-a5ab-bac7b5009f60/node_modules/.github.com/dirigeants/klasa/aee79a51a6e845b6678e96fdd1a7cc1e27fda435/node_modules/klasa/src/lib/extensions/KlasaUserStore.js:7
class KlasaUserStore extends UserStore {
                             ^
TypeError: Class extends value undefined is not a constructor or null```
Here full error

**Comment by Sank6** [comment]
Yes, that's a Klasa error, check your installation version and contact Klasa devs

**Comment by namekinggamerboy** [comment]
My bot list old no,show error me only info

**Comment by EqualizerNetwork** [comment]
https://klasa.js.org/#/
Install this.
