### ISSUE TITLE
How can I...

### ISSUE THREAD

**Issue by legofan10** [Sank6/Discord-Bot-List#450]
how can i permanently delete a bot from the list?

**Comment by shootdot** [comment]
Delete from website

**Comment by legofan10** [comment]
> Delete from website

like from the admin side

**Comment by shootdot** [comment]
From `me` page

**Comment by legofan10** [comment]
> From `me` page

From an admins point of view. How do they delete the bot by an admin that they don't own

**Comment by shootdot** [comment]
Currently u cant do that

**Comment by Sank6** [comment]
Yeah, I'm hoping to add stuff to the admin dashbaord to be able to manage bots more easily.
