### ISSUE TITLE
TypeError: fields.flat is not a function

### ISSUE THREAD

**Issue by Himo313** [Sank6/Discord-Bot-List#453]
I'm getting this error when i write a command eg: help command
![image](https://user-images.githubusercontent.com/39499245/104107914-85fbc400-52c0-11eb-8cf6-690fd83a622a.png)

**Comment by shootdot** [comment]
@Himo313 Update your NodeJS also make sure your Discord.JS Version is 12. NodeJS version must be greater than 12

**Comment by Himo313** [comment]
> @Himo313 Update your NodeJS also make sure your Discord.JS Version is 12. NodeJS version must be greater than 12

I know that thing and ofc my discord.js is 12 i will reinstall the discordjs
