### ISSUE TITLE
error !

### ISSUE THREAD

**Issue by VortexDev20** [Sank6/Discord-Bot-List#454]
!verify @bot , Cannot read property 'send' of undefined . please help me

**Comment by shootdot** [comment]
Send your full error. Most probably you didn't fill the `mod_log` area in `config.json` or you tried to edit the verify command which ended up causing error .

**Comment by Sank6** [comment]
Also, use the admin panel, not the bot commands.

**Comment by VortexDev20** [comment]
> Send your full error. Most probably you didn't fill the `mod_log` area in `config.json` or you tried to edit the verify command which ended up causing error .

this is the only error and i already completed filling the config.json

**Comment by VortexDev20** [comment]
> Also, use the admin panel, not the bot commands.

about that why my staff can not access to the admin panel ? and if we approve the bot from the panel will it send a message in the channel and to the owner ?

**Comment by Sank6** [comment]
It should still send the message.

**Comment by Sank6** [comment]
Ah, it could be a d.js caching error. Should be fixed now 👍
