### ISSUE TITLE
Marked NSFW Bot Logo On HomePage

### ISSUE THREAD

**Issue by NotMarx** [Sank6/Discord-Bot-List#455]
Hi, how I can make the marked nsfw bot in the search & homepage bot's logo is blur?

**Comment by shootdot** [comment]
It's already there. You can mark any bot as NSFW using command in discord

**Comment by NotMarx** [comment]
I meant by every nsfw bots logo that listed in the website will be blur.

**Comment by NotMarx** [comment]
```pug
doctype html
include includes/head.pug
body(onload="load()")
    include includes/nav.pug
    #content
        span.header
            h1 Discord Bot List
            p Just another bot list for Discord.
        #searchMore
            | Would you like to 
            a(href='/bots/search/') search all bots
        #cards
             each val in cards
                    div.card
                      if (val.nsfw)
                          img.icon.nsfw(src=val.logo)
            span#loading Loading...
```
I tried something like this but it does not work as I planned. Anything I can do to add blur effect on marked nsfw bot at the homepage?

**Comment by shootdot** [comment]
It's already coded and there in github download it and in discord to mark bot as nsfw use command `[p]nsfw @bot` when the bot is marked as nsfw in website the bot logo gets blurred.

**Comment by NotMarx** [comment]
Yeah, I know but when I check my bot at the homepage, the bot's logo isn't blur

**Comment by NotMarx** [comment]
Nevermind, I fixed it by myself
