### ISSUE TITLE
Username & Tag gone on mobile preview 

### ISSUE THREAD

**Issue by NotMarx** [Sank6/Discord-Bot-List#457]
Hi, I just discovered this up when I was using mobile device and see if this might be a bug on mobile.

![980D7880-494F-4D99-9293-FF6828F13174](https://user-images.githubusercontent.com/73813638/104168452-a8acea80-5430-11eb-8fa2-7db4e6797f60.png)

**Comment by Sank6** [comment]
That is definitely not intended, I think there's some class name overlap. I'll have a look.

**Comment by Sank6** [comment]
^ Fixed
