### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by Bobby99as** [Sank6/Discord-Bot-List#464]
please add support for PostgreSQL

**Comment by Sank6** [comment]
All the code currently uses MongoDB and it doesn't really have a "database manager" so adding/changing database would require an entire rewrite. Sorry, I won't be adding this.

**Comment by Bobby99as** [comment]
mongo DB is honestly a bad experience and you can't really host your own database from it you have to rent a database it honestly sucks

**Comment by Sank6** [comment]
You can host your own. Check the [install](https://docs.mongodb.com/manual/installation/#mongodb-community-edition-installation-tutorials) docs.
