### ISSUE TITLE
Update username on username change

### ISSUE THREAD

**Issue by ezywebca** [Sank6/Discord-Bot-List#466]

**Comment by ezywebca** [comment]
Also when a user is to use this there is a issue for say in the code where if a user attempts to add a bot whether verified or not once a user attempts to change that bots name again it does not change at all across the site nor the mongoDB !!!! Amazing Work tho @Sank6 !!!!

**Comment by Sank6** [comment]
#425 but I'll have a look for the second issue.

**Comment by ezywebca** [comment]
@Sank6 please note that this sites being constantly worked on from a dedi and not launched for public use hence even the ending on the domain but i do have rewrite on for db using monogodb defaulted url they provide hense should be able to re-write the bots info like if one was to use a server list and you update your image on server more then 90% of the time places like disboard and others like it will update the pfp .... so maybe something not pulling right from api ... im not 100% on this as im still poking around my self and catching bugs but here is url https://nblist.ga if you check it out you can see

**Comment by ezywebca** [comment]
@Sank6 i tested it more everything will update via the bot when changed in discord.com/developers all but the username of the bot stays the same as what it was first labeled as on initial send off to db for that bot if ur following

**Comment by Sank6** [comment]
You can host your own version if you want. Check the license.

**Comment by ezywebca** [comment]
@Sank6 thank u and we are atm (but also working on it) but this is the one issue with ur code..... i do not know what the fix is on it ive looked and looked

**Comment by ezywebca** [comment]
can u try maybe providing a updated repo with fix ?

**Comment by Sank6** [comment]
Fixed on dev branch: b4fd223. I'll push to master soon

**Comment by ezywebca** [comment]
> Fixed on dev branch: [b4fd223](https://github.com/Sank6/Discord-Bot-List/commit/b4fd2234a2e5a94bfcf22197150042b545b46e54). I'll push to master soon

thank you for update! im sorry to reply on to this!
