### ISSUE TITLE
Shows "User is not in the server" even if they are.

### ISSUE THREAD

**Issue by Lucaslah** [Sank6/Discord-Bot-List#468]
When I try and add a bot the my bot list, I get the User is not in the server even if the user is in the server.

There are not error in console.

Everything else works fine.

**Comment by Sank6** [comment]
Do you have the correct server id in the config?

**Comment by Lucaslah** [comment]
> Do you have the correct server id in the config?

Yes, I'll double check though.

**Comment by Lucaslah** [comment]
Fixed, My server id was incorrect.
