### ISSUE TITLE
How to add my own domain ?

### ISSUE THREAD

**Issue by biswajitguha01** [Sank6/Discord-Bot-List#469]
Hi, I just want to add my domain how to do that

**Comment by Zaid-maker** [comment]
Just add your domain in the config.json file.

**Comment by biswajitguha01** [comment]
Ok but , how to add Api ?? There is no api help page.. how to get servercount,

**Comment by Sank6** [comment]
https://github.com/Sank6/Discord-Bot-List/wiki/Bot-developer-APIs
