### ISSUE TITLE
Help On Canvas Please For Widget

### ISSUE THREAD

**Issue by ezywebca** [Sank6/Discord-Bot-List#472]
Ive tried and tried my main dev whos out atm is the guy who can do canvas like a wiz lol can u shoot me how to edit the .widget (@BotName)  so that i can add in my image layout for widgets so its not grey on white......

**Comment by legofan10** [comment]
Ok, sure. Screenshot the widget file.

**Comment by ezywebca** [comment]
please elaborate my code or the output i would receive from .widget

**Comment by legofan10** [comment]
> please elaborate my code or the output i would receive from .widget

pls friend my alt so he will send u to a link to DM my real account so I can help you. td1610#1990

**Comment by Sank6** [comment]
`src/routes/api/embed.js` and the docs are [here](https://canvasconstructor.js.org/).
