### ISSUE TITLE
issue with server count via .info @botname

### ISSUE THREAD

**Issue by ezywebca** [Sank6/Discord-Bot-List#473]
always shows up as 0 what do i do? or is it a bug to be fixed and rolled out?

**Comment by mafineeek** [comment]
you need to post stats by api endpoint.

**Comment by ezywebca** [comment]
ah alright but still confused as why as the main bot in this script is to keep track of bot likes but should also try to keep a bot track of server count (est) from clicks generated by invite button on site!

**Comment by Sank6** [comment]
Might have more servers from other sources and some clicks may not be actual invites.
