### ISSUE TITLE
also noticed issue inside of users /me section

### ISSUE THREAD

**Issue by ezywebca** [Sank6/Discord-Bot-List#474]
as a bot is rejected you are now left with one option this option is only to resubmit the old bot would it not make more sense allowing the user to edit the bot prior to resubmitting incase if there is a issue with invite perms url or something else....idk maybe have edit and forward off to resubmit after bot edit? make more sense! cheers @Sank6

**Comment by Sank6** [comment]
The resubmit button takes you to a form where you can edit it.
