### ISSUE TITLE
The list with bots disappears

### ISSUE THREAD

**Issue by Mairoooon** [Sank6/Discord-Bot-List#48]
Every time I turn the project off and back on, all the bots that were added in the list are removed, why is this happening?

**Comment by Sank6** [comment]
Does `/api/bots/list` show all the bots still?

**Comment by Mairoooon** [comment]
No there is none is completely empty

**Comment by Mairoooon** [comment]
Is it a problem related to mongodb?

**Comment by Sank6** [comment]
Umm shouldn't be, unless there's an upload problem.

**Comment by Mairoooon** [comment]
so why does this happen? I have only cloned with git and put the rest in .env, it is exactly like in your repository

**Comment by Misly16** [comment]
same thing happening here.

**Comment by MrLivixx** [comment]
I have the same thing, bots are cleared after restarting

**Comment by Mairoooon** [comment]
@Sank6 Does this error appear to you? or it works correctly for you, because there are several with the same error...

**Comment by Sank6** [comment]
Should be fixed: 511181a
