### ISSUE TITLE
New API Code: s4d

### ISSUE THREAD

**Issue by legofan10** [Sank6/Discord-Bot-List#481]
What is the server count API for the language s4d?

**Comment by shootdot** [comment]
Do you mean Python ?

**Comment by legofan10** [comment]
> Do you mean Python ?

IDK? Someone asked my to post with s4d.

**Comment by legofan10** [comment]
He/She says it is made with scratch for discord

**Comment by Sank6** [comment]
The code in the wiki is just sample code for python and nodejs. For anything else, just use the [table](https://github.com/Sank6/Discord-Bot-List/wiki/Bot-developer-APIs#sending-requests).
