### ISSUE TITLE
Sorry, But please read

### ISSUE THREAD

**Issue by A1an-org** [Sank6/Discord-Bot-List#486]
Hey there!
Sorry to disturb you but can i get perms to use the botlist?
under GNU General Public License v3.0 i can't use it for public use if i dont get perms!
Sorry again.

**Comment by Sank6** [comment]
Yeah sure. Under GPL v3, you have permissions to use it commercially. Look at the summary that Github provides [here](https://github.com/Sank6/Discord-Bot-List/blob/master/LICENSE.md)
