### ISSUE TITLE
Allowing server posting like https://github.com/Botrixlist/botrix

### ISSUE THREAD

**Issue by ezywebca** [Sank6/Discord-Bot-List#487]
be cool if you can add in over time m8 a way to post servers as well but btw this work is beautiful! 

😄 keep it up @Sank6 but id like and im sure many others a starting point other then botrix https://github.com/Botrixlist/botrix to use like your clean projects 😄 please respond when you have time! Cheers!

**Comment by Sank6** [comment]
I don't work no this much because I don't use it myself so a serverlist would be a lot, but if someone wants to make a pr, feel free.
