### ISSUE TITLE
editing

### ISSUE THREAD

**Issue by Misly16** [Sank6/Discord-Bot-List#49]
Whenever you edit a bot it displays the following error. 
![image](https://user-images.githubusercontent.com/60405462/79687506-94d8ad00-823f-11ea-9437-8d115463641a.png)

**Comment by Sank6** [comment]
The latest commit should have fixed that. Are you on 27fccda?

**Comment by Misly16** [comment]
yeah i forked it yesterday

**Comment by Misly16** [comment]
also clicking on members doesnt work as it doesnt load

**Comment by Sank6** [comment]
Should be fixed: 511181a

**Comment by Misly16** [comment]
The user problem is fixed but the editing is not.

**Comment by Misly16** [comment]
![image](https://user-images.githubusercontent.com/60405462/80277157-081d6b80-86e5-11ea-9561-e806c42fb1dc.png)
