### ISSUE TITLE
Don't work redirect url

### ISSUE THREAD

**Issue by hama120** [Sank6/Discord-Bot-List#498]
Hi, I'm host your projects but can work on redirect whene you login on your. Discord hi say redirect not working how can fix it please tell me ?

**Comment by shootdot** [comment]
Please send the error you are facing here.

>

**Comment by hama120** [comment]
[Click here to see it ](https://cdn.discordapp.com/attachments/780798080768278578/816690446151450704/Screenshot_20210303_181523_com.microsoft.emmx.jpg)

**Comment by JustReddy7397** [comment]
Have the same lol

**Comment by hama120** [comment]
Site don't work when click login button Authorize don't work please tell me how to fix it?

**Comment by Suleymannn2853** [comment]
i dont know sorry bro

hama120 <notifications@github.com>, 5 Mar 2021 Cum, 13:40 tarihinde şunu
yazdı:

**Comment by JustReddy7397** [comment]
Hey @hama120 go into src/utils/passport.js and change the callbackURL to ur own domain, for example: https://mydomain.com/api/callback or https://mydomain.com:25565/api/callback

**Comment by haydenwalker980** [comment]
@hama120 Did you add the URI to your app?

**Comment by Sank6** [comment]
https://github.com/Sank6/Discord-Bot-List/wiki/FAQs#invalid-oauth2-redirect-uri
