### ISSUE TITLE
Bots do not update

### ISSUE THREAD

**Issue by Akurejs** [Sank6/Discord-Bot-List#500]
When the owners of the bots make changes to them as name and photo, have no effect on the bot list, for example I changed the name of my bot from Robot to Robot 2 ta bot list is still Robot even using the update command, and the photo also does not change.

**Comment by Sank6** [comment]
Are you sure that's not browser cache?

**Comment by Akurejs** [comment]
> Are you sure that's not browser cache?

absolute, to date the bot is with the old name in the botlist has not been updated.

**Comment by Zaid-maker** [comment]
Yes dude the bots does not update.

**Comment by Akurejs** [comment]
will there be correction?

**Comment by Sank6** [comment]
Just tested. It does update. Just go onto the bot's page and refresh it a couple times.
