### ISSUE TITLE
config.js instead of config.json

### ISSUE THREAD

**Issue by wolfier74** [Sank6/Discord-Bot-List#501]
Please use config.js instead config.json for configuration.
This would be good for those who want to put some values to .env, as they can write process.env.value to config.js but not to json file :/

**Comment by HideakiAtsuyo** [comment]
> Please use config.js instead config.json for configuration.
> This would be good for those who want to put some values to .env, as they can write process.env.value to config.js but not to json file :/

It's not This is not a problem, so this issue is pretty useless because you can modify this for yourself and because more than the half of js users use json and not js for config files except when they have big needs like dynamic values and other things...

**Comment by Sank6** [comment]
You can just change it yourself. Change all references of the config file to `config.js` and just export the json. I don't think it's necessary to add this
