### ISSUE TITLE
Api routes: 404 not found

### ISSUE THREAD

**Issue by tovade** [Sank6/Discord-Bot-List#506]
Im getting this error: 
![image](https://user-images.githubusercontent.com/66245404/111496140-53e36400-8740-11eb-966c-a310c93dd40b.png)
Any idea why? thanks!

**Comment by tovade** [comment]
Can i also know where the api routes get loaded? Thanks

**Comment by Sank6** [comment]
There's no code in this repo that has certification. That's either modified code, or not from this.

**Comment by tovade** [comment]
i fixed it (i forgot i had this issue open)

**Comment by tovade** [comment]
btw the code was made by myself
