### ISSUE TITLE
New errors

### ISSUE THREAD

**Issue by Misly16** [Sank6/Discord-Bot-List#51]
![image](https://user-images.githubusercontent.com/60405462/80091740-81885300-8559-11ea-8eb8-3d90bdad083c.png)
After updating to the new commit theres an issue and it keeps erroring.

switching `const bot = require('@bot/index');` to `const bot = require('@bot/index.js');`
didn't fix it either.

**Comment by Sank6** [comment]
Have you not got the files in the bot folder in `/app/src/bot`?

**Comment by Misly16** [comment]
![image](https://user-images.githubusercontent.com/60405462/80098174-56573100-8564-11ea-9b09-a549f1865569.png)
i do

**Comment by bobby365** [comment]
Misly16 are you useing glitch?

**Comment by Misly16** [comment]
> Misly16 are you useing glitch?

Yeah I am

**Comment by bobby365** [comment]
i have that same issue

**Comment by Sank6** [comment]
Ah, I see the problem. The folder names are still capitalised. Apparently GitHub didn't count the folder name changes as actual edits. Fixed now: 031e28f.
