### ISSUE TITLE
future addition

### ISSUE THREAD

**Issue by LuckyTarget** [Sank6/Discord-Bot-List#510]
Very good would be in the long  description of Bot to accept html, markdown css and such things.

**Comment by Zaid-maker** [comment]
You can add it either by yourself because sank6 wont addd it cuz people can put virus through html description.

**Comment by LuckyTarget** [comment]
> You can add it either by yourself because sank6 wont addd it cuz people can put virus through html description.

can you tell me how can i do it ?

**Comment by Sank6** [comment]
It already supports HTML. There's a source button.
