### ISSUE TITLE
Bot issue

### ISSUE THREAD

**Issue by anshtyagi0** [Sank6/Discord-Bot-List#511]
Repl.it: Updating package configuration

--> npm install @utils/fileWalk @root/config.json @utils/passport.js @utils/createAuth.js @routes/bots @routes/theme @utils/getList.js @models/bots @utils/getList @bot/index @utils/checkFields @routes/api @routes/tag @utils/authApi @utils/discordApi @models/users @structures/app.js
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@utils%2fpassport.js - Not found
npm ERR! 404 
npm ERR! 404  '@utils/passport.js@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2021-04-01T06_33_50_819Z-debug.log
exit status 1

Repl.it: Package operation failed.

**Comment by Zaid-maker** [comment]
Please dont use repl.it for hosting the site because there is some problem with the directories in the repl.it

**Comment by Sank6** [comment]
Yeah those aren't repos. That's just module alias
