### ISSUE TITLE
Issue with Delete

### ISSUE THREAD

**Issue by LuckyTarget** [Sank6/Discord-Bot-List#512]
I find out hat the delete button does not work!

**Comment by Zaid-maker** [comment]
It works

**Comment by LuckyTarget** [comment]
> It works unless you know how to use it.
I think there isnt anything hard to know how it works, it just tells you to type the Bot's name, and then "delete" but it does not do anything

**Comment by Zaid-maker** [comment]
Please check that you put the correct channel I'd in the config file where the bot will fire the event and tell you that that the bot is deleted.

**Comment by LuckyTarget** [comment]
> Please check that you put the correct channel I'd in the config file where the bot will fire the event and tell you that that the bot is deleted.

there isnt any channel for this: 
![image](https://user-images.githubusercontent.com/39243722/113479408-996d9400-9497-11eb-8938-efda8fe60d9f.png)
