### ISSUE TITLE
Bug help me on website 

### ISSUE THREAD

**Issue by lordm121** [Sank6/Discord-Bot-List#518]
![Screenshot_20210409_120833_com android chrome](https://user-images.githubusercontent.com/74502300/114157490-5ba3bc00-992c-11eb-99ad-9db4ee2a3af4.jpg)
He said bot offline when all bots online

**Comment by AlfieFrost** [comment]
The bot has to be in the Bot List's discord server for the status feature to work.

**Comment by lordm121** [comment]
The bot is in server but not working

**Comment by Nim1com** [comment]
How did you get the site to replit?

**Comment by lordm121** [comment]
I hosted on replit all work but my problem on offline 🙂 all bot on server

**Comment by lordm121** [comment]
Transfer on github to replit

**Comment by tovade** [comment]
Please enable intents on your bot!

**Comment by lordm121** [comment]
This is or no 
![Screenshot_20210419_232449_com android chrome](https://user-images.githubusercontent.com/74502300/115298732-811f9980-a166-11eb-8bb2-ad95080fdfae.jpg)

**Comment by Sank6** [comment]
Yes. Enabling presence intents will show the bot's status.
