### ISSUE TITLE
Error help

### ISSUE THREAD

**Issue by alex12266** [Sank6/Discord-Bot-List#522]
When trying to verify a bot, it comes out and when trying to access to postulate a bot there is also an error which says inavalid
![image](https://user-images.githubusercontent.com/74673312/115055122-b0a07e80-9ea6-11eb-8446-3edd7063b000.png)
![image](https://user-images.githubusercontent.com/74673312/115055370-f6f5dd80-9ea6-11eb-9205-ede2f1842092.png)

**Comment by reisxd** [comment]
In the first screenshot maybe the bot you are trying to verify does not have a profile picture
In the second screenshot: https://github.com/Sank6/Discord-Bot-List/wiki/FAQs#invalid-oauth2-redirect-uri

**Comment by Sank6** [comment]
I think you're trying to verify a bot that doesn't exist in the database. Add it with the site first.
