### ISSUE TITLE
API returns error 404 

### ISSUE THREAD

**Issue by FriiZoLoGYy** [Sank6/Discord-Bot-List#528]
Currently I am hosting the site in my vps with its own domain, everything is functioning except for the API. Following the table in the wiki, 
`domain/api/auth/liked/botid`

I have tried both requests get & post each returns 404 error. This is also while trying http & https.  Just curious if I'm doing something wrong

**Comment by Sank6** [comment]
Have you put in the correct bot id?

**Comment by FriiZoLoGYy** [comment]
Yes I have

**Comment by Sank6** [comment]
I tested it and it works fine for me. Is the response JSON, or HTML?
