### ISSUE TITLE
Don't work dark theme. :(

### ISSUE THREAD

**Issue by MrLivixx** [Sank6/Discord-Bot-List#54]
When I want to change the subject the page is just updated 
[Gif](https://i.imgur.com/wrA7IdE.gifv)

**Comment by MrLivixx** [comment]
I found another bug
[GiF](https://i.imgur.com/6KtHjLW.gifvl)

**Comment by Misly16** [comment]
> When I want to change the subject the page is just updated
> [Gif](https://i.imgur.com/wrA7IdE.gifv)

Delete the dark theme file and add it again, that fixes it

**Comment by Zaid-maker** [comment]
How?

**Comment by shivamthakkar** [comment]
> I found another bug
> [GiF](https://i.imgur.com/6KtHjLW.gifvl)

How you host this site ?

**Comment by MrLivixx** [comment]
> > I found another bug
> > [GiF](https://i.imgur.com/6KtHjLW.gifvl)
> 
> How you host this site ?

VSD server

**Comment by Zaid-maker** [comment]
I host the site on Glitch

**Comment by Misly16** [comment]
> I host the site on Glitch

Yes its possible but not recommended

**Comment by Zaid-maker** [comment]
Planning of changing it

**Comment by Zaid-maker** [comment]
The best thing is the code is working properly fine on vscode
