### ISSUE TITLE
Google ADs issues.

### ISSUE THREAD

**Issue by Zaid-maker** [Sank6/Discord-Bot-List#543]
so i was trying to run ads on my site but google refuses and saying it's violates privacy how is it?

https://cordx.wtf/79ace6.png

**Comment by Zaid-maker** [comment]
@Sank6

**Comment by Sank6** [comment]
I don't know. Check their privacy policy. Also, not related to this repo.

**Comment by Zaid-maker** [comment]
> I don't know. Check their privacy policy. Also, not related to this repo.

They are not telling anything about privacy
