### ISSUE TITLE
SyntaxError: Unexpected token '.'

### ISSUE THREAD

**Issue by rastacabeza** [Sank6/Discord-Bot-List#552]
![imagen_2021-06-09_163814](https://user-images.githubusercontent.com/66240184/121418190-165a3580-c941-11eb-855d-7ecfbd9665bd.png)
I have that error when I start the bot

**Comment by fnleaks** [comment]
delete

**Comment by rastacabeza** [comment]
> delete

What I have to delete?

**Comment by reisxd** [comment]
> ![imagen_2021-06-09_163814](https://user-images.githubusercontent.com/66240184/121418190-165a3580-c941-11eb-855d-7ecfbd9665bd.png)
> I have that error when I start the bot

You need node 14+ for that to work

**Comment by DBMfan** [comment]
I have the same error, I don't know how to fix it.

**Comment by DBMfan** [comment]
Update: Deleting `await new App(client).listen(port || 8080);` removes all the errors but does not start up the website, Just the discord bot

**Comment by pherngpy** [comment]
i met the same problem but just now it solved idk why

**Comment by DBMfan** [comment]
So how do you solve this issue?

**Comment by reisxd** [comment]
Update your node version to 14

16 Haz 2021 Çar 19:52 tarihinde DBMfan ***@***.***> şunu
yazdı:

**Comment by reisxd** [comment]
The port 80 is already getting used, kill the process that uses the port 80.

16 Haz 2021 Çar 20:12 tarihinde DBMfan ***@***.***> şunu
yazdı:

**Comment by DBMfan** [comment]
How do I do this? I'm using glitch.com by the way.

**Comment by reisxd** [comment]
I don't recommend using glitch and just use another port for the web server
(in config.json) and that will fix it i guess.

16 Haz 2021 Çar 20:19 tarihinde DBMfan ***@***.***> şunu
yazdı:

**Comment by DBMfan** [comment]
Ok I will try that

**Comment by DBMfan** [comment]
Thank you so much, IT works now.

**Comment by DevJaxob** [comment]
Close the issue please @DBMfan

**Comment by DBMfan** [comment]
It isn't my issue.

**Comment by DevJaxob** [comment]
@rastacabeza close
