### ISSUE TITLE
OAuth2 

### ISSUE THREAD

**Issue by pherngpy** [Sank6/Discord-Bot-List#554]
when logging in,

on discord redirects settings there ,
i put
```js
https://example.example.com:3001/api/callback
```
in config.json
```js
    "web": {
        "domain_with_protocol": "https://example.example.com:3001",
        "port": 80,
```
after clicking `authorize` ,
![Picture2](https://user-images.githubusercontent.com/77534483/122143737-a0942380-ce84-11eb-8482-f28604b7ea9e.png)

pls help me , thank you

**Comment by DevJaxob** [comment]
The ports are only for localhosts

**Comment by reisxd** [comment]
> when logging in,
> 
> on discord redirects settings there ,
> i put
> 
> ```js
> https://example.example.com:3001/api/callback
> ```
> 
> in config.json
> 
> ```js
>     "web": {
>         "domain_with_protocol": "https://example.example.com:3001",
>         "port": 80,
> ```
> 
> after clicking `authorize` ,
> ![Picture2](https://user-images.githubusercontent.com/77534483/122143737-a0942380-ce84-11eb-8482-f28604b7ea9e.png)
> 
> pls help me , thank you

Your url is wrong...

**Comment by DevJaxob** [comment]
Yes his domain is absolutely wrong

**Comment by pherngpy** [comment]
It works now thanks you,what do u mean?
Please don't close this issue i have another problem later i'll tell

**Comment by reisxd** [comment]
> It works now thanks you,what do u mean?
> Please don't close this issue i have another problem later i'll tell

So... Will you tell? Or open a new issue?

**Comment by loulou133** [comment]
I also have an OAuth issue, have a look: 
![image](https://user-images.githubusercontent.com/72643424/124102831-fc53d480-da60-11eb-95e3-9f49a1c0bbd0.png)

**Comment by reisxd** [comment]
You need to add your redirect uri in developer portal (discord)

1 Tem 2021 Per 12:39 tarihinde loulou133 ***@***.***> şunu
yazdı:

**Comment by loulou133** [comment]
@reisxd What to put in the redirect?

**Comment by reisxd** [comment]
> @reisxd What to put in the redirect?

your redirect url like:
http(s)://domain/ip(:port)/api/callback

**Comment by reisxd** [comment]
> @reisxd Don't work for me

What did you put to it?

**Comment by loulou133** [comment]
@reisxd 
![image](https://user-images.githubusercontent.com/72643424/124116123-e2b98980-da6e-11eb-8781-fbee7a36a610.png)

**Comment by Zaid-maker** [comment]
You cannot use port 80 lol

**Comment by Zaid-maker** [comment]
Please go to wiki guide or learn basics of programming

**Comment by reisxd** [comment]
> @reisxd
> ![image](https://user-images.githubusercontent.com/72643424/124116123-e2b98980-da6e-11eb-8781-fbee7a36a610.png)

The port 80 is the default port so you dont need to put :80

**Comment by Zaid-maker** [comment]
I bet he put domain wrong in config too

**Comment by loulou133** [comment]
I put the right port so before laughing and saying that it is not the right port, you have to check ... 
![image](https://user-images.githubusercontent.com/72643424/124120672-5316d980-da74-11eb-968a-2daa49485bd4.png)

**Comment by loulou133** [comment]
Then, I already code in JavaScript so tell myself that I have to learn to program ...

**Comment by TeamColaDev** [comment]
Remove the / after localhost in config

**Comment by Zaid-maker** [comment]
The exact things is :
"domain_with_protocol": "http://localhost:3000"

And in developer portal :
http://localhost:3000/api/callback 

Is that simple if that's helps please close the the issue :)

**Comment by loulou133** [comment]
@Zaid-maker and @TeamColaDev Thanks !

**Comment by loulou133** [comment]
@pherngpy please close the the issue :)
