### ISSUE TITLE
What does this mean lol

### ISSUE THREAD

**Issue by PaimonWheeWhee** [Sank6/Discord-Bot-List#557]
![Screen Shot 2021-06-17 at 9 51 27 PM](https://user-images.githubusercontent.com/81248955/122499242-2cf23380-cfb6-11eb-8001-0d65ca7074a5.png)
When I try to run this on replit, this error always pops up. It's annoying and I've never even gotten a chance to start the repl without this popping up. How can I fix this error?

**Comment by LuckyTarget** [comment]
> ![Screen Shot 2021-06-17 at 9 51 27 PM](https://user-images.githubusercontent.com/81248955/122499242-2cf23380-cfb6-11eb-8001-0d65ca7074a5.png)
> When I try to run this on replit, this error always pops up. It's annoying and I've never even gotten a chance to start the repl without this popping up. How can I fix this error?

Instead of trying to start it with the Start button try typing in console `npm start`

**Comment by Sank6** [comment]
Don't think it'll work with repl.it. `module-alias` doesn't seem, to work. You can rewrite the paths if you want.
