### ISSUE TITLE
Webhook Vote

### ISSUE THREAD

**Issue by iHDxP** [Sank6/Discord-Bot-List#567]
Hello, i added bot and edited in the website to add webhook url , but when i vote i don't see the vote in channel that I've set the webhook in + there is no error . can you help please ?

**Comment by Sank6** [comment]
It's not a discord message webhook, it sends a JSON with information about the like. You can change it to a discord message in the code if you want (`src/routes/api/like/index.js`), or have a separate server process it.

**Comment by iHDxP** [comment]
`  // Custom webhook
  if (bot.webhook) {
    fetch(bot.webhook, {
      method: "POST",
      body: JSON.stringify({
        type: "like",
        bot: req.params.id,
        user: req.user.id,
        timestamp: new Date()
      }),
      headers: { 'Content-Type': 'application/json' }
    })
  }
`


what do i need to change here to let custom webhook send like info the the certain channel  .

`JSON.stringify` idk what to de here please help
