### ISSUE TITLE
`  // Custom webhook

### ISSUE THREAD

**Issue by iHDxP** [Sank6/Discord-Bot-List#568]
`  // Custom webhook
  if (bot.webhook) {
    fetch(bot.webhook, {
      method: "POST",
      body: JSON.stringify({
        type: "like",
        bot: req.params.id,
        user: req.user.id,
        timestamp: new Date()
      }),
      headers: { 'Content-Type': 'application/json' }
    })
  }
`

what do i need to change here to let custom webhook send like info the the certain channel  .

`JSON.stringify` idk what to de here please help

_Originally posted by @iHDxP in https://github.com/Sank6/Discord-Bot-List/issues/567#issuecomment-884527265_

**Comment by iHDxP** [comment]
https://github.com/Sank6/Discord-Bot-List/issues/449#issuecomment-757487686

That what i mean but when you edit the bot , and put webhook url you dont receive anything in the channel that webhook created in

**Comment by Sank6** [comment]
https://discord.com/developers/docs/resources/webhook#execute-webhook

**Comment by iHDxP** [comment]
.
