### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by pherngpy** [Sank6/Discord-Bot-List#576]
Hey
I have error while connecting to the database :(
![Screenshot_20210728_194607](https://user-images.githubusercontent.com/77534483/127317118-67c274ed-abe4-41b7-a4c5-63da163ffa4f.JPG)
I use replit (Linux)
Just testing
And I have a question:
Can I connect to multiple databases at once?
mongo_url : ["database 1","database 2","database3","database 4","database 5"]
Please help me to solve the error connecting database issue first
My mongo db url looks like this:
mongodb+srv://THIS IS USERNAME:THIS IS PASSWORD.mongodb.net/myFirstDatabase?retryWrites=true&w=majority
Help me please

>  help me

**Comment by pherngpy** [comment]
I also tried this:
mongodb://fake-name:fake-password@frjo0.mongodb.net/cluster0

**Comment by Sank6** [comment]
You can't have multiple urls. I don't know about repl.it but it should work. Can you paste the full error?

**Comment by pherngpy** [comment]
> You can't have multiple urls. I don't know about repl.it but it should work. Can you paste the full error?

![Screenshot_20210729_075119.JPG](https://user-images.githubusercontent.com/77534483/127410627-e2e3ecab-ee3c-49ed-a035-87f64fc38a32.JPG)

**Comment by Sank6** [comment]
Each bot is going to be a lot less than 100mb lol. With a max long description of 500 characters, it'll probably still be under 1kb for each bot. You won't need more storage.
I have no idea what you're doing. `src/index.js` doesn't have a line 23, which is apparently where your error comes from
Also next time, copy and paste the error in a codeblock as text. It's easier to read than an image.

**Comment by pherngpy** [comment]
> Each bot is going to be a lot less than 100mb lol. With a max long description of 500 characters, it'll probably still be under 1kb for each bot. You won't need more storage.
> I have no idea what you're doing. `src/index.js` doesn't have a line 23, which is apparently where your error comes from
> Also next time, copy and paste the error in a codeblock as text. It's easier to read than an image.

So help me fix please :pleading_face:

**Comment by pherngpy** [comment]
@Sank6 
How to fix this![Screenshot_20210731_145142.JPG](https://user-images.githubusercontent.com/77534483/127731619-653b3edf-0c0d-40f2-9c5b-48e1cd440173.JPG)
