### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by pherngpy** [Sank6/Discord-Bot-List#578]
![Screenshot_20210731_145142.JPG](https://user-images.githubusercontent.com/77534483/127731936-027fa5ce-f358-457d-9add-c0c2db526123.JPG)
help me

**Comment by reisxd** [comment]
> ![Screenshot_20210731_145142.JPG](https://user-images.githubusercontent.com/77534483/127731936-027fa5ce-f358-457d-9add-c0c2db526123.JPG)
> help me

Can you show the full error?
