### ISSUE TITLE
invalid oauth2 redirect_uri 

### ISSUE THREAD

**Issue by mrnothingslee** [Sank6/Discord-Bot-List#584]
![Capture](https://user-images.githubusercontent.com/64817938/130157323-179fa8b7-9094-4b59-90a2-9de690296036.JPG)
I have encounter this this issue while i was trying to login my bot list. I have tried to resolve the problem by searching on google, but nothing worked. I have put my domain in the "domain_with_protocol" in config.json. (http://discorbotlist.tk) but its still not working.

**Comment by ddiabla** [comment]
:/

wiki: _disapears_

**Comment by mrnothingslee** [comment]
> :/
> 
> wiki: _disapears_

I tried, but nothing works

**Comment by popQA17** [comment]
Hi, but in order to use discord's oauth system, you will first need to whitelist the redirect uri (in this case your website) from the [Discord Developer Portal](https://discord.com/developers/applications).

**Comment by mrnothingslee** [comment]
how?

**Comment by DevEvil99** [comment]
> how?

If this is your domain http://discorbotlist.tk yo have to go to [Developer Portal](https://discord.com/developers/applications) and click on your application then go to outh2 section and add this http://discorbotlist.tk/api/callback to Redirects URI

**Comment by Sank6** [comment]
https://github.com/Sank6/Discord-Bot-List/wiki/FAQs#invalid-oauth2-redirect-uri
