### ISSUE TITLE
having a problem on forking

### ISSUE THREAD

**Issue by xinhoshinou** [Sank6/Discord-Bot-List#585]
https://media.discordapp.net/attachments/868482560311832587/879296168448897035/unknown.png?width=890&height=384

**Comment by Juancho5945** [comment]
> https://media.discordapp.net/attachments/868482560311832587/879296168448897035/unknown.png?width=890&height=384

***The same thing happens to me***

**Comment by Sank6** [comment]
Doesn't work on repl.it. Try running it on a vps.
