### ISSUE TITLE
I cant start it

### ISSUE THREAD

**Issue by EmanSza** [Sank6/Discord-Bot-List#60]
when I try to start it this happens 
![image](https://user-images.githubusercontent.com/44507685/80554648-d4b83680-899b-11ea-8a0e-94f43c8e3830.png)

**Comment by Misly16** [comment]
you need to install env

**Comment by inhydrox** [comment]
```js
npm install dotenv
```

**Comment by Sank6** [comment]
Well you need to install everything. `dotenv` just happens to be the first one that you need so it's the first to throw an error. Run `npm i`
