### ISSUE TITLE
can't edit bots

### ISSUE THREAD

**Issue by bobby365** [Sank6/Discord-Bot-List#61]
when I go to edit my bot it always gives an error

**Comment by Misly16** [comment]
Already reported https://github.com/Sank6/Discord-Bot-List/issues/49

**Comment by bobby365** [comment]
it says closed

**Comment by Misly16** [comment]
yes but he can still see it

**Comment by bobby365** [comment]
I'm just going to keep this open

**Comment by Sank6** [comment]
Fixed: c052739
