### ISSUE TITLE
Authorization token is undefined?

### ISSUE THREAD

**Issue by Zaid-maker** [Sank6/Discord-Bot-List#63]
when ever try to generate authorization token it's says `Authorization Token is: undefined`. please tell me how i fix this error

**Comment by MrLivixx** [comment]
Can you send a screenshot of the error or the terminal log?

**Comment by Zaid-maker** [comment]
there is no error in terminal

**Comment by Zaid-maker** [comment]
when i click on authorization token in edit bot section it says undefined

**Comment by Zaid-maker** [comment]
and there is number of problems in the code idk why?

**Comment by Zaid-maker** [comment]
[Error](https://cdn.discordapp.com/attachments/706523389107372033/706589848747769976/Capture.PNG)

**Comment by bobby365** [comment]
I get that too when I try to get my authorization token

**Comment by Misly16** [comment]
an issue about this was already made. https://github.com/Sank6/Discord-Bot-List/issues/59

**Comment by Zaid-maker** [comment]
when fixing the issue

**Comment by Misly16** [comment]
> 
> 
> when fixing the issue

Whenever Sank see's this

**Comment by Zaid-maker** [comment]
Anyways is there any example of using API and how to fully use it

**Comment by Sank6** [comment]
Fixed: 27da2e4
