### ISSUE TITLE
Problem in Username 

### ISSUE THREAD

**Issue by shivamthakkar** [Sank6/Discord-Bot-List#69]
When i login to site my username is shown like this please tell how to fix it 
![Screenshot_2020-05-16-22-51-27-74](https://user-images.githubusercontent.com/51533539/82126089-f56bf300-97c7-11ea-9e72-2e00a14348dc.png)

**Comment by Misly16** [comment]
Its because your name has special characters

**Comment by shivamthakkar** [comment]
> Its because your name has special characters

No my name dont have any special characters 
![Screenshot_2020-05-16-22-56-53-42_572064f74bd5f9fa804b05334aa4f912](https://user-images.githubusercontent.com/51533539/82126183-96f34480-97c8-11ea-8c3c-ad3b03356c73.png)

**Comment by shivamthakkar** [comment]
@Misly16 sir please reply

**Comment by Misly16** [comment]
Then it must be to do with the spaces with your username.

**Comment by shivamthakkar** [comment]
@Misly16 how ?

**Comment by Sank6** [comment]
Shouldn't be happening. I can't seem to reproduce it. Is the issue still occurring in the latest version

**Comment by shinchan-pb-xi** [comment]
yes, it is still occurring

**Comment by Zaid-maker** [comment]
Please fix this issue @Sank6

**Comment by sayantan300** [comment]
Same with me, I'm PROGAMER 😎 and it shows that %nos. And actually looks bad on the top of site...

**Comment by Sank6** [comment]
Fixed: ed286c8
