### ISSUE TITLE
When I delete a bot with mongodb

### ISSUE THREAD

**Issue by Vulsa** [Sank6/Discord-Bot-List#70]
When I delete a column (a bot) on mongodb and add the bot again (for my tests), it redirects me to "/error/?e=unknown" and when I go to my profile, it tells me that the bot is checked and exists and has recreated the column in mongodb.

Help me please.

**Comment by Misly16** [comment]
#57

**Comment by Vulsa** [comment]
I don't have the same problem, my problem is with mongodb. In my cmd, there is no error it's just that my bot is added again, and the column is added again in mongodb

**Comment by Sank6** [comment]
Make sure that that the admin bot's role is higher than all the other roles.
