### ISSUE TITLE
Invalid OAuth2 Redirect URL

### ISSUE THREAD

**Issue by HaryoPratama** [Sank6/Discord-Bot-List#71]
i got invalid OAuth2 Redirect url
![image](https://user-images.githubusercontent.com/62017665/82132851-cfe4e680-97d3-11ea-9acf-0186465d4dbb.png)

at login.js: https://discordapp.com/api/oauth2/authorize?client_id=${CLIENT_ID}&response_type=code&scope=identify&redirect_uri=${encodeURIComponent(DOMAIN)}/api/callback

**Comment by shivamthakkar** [comment]
> i got invalid OAuth2 Redirect url
> ![image](https://user-images.githubusercontent.com/62017665/82132851-cfe4e680-97d3-11ea-9acf-0186465d4dbb.png)
> 
> at login.js: [https://discordapp.com/api/oauth2/authorize?client_id=${CLIENT_ID}&response_type=code&scope=identify&redirect_uri=${encodeURIComponent(DOMAIN)}/api/callback](https://discordapp.com/api/oauth2/authorize?client_id=$%7BCLIENT_ID%7D&response_type=code&scope=identify&redirect_uri=$%7BencodeURIComponent(DOMAIN)%7D/api/callback)

Did you read Setup Guide ?

**Comment by HaryoPratama** [comment]
> > i got invalid OAuth2 Redirect url
> > ![image](https://user-images.githubusercontent.com/62017665/82132851-cfe4e680-97d3-11ea-9acf-0186465d4dbb.png)
> > 
> > at login.js: [https://discordapp.com/api/oauth2/authorize?client_id=${CLIENT_ID}&response_type=code&scope=identify&redirect_uri=${encodeURIComponent(DOMAIN)}/api/callback](https://discordapp.com/api/oauth2/authorize?client_id=$%7BCLIENT_ID%7D&response_type=code&scope=identify&redirect_uri=$%7BencodeURIComponent(DOMAIN)%7D/api/callback)
> 
> Did you read Setup Guide ? 

Already read it

**Comment by HaryoPratama** [comment]
It's need added redirect to The web than /api/callback right

**Comment by HaryoPratama** [comment]
Solved i fix something, because 
![image](https://user-images.githubusercontent.com/62017665/82136606-261b4f00-97ff-11ea-9a8c-3d89e17ec7b6.png) i found be4 is uri not url.
