### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by EvanHanna12** [Sank6/Discord-Bot-List#77]
As i keep trying to log in its send me back to the authoraztion link and won't let me login any solutions to fix this promblem because i have no errors in logs!

**Comment by Zaid-maker** [comment]
Yes same problem

**Comment by Zaid-maker** [comment]
@Sank6

**Comment by Misly16** [comment]
You have to set a callback url in discord afaik

**Comment by EvanHanna12** [comment]
> You have to set a callback url in discord afaik

Where is discord afaik

**Comment by Misly16** [comment]
Afaik = as far as I know

**Comment by Misly16** [comment]
And you can set the callback url in the dev portal

**Comment by EvanHanna12** [comment]
Oh i done that @Misly16 and its still doing it

**Comment by Misly16** [comment]
What errors are you getting in the console

**Comment by JakeyPrime** [comment]
> What errors are you getting in the console

There's no errors in console, it just sends you back to the authorization over and over again, unless you deny auth, then you get an error about it being denied; no errors otherwise.

**Comment by Sank6** [comment]
Fixed: 8525414
