### ISSUE TITLE
how do I host?

### ISSUE THREAD

**Issue by 4rlon** [Sank6/Discord-Bot-List#78]
Hey guys please anybody know how can I host this?

**Comment by Misly16** [comment]
you can host it on a vps but you can also host it on glitch

**Comment by Zaid-maker** [comment]
some things will not work so use a vps

**Comment by Misly16** [comment]
This version is currently broken anyway.

-------- Original Message --------

**Comment by CheatcodeArlon** [comment]
What do you guys think I need to do first I mean is there any guide?

**Comment by CheatcodeArlon** [comment]
For glitch

**Comment by Zaid-maker** [comment]
hmmmmm

**Comment by Misly16** [comment]
configure the env file and start it

**Comment by CheatcodeArlon** [comment]
Wdym? Just filling the URL and token and stuffs it will start working?

**Comment by Misly16** [comment]
> Wdym? Just filling the URL and token and stuffs it will start working?

Yes

**Comment by CheatcodeArlon** [comment]
but it didn't work

**Comment by CheatcodeArlon** [comment]
but rn my website is hosted in another web hosting so is it fine?

**Comment by CheatcodeArlon** [comment]
or  have to change its nameservers to default

**Comment by CheatcodeArlon** [comment]
anyways I had hosted it btw do you guys know why after setting the api calback its still redirecting the authorize page?

**Comment by Zaid-maker** [comment]
yes this same problem is happening to me also

**Comment by Zaid-maker** [comment]
Demo: https://a-bot-list.glitch.me

**Comment by Misly16** [comment]
The latest version sadly broke many features

**Comment by Sank6** [comment]
Fixed: 8525414
