### ISSUE TITLE
loop

### ISSUE THREAD

**Issue by exeyph** [Sank6/Discord-Bot-List#79]
Clicking on the login screen is coming, editing is entering the view, and then the screen for entering guinea comes up.

**Comment by tireder** [comment]
same it just repeats the authorize

**Comment by exeyph** [comment]
How to fix?

**Comment by tireder** [comment]
Idk need a fix to

**Comment by JakeyPrime** [comment]
Getting the repeat authorize as well, it seems.

**Comment by Sank6** [comment]
Fixed: 0728071

**Comment by Zaid-maker** [comment]
Thank you dude you saved my bit list
