### ISSUE TITLE
No env file :( gimme env details

### ISSUE THREAD

**Issue by TrickyhubYT** [Sank6/Discord-Bot-List#89]

**Comment by shinchan-pb-xi** [comment]
please give me env file also

**Comment by TheTeaCup** [comment]
you make the .env your self.

**Comment by shivamthakkar** [comment]
@TheTeaCup Have you maked .env ? If yes then please help me

**Comment by TheTeaCup** [comment]
@shivamthakkar 
it's best that you spend time looking at a `.env` file.
```
PORT=
DISCORD_TOKEN=
MONGO_DB_URL=
```
if you still are having issues let me know but ill try my best since it seems like you're a beginner and i refuse to spoon-feed.

**Comment by Sank6** [comment]
Added it back: 1b8a910
