### ISSUE TITLE
How to Decline Bot ?

### ISSUE THREAD

**Issue by shinchan-pb-xi** [Sank6/Discord-Bot-List#93]

**Comment by Zaid-maker** [comment]
By a command remove xd

**Comment by shinchan-pb-xi** [comment]
lol please help

**Comment by Misly16** [comment]
Look into the code, its in their

**Comment by shinchan-pb-xi** [comment]
No its not there

**Comment by Misly16** [comment]
Smh 
https://www.github.com/Sank6/Discord-Bot-List/tree/master/src%2Fbot%2Fcommands%2FBots%2Fremove.js

**Comment by shinchan-pb-xi** [comment]
ty
