### ISSUE TITLE
Unable To Edit This Button

### ISSUE THREAD

**Issue by shinchan-pb-xi** [Sank6/Discord-Bot-List#95]
### I am unable To edit this button text please tell me from where i can edit this button 
![image](https://user-images.githubusercontent.com/66065917/86367006-1ebde100-bc99-11ea-83de-a59f84338a11.png)

**Comment by Misly16** [comment]
Just search for that with your editor and find it.

**Comment by Sank6** [comment]
It's in one of the `.ejs` files in the `dynamic` folder.
