### ISSUE TITLE
Where Does Mongo DB Saves Data

### ISSUE THREAD

**Issue by shinchan-pb-xi** [Sank6/Discord-Bot-List#96]
I am unable to find that data/db file where mogodb saves data

**Comment by Zaid-maker** [comment]
Stupid questions

**Comment by Misly16** [comment]
@shinchan-pb-xi mongo saves data on its own servers, not on a local file.

**Comment by shivamthakkar** [comment]
> Stupid questions

Stupid people

**Comment by shivamthakkar** [comment]
> @shinchan-pb-xi mongo saves data on its own servers, not on a local file.

Can you tell me where pls

**Comment by Misly16** [comment]
in your mongo atlas....

**Comment by Sank6** [comment]
The MongoDB is an externally hosted free database and it's run by [Atlas](https://www.mongodb.com/cloud/atlas).
