### ISSUE TITLE
configuration

### ISSUE THREAD

**Issue by powerflips** [Sank6/Discord-Bot-List#98]
does anyone help me to configure in MONGO_DB_URL which url I should put from mongo? I already created the account and the database but I don't know which url is there, and also someone informs me if the files have that is in a cpanel hosting

**Comment by Sank6** [comment]
I don't think you can set it up on cPanel, but the later version of it does have NodeJS support so I think you can give it a try. For the Mongo DB URL, create a free tier cluster and then click the `connect` button. Then create a database user and pass and add the IP address of the location you're hosting it, or add `0.0.0.0/0` to make your database public. 
On the choose a connection page, select **Connect your application** and it'll give you the connection url. This should be your `MONGO_DB_URL`
