### ISSUE TITLE
plz help 

### ISSUE THREAD

**Issue by AtomicGaming666** [Sank6/Discord-Bot-List#99]
hey o cant install this git@github.com:kyranet/canvasConstructor.git

i just get this 

![image](https://user-images.githubusercontent.com/39306849/86616491-40043180-bff9-11ea-8e22-d37339ac6333.png)

**Comment by AtomicGaming666** [comment]
i got past that 
now hosting on glitch but it takes its time to start can you tell me why 

![image](https://user-images.githubusercontent.com/39306849/86618567-7d1df300-bffc-11ea-902c-2301d2699af6.png)



it just sits there

**Comment by AtomicGaming666** [comment]
i have also never used this DB befor

**Comment by AtomicGaming666** [comment]
hello this is my new error

![image](https://user-images.githubusercontent.com/39306849/86721322-36b2ad80-c069-11ea-8ae6-fc3c0c39b611.png)

**Comment by AtomicGaming666** [comment]
i also get this when i try to add a bot


![image](https://user-images.githubusercontent.com/39306849/86722487-47175800-c06a-11ea-9221-ab9a6b592ec7.png)

**Comment by Sank6** [comment]
Firstly, I don't know if you can host it on glitch. Also, that error is `missing access` which I'm guessing means that your Discord bot doesn't have enough perms to do something.

**Comment by AtomicGaming666** [comment]
it has admin

**Comment by AtomicGaming666** [comment]
i also cant get dark theme to work

**Comment by AtomicGaming666** [comment]
i also got it to host on glitch 

https://atomic-bot-list.glitch.me

thats the site

**Comment by Sank6** [comment]
> i also cant get dark theme to work
I think that might have been because the folder name was still capitalised in the route file for theme. Try it now: a3938fe

**Comment by AtomicGaming666** [comment]
it still not working

**Comment by Sank6** [comment]
Seems to work for me on there. Glitch seems to be doing some weird caching stuff though. Make sure you hard refresh

**Comment by AtomicGaming666** [comment]
hey do i hard refresh

**Comment by AtomicGaming666** [comment]
also sould add a edit button to this page 

https://atomic-bot-list.glitch.me/bots/601597561375293461/

also i got dark mode to work 
and found out for to hard refresh

**Comment by Sank6** [comment]
The edit button only shows on your profile page. The page you sent is a publicly accessible page and appears the same for everyone.

**Comment by AtomicGaming666** [comment]
oh ok

**Comment by AtomicGaming666** [comment]
thx for the help

**Comment by AtomicGaming666** [comment]
hey do you thing you can add a votes thing ????

**Comment by Zaid-maker** [comment]
Yes I have a code for it but it only one time and I making a Pull Request
on this repo.

**Comment by AtomicGaming666** [comment]
??

**Comment by AtomicGaming666** [comment]
hey its not loading no more what do i do

![image](https://user-images.githubusercontent.com/39306849/87240498-6abd1280-c45d-11ea-9483-8a51b5f07a23.png)


it gets to here then stops

**Comment by Sank6** [comment]
Please don't host it on glitch. It's buggy and not meant for full scale websites with backend.

**Comment by AtomicGaming666** [comment]
ok but i have been doing some edits to it and i added so you can put a website for the bot but its not working now 
and there is no errors

**Comment by Sank6** [comment]
If you've edited the code then I don't really know why it's not working. It seems to be working fine for me.
